### DISCUSSION TITLE
Job 'SCHEDULER' exit with error: failed to load rest config

### DISCUSSION THREAD

**Discussion by patsevanton** [goharbor/harbor-helm#1532] [Q&A]
Hello! Thanks for helm chart harbor
I use helm chert version 1.12.2
I get error:
```
harbor-jobservice-xx-zz [ERROR] [/jobservice/api/router.go:82]: Serve http request 'GET /api/v1/config' failed with error: {"code":10011,"message":"unauthorized","details":"unauthorized"}
harbor-jobservice-xx-zz [ERROR] [/jobservice/api/router.go:82]: Serve http request 'POST /api/v1/jobs' failed with error: {"code":10011,"message":"unauthorized","details":"unauthorized"}
harbor-jobservice-xx-zz [ERROR] [/jobservice/api/router.go:82]: Serve http request 'GET /api/v1/config' failed with error: {"code":10011,"message":"unauthorized","details":"unauthorized"}
harbor-jobservice-xx-zz [ERROR] [/pkg/config/rest/rest.go:50]: Failed on load rest config err:http error: code 401, message {"errors":[{"code":"UNAUTHORIZED","message":"only internal service is allowed to call this API"}]}
harbor-jobservice-xx-zz [ERROR] [/jobservice/runner/redis.go:123]: Job 'SCHEDULER:cb67d3ee2785b247d60388bc' exit with error: failed to load rest config
harbor-jobservice-xx-zz [ERROR] [/pkg/config/rest/rest.go:50]: Failed on load rest config err:http error: code 401, message {"errors":[{"code":"UNAUTHORIZED","message":"only internal service is allowed to call this API"}]}
harbor-jobservice-xx-zz [ERROR] [/jobservice/runner/redis.go:123]: Job 'SCHEDULER:cb67d3ee2785b247d60388bc' exit with error: failed to load rest config
harbor-jobservice-xx-zz [ERROR] [/pkg/config/rest/rest.go:50]: Failed on load rest config err:http error: code 401, message {"errors":[{"code":"UNAUTHORIZED","message":"only internal service is allowed to call this API"}]}
harbor-jobservice-xx-zz [ERROR] [/jobservice/runner/redis.go:123]: Job 'SCHEDULER:cb67d3ee2785b247d60388bc' exit with error: failed to load rest config
harbor-core-yy-ww [ERROR] [/pkg/audit/forward.go:44]: failed to create audit log, error dial tcp: missing address
harbor-core-yy-ww [ERROR] [/lib/config/userconfig.go:44]: failed to load config, error unexpected EOF
harbor-core-yy-ww [ERROR] [/lib/http/error.go:57]: {"errors":[{"code":"UNKNOWN","message":"unknown: unexpected EOF"}]} 
harbor-core-yy-ww [ERROR] [/pkg/task/task.go:116]: delete task 3 from db due to failed to submit job SCHEDULER, error: http error: code 401, message {"code":10011,"message":"unauthorized","details":"unauthorized"}
harbor-registry-7898ff9cc5-qtclq registry time="2023-07-03T13:45:10.206426404Z" level=info msg="Purge uploads finished.  Num deleted=0, num errors=1" 
```

My values:
```
    expose:
      type: ingress
      tls:
        certSource: secret
        secret:
          secretName: "harbor-ingress"
      ingress:
        hosts:
          core: harbor-official.corp.domain
          notary: notary-official.corp.domain
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: cluster-issuer
          ingress.kubernetes.io/ssl-redirect: "true"
          ingress.kubernetes.io/proxy-body-size: "0"
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
          cert-manager.io/common-name: 'harbor-official.corp.domain'
    externalURL: https://harbor-official.corp.domain
    ipFamily:
      ipv6:
        enabled: false
    persistence:
      persistentVolumeClaim:
        registry:
          size: 200Gi
    harborAdminPassword: "mysuperpassword"
    cache:
      enabled: true
    notary:
      enabled: false
```

How fix this error ?
