### DISCUSSION TITLE
Connecting Harbor to MinIO Tenant

### DISCUSSION THREAD

**Discussion by coffee-time-design** [goharbor/harbor-helm#1760] [Q&A]
I've been at it for awhile and I'm at a bit of a loss in terms of connecting Harbor to MinIO.
I have been using docker-registry for awhile and it works, but I wanted the proxy cache feature that Harbor has.
I read a few guides and it seemed pretty straight forward, I built a HA deployment of Harbor, using the helm chart, no issues, no errors, but when I pull an image, like so:
`docker pull registry.example.com/docker-proxy/library/hello-world:latest`
I get an error about the AWS access key:
```
harbor-registry-846697b7b-hlgf9 registry level=error msg="response completed with error" auth.user.name="harbor_registry_user" err.code=unknown err.detail="s3aws: InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.
harbor-core-5675587b56-pzzgl core [ERROR] [/controller/proxy/controller.go:292]: error while putting blob to local repo, http status code: 500, body: {"errors":[{"code":"UNKNOWN","message":"unknown error","detail":{"DriverName":"s3aws","Enclosed":{"RequestFailure":{}}}}]}
```
I've tried a few dozen different things, but I always seem to get the same response.
The working helm chart of docker-registry uses:
```
  s3:
    secretRef: "s3-credentials"
s3:
 region: us-east-1
 regionEndpoint: ${MINIO_URL}/
 bucket: ${BUCKET_NAME}
 rootdirectory: /
 encrypt: false
 secure: true
```
The not so working chart of harbor uses:
```
  imageChartStorage:
    disableredirect: true
    type: s3
    s3:
      existingSecret: "s3-credentials"
      region: us-east-1
      regionEndpoint: ${MINIO_URL}/
      bucket: ${BUCKET_NAME}
      rootdirectory: /
      encrypt: false
      skipverify: true
      secure: true
```
      
I've tested against s3 with the aws cli and it works fine, I'm probably missing something simple...
I just wish I knew what AWS Access Key Harbor was presenting to MinIO, then maybe I could figure it out in reverse.
