### DISCUSSION TITLE
docker login return 404 Not Found

### DISCUSSION THREAD

**Discussion by rgaiacs** [goharbor/harbor-helm#1822] [Q&A]
I'm testing Harbor and for that I deployed it using Helm (full configuration at the end of this message).

The pods are running!

```bash
kubectl get pods
```

```
binderhub-harbor-core-6598dd5d4f-tnqpj          1/1     Running   0             92m
binderhub-harbor-database-0                     1/1     Running   0             92m
binderhub-harbor-jobservice-78fffcf85-4qcqv     1/1     Running   2 (92m ago)   92m
binderhub-harbor-nginx-765f7dd4dd-qq9p6         1/1     Running   0             92m
binderhub-harbor-portal-56c4c9d968-cjp6d        1/1     Running   0             92m
binderhub-harbor-redis-0                        1/1     Running   0             92m
binderhub-harbor-registry-5b69db4696-rpdrc      2/2     Running   0             92m
binderhub-harbor-trivy-0                        1/1     Running   0             92m
```

And the services are also running!

```bash
kubectl get svc
```

```
binderhub-harbor-core                ClusterIP   10.108.118.64    <none>        80/TCP                       95m
binderhub-harbor-database            ClusterIP   10.100.243.22    <none>        5432/TCP                     95m
binderhub-harbor-jobservice          ClusterIP   10.96.112.196    <none>        80/TCP                       95m
binderhub-harbor-portal              ClusterIP   10.108.176.167   <none>        80/TCP                       95m
binderhub-harbor-redis               ClusterIP   10.100.202.174   <none>        6379/TCP                     95m
binderhub-harbor-registry            ClusterIP   10.108.161.113   <none>        5000/TCP,8080/TCP            95m
binderhub-harbor-trivy               ClusterIP   10.109.197.139   <none>        8080/TCP                     95m
harbor                               NodePort    10.100.221.78    <none>        80:30002/TCP                 95m
```

I can access Harbor web interface using http://194.95.75.20:30002 (`194.95.75.20` is the IP of the server and `30002` is the exposed node port).

When I try to login using the docker client with

```bash
docker login http://194.95.75.20:30002
```

the output is

```
Error response from daemon: Get "http://194.95.75.20:30002/v2/": error parsing HTTP 404 response body: invalid character '<' looking for beginning of value: "<html>\r\n<head><title>404 Not Found</title></head>\r\n<body>\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n"
```

What is wrong in my configuration?

# Helm Chart configuration

```yaml
harbor:
  affinity:
    requiredDuringSchedulingRequiredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: harbor
          operator: In
          values:
          - "true"
  caSecretName: ""
  cache:
    enabled: false
    expireHours: 24
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    privileged: false
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  core:
    affinity: {}
    automountServiceAccountToken: false
    existingSecret: ""
    existingXsrfSecret: ""
    existingXsrfSecretKey: CSRF_KEY
    extraEnvVars: []
    gdpr:
      auditLogsCompliant: false
      deleteUser: false
    image:
      repository: goharbor/harbor-core
      tag: v2.11.1
    initContainers: []
    nodeSelector: {}
    podAnnotations: {}
    podLabels: {}
    quotaUpdateProvider: db
    replicas: 1
    revisionHistoryLimit: 10
    secret: ""
    secretName: ""
    serviceAccountName: ""
    serviceAnnotations: {}
    startupProbe:
      enabled: true
      initialDelaySeconds: 10
    tokenCert: ""
    tokenKey: ""
    tolerations: []
    topologySpreadConstraints: []
    xsrfKey: ""
  database:
    external:
      coreDatabase: registry
      existingSecret: ""
      host: 192.168.0.1
      password: password
      port: "5432"
      sslmode: disable
      username: user
    internal:
      affinity: {}
      automountServiceAccountToken: false
      extrInitContainers: []
      extraEnvVars: []
      image:
        repository: goharbor/harbor-db
        tag: v2.11.1
      initContainer:
        migrator: {}
        permissions: {}
      livenessProbe:
        timeoutSeconds: 1
      nodeSelector: {}
      password: changeit
      readinessProbe:
        timeoutSeconds: 1
      serviceAccountName: ""
      shmSizeLimit: 512Mi
      tolerations: []
    maxIdleConns: 100
    maxOpenConns: 900
    podAnnotations: {}
    podLabels: {}
    type: internal
  enableMigrateHelmHook: false
  existingSecretAdminPasswordKey: HARBOR_ADMIN_PASSWORD
  existingSecretSecretKey: ""
  exporter:
    affinity: {}
    automountServiceAccountToken: false
    cacheCleanInterval: 14400
    cacheDuration: 23
    extraEnvVars: []
    image:
      repository: goharbor/harbor-exporter
      tag: v2.11.1
    nodeSelector: {}
    podAnnotations: {}
    podLabels: {}
    replicas: 1
    revisionHistoryLimit: 10
    serviceAccountName: ""
    tolerations: []
    topologySpreadConstraints: []
  expose:
    clusterIP:
      annotations: {}
      labels: {}
      name: harbor
      ports:
        httpPort: 80
        httpsPort: 443
      staticClusterIP: ""
    ingress:
      annotations:
        ingress.kubernetes.io/proxy-body-size: "0"
        ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
      className: ""
      controller: default
      hosts:
        core: core.harbor.domain
      kubeVersionOverride: ""
      labels: {}
    loadBalancer:
      IP: ""
      annotations: {}
      labels: {}
      name: harbor
      ports:
        httpPort: 80
        httpsPort: 443
      sourceRanges: []
    nodePort:
      annotations: {}
      labels: {}
      name: harbor
      ports:
        http:
          nodePort: 30002
          port: 80
        https:
          nodePort: 30003
          port: 443
    persistence:
      enabled: false
    tls:
      auto:
        commonName: ""
      certSource: auto
      enabled: false
      secret:
        secretName: ""
    type: nodePort
  externalURL: http://194.95.75.20
  global: {}
  harborAdminPassword: Harbor12345
  imagePullPolicy: IfNotPresent
  imagePullSecrets: null
  internalTLS:
    certSource: auto
    core:
      crt: ""
      key: ""
      secretName: ""
    enabled: false
    jobservice:
      crt: ""
      key: ""
      secretName: ""
    portal:
      crt: ""
      key: ""
      secretName: ""
    registry:
      crt: ""
      key: ""
      secretName: ""
    strong_ssl_ciphers: false
    trivy:
      crt: ""
      key: ""
      secretName: ""
    trustCa: ""
  ipFamily:
    ipv4:
      enabled: true
    ipv6:
      enabled: true
  jobservice:
    affinity: {}
    automountServiceAccountToken: false
    existingSecret: ""
    existingSecretKey: JOBSERVICE_SECRET
    extraEnvVars: []
    image:
      repository: goharbor/harbor-jobservice
      tag: v2.11.1
    initContainers: []
    jobLoggers:
    - file
    loggerSweeperDuration: 14
    maxJobWorkers: 10
    nodeSelector: {}
    notification:
      webhook_job_http_client_timeout: 3
      webhook_job_max_retry: 3
    podAnnotations: {}
    podLabels: {}
    reaper:
      max_dangling_hours: 168
      max_update_hours: 24
    replicas: 1
    revisionHistoryLimit: 10
    secret: ""
    serviceAccountName: ""
    tolerations: []
  logLevel: info
  metrics:
    core:
      path: /metrics
      port: 8001
    enabled: false
    exporter:
      path: /metrics
      port: 8001
    jobservice:
      path: /metrics
      port: 8001
    registry:
      path: /metrics
      port: 8001
    serviceMonitor:
      additionalLabels: {}
      enabled: false
      interval: ""
      metricRelabelings: []
      relabelings: []
  nginx:
    affinity: {}
    automountServiceAccountToken: false
    extraEnvVars: []
    image:
      repository: goharbor/nginx-photon
      tag: v2.11.1
    nodeSelector: {}
    podAnnotations: {}
    podLabels: {}
    replicas: 1
    revisionHistoryLimit: 10
    serviceAccountName: ""
    tolerations: []
    topologySpreadConstraints: []
  persistence:
    enabled: false
    imageChartStorage:
      azure:
        accountkey: base64encodedaccountkey
        accountname: accountname
        container: containername
        existingSecret: ""
      disableredirect: false
      filesystem:
        rootdirectory: /storage
      gcs:
        bucket: bucketname
        encodedkey: base64-encoded-json-key-file
        existingSecret: ""
        useWorkloadIdentity: false
      oss:
        accesskeyid: accesskeyid
        accesskeysecret: accesskeysecret
        bucket: bucketname
        existingSecret: ""
        region: regionname
      s3:
        bucket: bucketname
        region: us-west-1
      swift:
        authurl: https://storage.myprovider.com/v3/auth
        container: containername
        existingSecret: ""
        password: password
        username: username
      type: filesystem
    persistentVolumeClaim:
      database:
        accessMode: ReadWriteMany
        annotations: {}
        existingClaim: ""
        size: 1Gi
        storageClass: standard
        subPath: ""
      jobservice:
        jobLog:
          accessMode: ReadWriteMany
          annotations: {}
          existingClaim: ""
          size: 1Gi
          storageClass: standard
          subPath: ""
      redis:
        accessMode: ReadWriteMany
        annotations: {}
        existingClaim: ""
        size: 1Gi
        storageClass: standard
        subPath: ""
      registry:
        accessMode: ReadWriteMany
        annotations: {}
        existingClaim: ""
        size: 5Gi
        storageClass: standard
        subPath: ""
      trivy:
        accessMode: ReadWriteMany
        annotations: {}
        existingClaim: ""
        size: 5Gi
        storageClass: standard
        subPath: ""
    resourcePolicy: ""
  portal:
    affinity: {}
    automountServiceAccountToken: false
    extraEnvVars: []
    image:
      repository: goharbor/harbor-portal
      tag: v2.11.1
    initContainers: []
    nodeSelector: {}
    podAnnotations: {}
    podLabels: {}
    replicas: 1
    revisionHistoryLimit: 10
    serviceAccountName: ""
    serviceAnnotations: {}
    tolerations: []
    topologySpreadConstraints: []
  proxy:
    components:
    - core
    - jobservice
    - trivy
    noProxy: 127.0.0.1,localhost,.local,.internal
  redis:
    external:
      addr: 192.168.0.2:6379
      coreDatabaseIndex: "0"
      existingSecret: ""
      jobserviceDatabaseIndex: "1"
      password: ""
      registryDatabaseIndex: "2"
      sentinelMasterSet: ""
      trivyAdapterIndex: "5"
      username: ""
    internal:
      affinity: {}
      automountServiceAccountToken: false
      extraEnvVars: []
      image:
        repository: goharbor/redis-photon
        tag: v2.11.1
      initContainers: []
      jobserviceDatabaseIndex: "1"
      nodeSelector: {}
      registryDatabaseIndex: "2"
      serviceAccountName: ""
      tolerations: []
      trivyAdapterIndex: "5"
    podAnnotations: {}
    podLabels: {}
    type: internal
  registry:
    affinity: {}
    automountServiceAccountToken: false
    controller:
      extraEnvVars: []
      image:
        repository: goharbor/harbor-registryctl
        tag: v2.11.1
    credentials:
      existingSecret: ""
      htpasswdString: ""
      password: harbor_registry_password
      username: harbor_registry_user
    existingSecret: ""
    existingSecretKey: REGISTRY_HTTP_SECRET
    initContainers: []
    middleware:
      cloudFront:
        baseurl: example.cloudfront.net
        duration: 3000s
        ipfilteredby: none
        keypairid: KEYPAIRID
        privateKeySecret: my-secret
      enabled: false
      type: cloudFront
    nodeSelector: {}
    podAnnotations: {}
    podLabels: {}
    registry:
      extraEnvVars: []
      image:
        repository: goharbor/registry-photon
        tag: v2.11.1
    relativeurls: false
    replicas: 1
    revisionHistoryLimit: 10
    secret: ""
    serviceAccountName: ""
    tolerations: []
    topologySpreadConstraints: []
    upload_purging:
      age: 168h
      dryrun: false
      enabled: true
      interval: 24h
  secretKey: not-a-secure-key
  trace:
    enabled: false
    jaeger:
      endpoint: http://hostname:14268/api/traces
    otel:
      compression: false
      endpoint: hostname:4318
      insecure: true
      timeout: 10
      url_path: /v1/traces
    provider: jaeger
    sample_rate: 1
  trivy:
    affinity: {}
    automountServiceAccountToken: false
    debugMode: false
    enabled: true
    extraEnvVars: []
    gitHubToken: ""
    ignoreUnfixed: false
    image:
      repository: goharbor/trivy-adapter-photon
      tag: v2.11.1
    initContainers: []
    insecure: false
    nodeSelector: {}
    offlineScan: false
    podAnnotations: {}
    podLabels: {}
    replicas: 1
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 200m
        memory: 512Mi
    securityCheck: vuln
    serviceAccountName: ""
    severity: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
    skipJavaDBUpdate: false
    skipUpdate: false
    timeout: 5m0s
    tolerations: []
    topologySpreadConstraints: []
    vulnType: os,library
  updateStrategy:
    type: RollingUpdate
```
