### ISSUE TITLE
Ability to include secret instead of exposing raw password

### ISSUE THREAD

**Issue by panteparak** [goharbor/harbor-helm#1013]
Exposing database and redis secret via helm values files are very dangerous. It would be better to mount k8s secret.

Proposed change (example)

```
database:
  external:
    existingSecret: "SECRET-NAME"
    existingSecretPasswordKey: "SECRET-KEY"
```
