### ISSUE TITLE
Error with docker login, not sure how to properly configure harbor w/ ingress

### ISSUE THREAD

**Issue by mckernanin** [goharbor/harbor-helm#1041]
I just setup a new harbor instance with the helm chart, and I'm trying to auth with docker to be able to push images. 
I am using traefik with letsencrypt certificates in front of my cluster. I can log in to the web interface just fine, but running docker login fails. I have replaced my actual domain with `my.domain` in all examples below. I'm guessing that I just have things configured wrong, but It's not clear what the right config looks like.

Values I'm using:
```yaml
        expose:
          type: loadBalancer
          ingress:
            hosts:
              core: registry.my.domain
              notary: notary.my.domain
          tls:
            auto:
              commonName: registry.my.domain
        externalUrl: https://registry.my.domain
```

When trying to run `docker login`:
```
➜ docker login https://registry.my.domain
Username: admin
Password: 
Error response from daemon: Get "https://registry.my.domain/v2/": Get "https://core.harbor.domain/service/token?account=admin&client_id=docker&offline_token=true&service=harbor-registry": dial tcp: lookup core.harbor.domain: no such host
```

**Comment by dioguerra** [comment]
You need to use the token for login, not the PW

**Comment by mckernanin** [comment]
```
➜ docker -D login https://registry.my.domain
Username: robot$hel-test
Password:
Error response from daemon: Get "https://registry.my.domainv2/": Get "https://core.harbor.domain/service/token?account=robot%24hel-test&client_id=docker&offline_token=true&service=harbor-registry": dial tcp: lookup core.harbor.domain: no such host
```

Using a robot account I get the same issue. Looks like I need to override a domain setting somewhere.

**Comment by dioguerra** [comment]
I don't think your domain is being propagated correctly

**Comment by mckernanin** [comment]
Thanks, I agree. How do I fix it?

**Comment by ywk253100** [comment]
@mckernanin If you use ingress, the `expose.type` should be `ingress` rather than `loadBalancer`

**Comment by mckernanin** [comment]
Updated values to look like this:
```yaml
expose:
  type: ingress
  ingress:
    hosts:
      core: registry.my.domain
      notary: notary.my.domain
  tls:
    auto:
      commonName: registry.my.domain
externalUrl: https://registry.my.domain
```

I'm using traefik for an ingress in my cluster which uses `IngressRoutes`, the `Ingress` objects being added are just stuck progressing since my cluster doesn't know what to do with them:

![image](https://user-images.githubusercontent.com/6300047/131958428-b85274c1-eb05-4290-a52e-eae760953d89.png)
