### ISSUE TITLE
Harbor ingress and Notary ingress share the same TLS secret name

### ISSUE THREAD

**Issue by tomalexander** [goharbor/harbor-helm#1065]
Steps to reproduce:
1. git clone this repo
2.
```
$ helm template harbor . --dry-run | grep -A 1 "tls:"  
tls:
  - secretName: harbor-ingress
--
  tls:
  - secretName: harbor-ingress
  ```

Impact: Whichever ingress writes to that secret first wins, so right now my harbor.my.domain is serving a certificate for notary.harbor.my.domain

**Comment by tomalexander** [comment]
Looks like this bug was introduced in https://github.com/goharbor/harbor-helm/commit/c34ab1d336d3f5ff7edb51068381a0be63d2c8ad which means its been in every release of harbor-helm since 1.4.0

**Comment by jfmeachum** [comment]
@tomalexander I was able to fix this on my cluster that uses ingress-nginx and cert-manager.

It looks like Harbor tries to automatically create certificates by default, which were in conflict with ones that cert-manager was intended to provision.  Changing `expose.tls.certSource` to equal "secret" and then specifying `expose.tls.secret.secretName` and `expose.tls.secret.notarySecretName` resolved this issue for me.

```yaml
expose:
  type: ingress
  tls:
    certSource: "secret"
    enabled: true
    secret:
      secretName: "harbor-core-ingress-tls"
      notarySecretName: "harbor-notary-ingress-tls"
```
