### ISSUE TITLE
Helm behing proxy. again

### ISSUE THREAD

**Issue by anatoly-kryzhanovsky** [goharbor/harbor-helm#1098]
we use harbor for a several year. before we have harbor deployed with helm in k8s cluster with can be accessible directly
but there was some changes in infrastructure and now we have nginx proxy before k8s:

net -> nginx + ssl termination -> k8s -> ingress -> harbor

i can successful login to portal, manage them (create repository and so on), also i can login with `docker login`, but then i try to push image i receive following output:
```
819fc5ebc71c: Pushing [==================================================>]  3.072kB
9db2d85e46e5: Pushing [==================================================>]   2.56kB
ac9af79b2ae4: Pushing [==================================================>]  15.36kB
8de25bd1a8da: Pushing  3.584kB
41463f24d650: Pushing  2.048kB
e769b520dc65: Waiting
....
unknown blob
```

i found some related issues which notice about nginx configuration, but have no luck with them.

so my ngonx config is:
```
server {
  server_name registry.somedomain.com;

  location / {
    proxy_pass http://k8s; #k8s - is upstream 

    proxy_http_version 1.1;

    proxy_set_header Host $http_host;

    # also tried with and without following lines:
    # proxy_set_header X-Forwarded-Host $http_host; 
    # proxy_set_header X-Forwarded-Proto "https";
    # proxy_set_header X-Forwarded-For $remote_addr;
  }
}
```

my values.yaml:
```
expose:
  type: ingress
  tls:
    enabled: false
    certSource: auto
    auto:
      commonName: ""
    secret:
      secretName: ""
      notarySecretName: ""
  ingress:
    hosts:
      core: registry.somedomain.com
      notary: notary.somedomaind.com
    controller: default
    kubeVersionOverride: ""
    annotations:
      ingress.kubernetes.io/ssl-redirect: "true"
      ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      kubernetes.io/ingress.class: "nginx"

externalURL: https://registry.somedomain.com
internalTLS:
  enabled: false
```

i cannot find any error or warning in log files of harbor components or proxy logs - all response has 2XX codes. 
i also find some config variable as http.reletiveurl but cannot find it in values.yaml

so can anybody help me with right configuration?  i think that it is very common setup then we have ssl termination on proxy and then by pass just plain http to harbor and thats will be perfect if such information can be found in documentation
