### ISSUE TITLE
Helm update mangles TLS secret

### ISSUE THREAD

**Issue by withinboredom** [goharbor/harbor-helm#1114]
Expected: 
To redeploy with helm and the TLS secret to be reused.

Actual:
Redeploy with helm values changed and TLS secret is overridden with generic certificate from Harbor.

This is especially bad because systems like letsencrypt have rate limits, which effectively limits the number of times per week this can be updated.

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

1. Deploy harbor via helm
2. Get a certificate via cert-manager
2. Update the values (ex: increase number of replicas)
3. Update via helm
4. TLS secret gets overridden with cert issued by `harbor-ca`

**Comment by ninjadq** [comment]
if you use cert-manager, you can use cert-manager to manage the certs, and refer it on `value.yml`

**Comment by adippl** [comment]
I had exactly the same problem. Configuration isn't obvious and default values don't work with ingress and cert-manager.
Please consider changing it or provide example in the documentation.

Here is my command I use for installation/upgrades/
`helm upgrade --install --repo https://helm.goharbor.io --create-namespace --namespace harbor test-instance harbor --version 1.13.0 --values values.yaml`

and values file
```
expose:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    controller: my-ingress
    className: my-ingress
    hosts:
      core: harbor.k8s2.MY.DOMAIN
      notary: notary.harbor.k8s2.MY.DOMAIN
  tls:
    enabled: true
    certSource: secret
    secret:
      secretName: harbor-tls-cert
externalURL: https://harbor.k8s2.MY.DOMAIN
harborAdminPassword: XrCHzUC1DDxiWUdnhs21qlgOG
persistence:
  persistentVolumeClaim:
    registry:
      size: 50Gi
```
