### ISSUE TITLE
Add custom annotations feature for all component's PVCs

### ISSUE THREAD

**Issue by tanuj-soni2** [goharbor/harbor-helm#1121]
Could we add custom annotation feature for all PVCs?

like this, we can mention it through `values.yaml`

```
   persistence:
      annotations: {}
```

we are expecting to add our annotations like mentioned below from `values.yaml`

```
   persistence:
      annotations:
         component: 'registry'
         app: 'harbor'   
```

Example mapping for `values.yaml`

`persistence.persistentVolumeClaim.registry.annotations`
