### ISSUE TITLE
ServiceMonitor manifests are not getting created

### ISSUE THREAD

**Issue by gouravsw** [goharbor/harbor-helm#1127]
I am able to deploy the Harbor in K8S cluster. Harbor is up and running without any issues. I am using the latest release

https://github.com/goharbor/harbor-helm/releases/tag/v1.8.1

Harbor OSS version: v2.4.1

For monitoring purpose via Prometheus, I am planning to enable the metrics and it's subfield servicemonitor to true. So that servicemonitor manifests will be created. But somehow these ServiceMonitor manifests are not getting created. While checking the templates for metrcis. It is passing all the checks

`{{- if and ( .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" ) .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}`

As per expression` metrics.enabled` is `true` as well as `metrics.serviceMonitor.enabled` is `true`. And this check (`.Capabilities.APIVersions.Has "monitoring.coreos.com/v1"`) has the requested `api-version`  

```
k api-versions  |grep coreos
monitoring.coreos.com/v1
monitoring.coreos.com/v1alpha1
```

Could someone provide the insight why the ServiceMonitor manifests are not generating? What mistake I am making in values.yaml file?

```
metrics:
  enabled: true
  core:
    path: /metrics
    port: 8001
  registry:
    path: /metrics
    port: 8001
  jobservice:
    path: /metrics
    port: 8001
  exporter:
    path: /metrics
    port: 8001
  serviceMonitor:
    enabled: true
    additionalLabels: {}
    interval: "15"
    metricRelabelings: 
      # - action: keep
      #   regex: 'kube_(daemonset|deployment|pod|namespace|node|statefulset).+'
      #   sourceLabels: [__name__]
    relabelings: 
      # - sourceLabels: [__meta_kubernetes_pod_node_name]
      #   separator: ;
      #   regex: ^(.*)$
      #   targetLabel: nodename
      #   replacement: $1
      #   action: replace
```

**Comment by zyyw** [comment]
As this comment mentioned 
```
https://github.com/goharbor/harbor-helm/blob/a57ee9e7672e03f3c605661109c5291c3819b511/values.yaml#L835
```
you should probably install prometheus-operator first.

**Comment by gouravsw** [comment]
@zyyw Prometheus operator was deployed prior to harbor.

**Comment by timbrown5** [comment]
I'm seeing this behaviour too:

```
kubectl api-versions | grep monitoring.coreos.com/v1
monitoring.coreos.com/v1
monitoring.coreos.com/v1alpha1
```

values.yaml:
```
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
```

In my case I am using customize to deploy the helm charts:
```
helmCharts:
  - name: harbor
    version: 1.9.2
    repo: https://helm.goharbor.io
    releaseName: deployment-harbor
    namespace: harbor
    valuesFile: values.yaml
```

```
helmCharts:
  - name: kube-prometheus-stack              
    version: 36.6.2
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: deployment-monitoring
    namespace: monitoring
    includeCRDs: false # Run install-crds.sh instead 
    valuesFile: values.yaml
```

I deployed the Prometheus helm chart after harbor, but the template should be yaml should get regenerated and reapplied each time and I get no Harbor ServiceMonitor listed in the latest yaml that kustomize generates.
