### ISSUE TITLE
postgresql can't start

### ISSUE THREAD

**Issue by 943692923** [goharbor/harbor-helm#1128]
database container run to Error due to permissions
solution: change templates/database/database-ss.yaml

```
      initContainers:
      # as we change the data directory to a sub folder to support psp, the init container here
      # is used to migrate the existing data. See https://github.com/goharbor/harbor-helm/issues/756
      # for more detail.
      # we may remove it after several releases
      - name: "data-migrator"
        image: {{ .Values.database.internal.image.repository }}:{{ .Values.database.internal.image.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        command: ["/bin/sh"]
        args: ["-c", "[ ! -d /opt/data/pgdata ] && mkdir -m 0700 /opt/data/pgdata &&  chown -R 999:999 /opt/data/pgdata || true"]
        volumeMounts:
          - name: database-data
            mountPath: /opt/data
            subPath: {{ $database.subPath }}
```
