### ISSUE TITLE
Pulling and pushing containers is very slow

### ISSUE THREAD

**Issue by tgeci** [goharbor/harbor-helm#1130]
Hi guys!
We use Harbor and have deployed it via Helm in Kubernetes. After gradually integrating it into our development processes, we found out that the process of uploading and pulling containers is very slow.
 
With very slow I mean that pulling a container for Keycloak for example took more than 10 Minutes where all layers together have 745.6MB. While pulling the same image (quay.io/keycloak/keycloak:15.1.0) directly from upstream registry takes 15 Seconds.

I have already tried to tweak some things like pulling up the replicas on the harbor core or increasing the memory and CPU resources for that. The network can be ruled out with a very high probability because the instance is running in a self-hosted kubernetes cluster in a datacenter with extremely high internet connectivity (more than 1TBit up/down). 
Even downloading the images on the Kubernetes nodes takes extremely long time and they are connected via 10G.

Here the relevant values.yaml:
```
core:
  replicas: 2
  resources:
    requests:
      memory: 1024Mi
      cpu: 500m

registry:
  registry:
    resources:
     requests:
      memory: 512Mi
```

Any ideas or hints ?
