### ISSUE TITLE
Deploy harbor with helm in k8s,there is 404 not Found error in nginx,when i visit harbor interface.

### ISSUE THREAD

**Issue by neblen** [goharbor/harbor-helm#1155]
404 Not Found appears in harbor website.I deploy harbor with helm in k8s.What can I do for solving this problem？
I install nginx-controller.Nginx controller logs as follows. 
```
I0308 02:19:35.559655 7 event.go:282] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"harbor-test", Name:"harbor-test-harbor-ingress", UID:"xxxxxxx-xxxx-xxxx-xxxx-36afc5be2ef9", APIVersion:"networking.k8s.io/v1beta1", ResourceVersion:"167834", FieldPath:""}): type: 'Normal' reason: 'Sync' Scheduled for sync
I0308 02:19:35.588573 7 event.go:282] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"harbor-test", Name:"harbor-test-harbor-ingress", UID:"xxxxxxx-xxxxx-xxxx-xxxx-36afc5be2ef9", APIVersion:"networking.k8s.io/v1beta1", ResourceVersion:"167837", FieldPath:""}): type: 'Normal' reason: 'Sync' Scheduled for sync
W0308 02:19:38.139160 7 controller.go:992] Service "harbor-test/harbor-test-harbor-core" does not have any active Endpoint
```

**Comment by neblen** [comment]
harbor cluster service is as follows.
```
[root@rancher-node-1 ingress-test]# kubectl get svc -n harbor
NAME                          TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
harbor-harbor-chartmuseum     ClusterIP   xx.xx.xx.xxx    <none>        80/TCP              152m
harbor-harbor-clair           ClusterIP   xx.xx.xx.xx    <none>        8080/TCP            152m
harbor-harbor-core            ClusterIP   xx.xx.xx.xx    <none>        80/TCP              152m
harbor-harbor-database        ClusterIP   xx.xx.xx.xx     <none>        5432/TCP            152m
harbor-harbor-jobservice      ClusterIP   xx.xx.xx.xx    <none>        80/TCP              152m
harbor-harbor-notary-server   ClusterIP   xx.xx.xx.xx   <none>        4443/TCP            152m
harbor-harbor-notary-signer   ClusterIP   xx.xx.xx.xx    <none>        7899/TCP            152m
harbor-harbor-portal          ClusterIP   xx.xx.xx.xx    <none>        80/TCP              152m
harbor-harbor-redis           ClusterIP   xx.xx.xx.xx      <none>        6379/TCP            152m
harbor-harbor-registry        ClusterIP   xx.xx.xx.xx  <none>        5000/TCP,8080/TCP   152m
```
 harbor cluster ingress is as follows
```
[root@rancher-node-1 ingress-test]# kubectl get ingress -n harbor
NAME                    CLASS    HOSTS                                     ADDRESS                     PORTS     AGE
harbor-harbor-ingress   <none>   core.harbor.domain,notary.harbor.domain    xx.xx.xx.xx, xx.xx.xx.xx   80, 443   156m
```

**Comment by zyyw** [comment]
hi @neblen do you have your nginx ingress setup properly?
from the logs, it seems not:
```
Service "harbor-test/harbor-test-harbor-core" does not have any active Endpoint
```

**Comment by neblen** [comment]
> hi @neblen do you have your nginx ingress setup properly? from the logs, it seems not:
> 
> ```
> Service "harbor-test/harbor-test-harbor-core" does not have any active Endpoint
> ```

Thank you for your reploy.
The values.yaml is as follows. I just use the helm command which means that "helm install harbor ./harbor -n harbor". 
```
expose:
  # Set the way how to expose the service. Set the type as "ingress",
  # "clusterIP", "nodePort" or "loadBalancer" and fill the information
  # in the corresponding section
  type: ingress
  tls:
    # Enable the tls or not. Note: if the type is "ingress" and the tls
    # is disabled, the port must be included in the command when pull/push
    # images. Refer to https://github.com/goharbor/harbor/issues/5291
    # for the detail.
    enabled: true
    # Fill the name of secret if you want to use your own TLS certificate.
    # The secret contains keys named:
    # "tls.crt" - the certificate (required)
    # "tls.key" - the private key (required)
    # "ca.crt" - the certificate of CA (optional), this enables the download
    # link on portal to download the certificate of CA
    # These files will be generated automatically if the "secretName" is not set
    secretName: ""
    # By default, the Notary service will use the same cert and key as
    # described above. Fill the name
```

**Comment by neblen** [comment]
The ingress info is as follows.
```
[user@rancher-node-1 ~]# kubectl get ingress -n harbor
NAME                    CLASS    HOSTS                                     ADDRESS                     PORTS     AGE
harbor-harbor-ingress   <none>   core.harbor.domain,notary.harbor.domain   xx.xx.xx.xx.186,xx.xx.xx.187   80, 443   45h
[user@rancher-node-1 ~]#
```

**Comment by zyyw** [comment]
from the log 
```
I0308 02:19:35.559655 7 event.go:282] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"harbor-test", Name:"harbor-test-harbor-ingress", UID:"xxxxxxx-xxxx-xxxx-xxxx-36afc5be2ef9", APIVersion:"networking.k8s.io/v1beta1", ResourceVersion:"167834", FieldPath:""}): type: 'Normal' reason: 'Sync' Scheduled for sync
```
the ingress is under Namespace:"harbor-test", why do you `kubectl get ingress -n harbor`?
Is it possible that the namespace mismatch?

**Comment by neblen** [comment]
@zyyw  Sorry, i try two times，the first time is in harbor namespace,the second time is in harbor-test namespace.The error logs are same in the two namespaces.

**Comment by neblen** [comment]
Finally, I find that  deploy the cluster in ingress mode, I  must have a domain name to access the harbor.I have configured domain name resolution.It works correctly. @zyyw Thank you for your help.

**Comment by vennemp** [comment]
i'm running into this exact same issue right now just deploying in a dev env.  

I'm using latest helm and harbor charts. 
<img width="967" alt="Screen Shot 2022-04-18 at 7 14 25 PM" src="https://user-images.githubusercontent.com/26049891/163891539-1a9e1810-e632-4899-aab7-04d47b22676d.png">

I have updated dns to point to my load balancer.

```yaml
Name:             harbor-ingress
Labels:           app=harbor
                  app.kubernetes.io/managed-by=Helm
                  chart=harbor
                  heritage=Helm
                  release=harbor
Namespace:        default
Address:          
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
TLS:
  harbor-ingress terminates harbor-core.mydomain.com
Rules:
  Host                         Path  Backends
  ----                         ----  --------
  harbor-core.mydomain.com  
                               /api/         harbor-core:80 (192.168.31.201:8080)
                               /service/     harbor-core:80 (192.168.31.201:8080)
                               /v2           harbor-core:80 (192.168.31.201:8080)
                               /chartrepo/   harbor-core:80 (192.168.31.201:8080)
                               /c/           harbor-core:80 (192.168.31.201:8080)
                               /             harbor-portal:80 (192.168.45.137:8080)
Annotations:                   ingress.kubernetes.io/proxy-body-size: 0
                               ingress.kubernetes.io/ssl-redirect: true
                               meta.helm.sh/release-name: harbor
                               meta.helm.sh/release-namespace: default
                               nginx.ingress.kubernetes.io/proxy-body-size: 0
                               nginx.ingress.kubernetes.io/ssl-redirect: true
Events:                        <none>


Name:             harbor-ingress-notary
Labels:           app=harbor
                  app.kubernetes.io/managed-by=Helm
                  chart=harbor
                  heritage=Helm
                  release=harbor
Namespace:        default
Address:          
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
TLS:
  harbor-ingress terminates harbor-notary.mydomain.com
Rules:
  Host                           Path  Backends
  ----                           ----  --------
  harbor-notary.mydomain.com  
                                 /   harbor-notary-server:4443 (192.168.28.72:4443)
Annotations:                     ingress.kubernetes.io/proxy-body-size: 0
                                 ingress.kubernetes.io/ssl-redirect: true
                                 meta.helm.sh/release-name: harbor
                                 meta.helm.sh/release-namespace: default
                                 nginx.ingress.kubernetes.io/proxy-body-size: 0
                                 nginx.ingress.kubernetes.io/ssl-redirect: true
Events:                          <none>
 ```
