### ISSUE TITLE
Content trust with docker client return 401

### ISSUE THREAD

**Issue by MenahStreetBand** [goharbor/harbor-helm#1162]
I'm using: 
Istio: 1.11.4
Harbor: v2.4.1 with helm and this configuration:

```yaml
expose:
  type: clusterIP
   tls:
    enabled: false
externalURL: https://registry1.example.com
internalTLS:
  enabled: false
persistence:
  enabled: true
imagePullPolicy: IfNotPresent
updateStrategy:
  type: Recreate
nginx:
  replicas: 0
```
all another configuration is default.

When I use:
```
export DOCKER_CONTENT_TRUST=1
export DOCKER_CONTENT_TRUST_SERVER=https://registry1.example.com
```
The push return error 401 and this is the logs

```
docker --debug push registry1.example.com/library/k3s
Using default tag: latest
The push refers to repository [registry1.example.com/library/k3s]
cff3ade2eedd: Layer already exists 
974fdc595a78: Layer already exists 
d976696f96c7: Layer already exists 
latest: digest: sha256:e61e12f31cee09691ef33246ef482884aca02324759569bb6b4ce1c9bb1f60db size: 942
Signing and pushing trust metadata
DEBU[0001] reading certificate directory: /Users/myuser/.docker/tls/registry1.example.com 
DEBU[0001] No yubikey found, using alternative key storage: no library found 
DEBU[0001] Making dir path: /Users/myuser/.docker/trust/tuf/registry1.example.com/library/k3s/changelist 
DEBU[0002] received HTTP status 401 when requesting root. 
you are not authorized to perform this operation: server returned 401.
```
The logs from harbor-notary-server pod:
`
{"go.version":"go1.14.15","http.request.host":"harbor-notary-server:4443","http.request.id":"36846764-ee59-4a15-a2af-7173efef0ad2","http.request.method":"GET","http.request.remoteaddr":"100.1.1.2:51404","http.request.uri":"/v2/registry1.example.com/library/k3s/_trust/tuf/root.json","http.request.useragent":"Go-http-client/1.1","level":"info","msg":"404 GET root role","registry1.example.com":"gun","time":"2022-03-17T14:39:11Z"}
`

`
{"go.version":"go1.14.15","http.request.host":"harbor-notary-server:4443","http.request.id":"36846764-ee59-4a15-a2af-7173efef0ad2","http.request.method":"GET","http.request.remoteaddr":"100.1.1.2:51404","http.request.uri":"/v2/registry1.example.com/library/k3s/_trust/tuf/root.json","http.request.useragent":"Go-http-client/1.1","level":"info","msg":"metadata not found: You have requested metadata that does not exist.: No record found","time":"2022-03-17T14:39:11Z"}
`

`
{"go.version":"go1.14.15","http.request.host":"harbor-notary-server:4443","http.request.id":"36846764-ee59-4a15-a2af-7173efef0ad2","http.request.method":"GET","http.request.remoteaddr":"100.1.1.2:51404","http.request.uri":"/v2/registry1.example.com/library/k3s/_trust/tuf/root.json","http.request.useragent":"Go-http-client/1.1","http.response.contenttype":"application/json; charset=utf-8","http.response.duration":"1.070316ms","http.response.status":404,"http.response.written":116,"level":"info","msg":"response completed","time":"2022-03-17T14:39:11Z"}
`
This is my Istio Gateway and Virtual Service
```yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: harbor-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway 
  servers:
    - hosts:
        - 'registry1.example.com'
      port:
        name: http
        number: 443
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: gateway-certs
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: harbor
  namespace: harbor-system
spec:
  gateways:
    - istio-system/harbor-gateway
    - mesh
  hosts:
    - registry1.example.com
  http:
    - name: 'registry'
      match:
        - port: 5000
      route:
        - destination:
            host: harbor-registry.harbor-system.svc.cluster.local
            port:
              number: 5000   
    - name: 'core'
      match:
        - uri:
            prefix: '/api/'
        - uri:
            prefix: '/service/'
        - uri:
            prefix: '/v2/'
        - uri:
            prefix: '/chartrepo/'
        - uri:
            prefix: '/c/'
      route:
        - destination:
            host: harbor-core.harbor-system.svc.cluster.local
            port:
              number: 80
    - name: 'portal'
      route:
        - destination:
            host: harbor-portal.harbor-system.svc.cluster.local
            port:
              number: 80
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: harbor-registry
  namespace: harbor-system
spec:
  hosts:
    - registry1.example.com
    - harbor-core
  ports:
    - number: 5000
      name: http-registry
  location: MESH_INTERNAL
  resolution: NONE

```

Without `DOCKER_CONTENT_TRUST` the image is pushed in the repository, but no signed.
