### ISSUE TITLE
Ingress: list of hosts and path-configuration

### ISSUE THREAD

**Issue by boehb-efs** [goharbor/harbor-helm#1169]
Hi,
nice project, we would like to use in our platform to enable users to define custom workflows to use in argo :-)

However, currently I do not see a possibility to generate an ingress with multiple hosts and configuration of path. To clarify, we want to achieve the following:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: harbor-ingress
  annotations:
    ...
spec:
  rules:
  - host: $(host1)
    http:
      paths:
      - path: /harbor/
        pathType: Prefix
        backend:
          service:
            name: harbor-portal
            port:
              number: 80
      - path: /harbor/api/
        pathType: Prefix
        backend:
          service:
            name: harbor-core
            port:
              number: 80
	...
  - host: $(host2)
    http:
      paths:
      - path: /harbor/
        pathType: Prefix
        backend:
          service:
            name: harbor-portal
            port:
              number: 80
      - path: /harbor/api/
        pathType: Prefix
        backend:
          service:
            name: harbor-core
            port:
              number: 80
	...
```

Please enable this? Same with notary...
