### ISSUE TITLE
Proposal to Generate a Changelog

### ISSUE THREAD

**Issue by Vad1mo** [goharbor/harbor-helm#1177]
When new Helm charts are released, it is difficult to see what has changed and what impacts  it has on the upgrade and deployment. 

One easy way to publish a Changelog can be done with artifacthub.io. Project Harbor is already listed https://artifacthub.io/packages/helm/harbor/harbor

The only thing needed is to add annotations to `Chart.yaml`

```yaml
Artifact Hub annotations in Chart.yaml:

annotations:
  artifacthub.io/changes: |
    - Added cool feature
    - Fixed minor bug    
```
See full example: https://artifacthub.io/docs/topics/annotations/helm/
and code https://github.com/artifacthub/hub/blob/master/charts/artifact-hub/Chart.yaml

The result will be displayed by artifacthub like this:

<img width="1218" alt="image" src="https://user-images.githubusercontent.com/1492007/163173150-6ee22f91-fbe5-4ffc-b60e-19450f8c9bb3.png">

It is also possible to reference directly to the Changelog from the git repo or download the markdown version containing the full change log.
