### ISSUE TITLE
Harbor-core unable to access /service/token when hard-coding auto-generated values

### ISSUE THREAD

**Issue by ProNibs** [goharbor/harbor-helm#1240]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**

Installed Harbor Helm chart as expected. I am using a GitOps system called kapp-controller (similar to ArgoCD/Flux). I was having issues where pods would rotate each time the helmTemplate command was ran by kapp-controller, so I went through the chart to explicitly define all the auto-generated fields as seen below. 
After doing so, my GitOps system wasn't rotating passwords anymore, but then I was unable to push images to the registry through my ingress. Port-forward of the registry pods+svc worked fine. Going through the logs in harbor-core, would get a `unable to handle service: `

So either I have something mis-configured and the chart should not allow that, or there is a bug.

**Steps to reproduce the problem:**

I had the following values set on my helm install, where `harbor-tls-secret` is a cert-manager created secret with a self-signed CA issuer. The following values are not the ones actually used by the Harbor in my URL.

```yaml
        externalURL: "https://andrew-harbor.tanzuplatform.com"
        harborAdminPassword: Harbor123456
        caSecretName: harbor-tls-secret
        caBundleSecretName: harbor-tls-secret
        logLevel: debug
        expose:
            ingress:
                hosts:
                    core: andrew-harbor.tanzuplatform.com      
                    notary: andrew-notary.tanzuplatform.com  
            tls:
                certSource: secret
                secret:
                    secretName: harbor-tls-secret
                    notarySecretName: harbor-tls-secret
        core:
            secret: w5dlTF1qrIKvfmuJ
            xsrfKey: VvFTijscqmVOM0fz7qhoLWvu12YRYCKY
            secretName: harbor-tls-secret
        registry:
            secret: PuzrqhB0zbPW17ut
            credentials:
                # This was generated via `openssl passwd -apr1 harbor-registry-password`
                htpasswdString: "$apr1$g4cGfexj$My3rncqfvMiKhzF6JJx090"
        notary:
            secretName: harbor-tls-secret
        jobservice:
            secret: IxKVXjB46tMjPP0p
```

**Versions:**
Please specify the versions of following systems.

- helm version: v3.9.0
- harbor chart version: 1.9.2
