### ISSUE TITLE
Fix doc - values.yaml - coreDatabaseIndex can be set to value different from 0

### ISSUE THREAD

**Issue by RichardSufliarsky** [goharbor/harbor-helm#1243]
I propose to remove these two lines as it works also with different database index number. https://github.com/goharbor/harbor-helm/blob/db5a241068a13b23201b61a25685c73fd8fe4147/values.yaml#L826 https://github.com/goharbor/harbor-helm/blob/db5a241068a13b23201b61a25685c73fd8fe4147/values.yaml#L827 

I deployed helm chart v1.9.3 with this config:
```
redis:
  type: external
  external:
    addr: "redis-sentinels-node-0.redis-sentinels-headless.redis-sentinels.svc.cluster.local:26379,redis-sentinels-node-1.redis-sentinels-headless.redis-sentinels.svc.cluster.local:26379,redis-sentinels-node-2.redis-sentinels-headless.redis-sentinels.svc.cluster.local:26379"
    sentinelMasterSet: "k8s123"
    coreDatabaseIndex: "10"
    jobserviceDatabaseIndex: "11"
    registryDatabaseIndex: "12"
    chartmuseumDatabaseIndex: "13"
    trivyAdapterIndex: "14"
    password: "pass.WORD"
```

It works and I can see keys created in the database index 10:
```
1001@redis-sentinels-node-1:/$ redis-cli
127.0.0.1:6379> auth pass.WORD
OK
127.0.0.1:6379> select 10
OK
127.0.0.1:6379[10]> dbsize
(integer) 968
127.0.0.1:6379[10]> dump "cache:manifestlist:quay.io/prometheus/node-exporter:sha256:f2269e73124dd0f60a7d19a2ce1264d33d08a985aed0ee6b0b89d0be470592cd:contenttype"
"\x00;\xd99application/vnd.docker.distribution.manifest.list.v2+json\n\x00\x8f\xe9\xa1\t\xea\xa2\x16;"
```
Can someone else confirm it works with external Redis? I am happy to create PR then.
