### ISSUE TITLE
Using same PVC and different subPath in components got permission problems

### ISSUE THREAD

**Issue by wyttime04** [goharbor/harbor-helm#1284]
If I use same PVC share with other components will cause database permission denied
- database Log
  ```
  ls: cannot access '/var/lib/postgresql/data/pgdata': No such file or directory
  The files belonging to this database system will be owned by user "postgres".
  This user must also own the server process.
  The database cluster will be initialized with locales
    COLLATE:  en_US.UTF-8
    CTYPE:    en_US.UTF-8
    MESSAGES: C
    MONETARY: C
    NUMERIC:  C
    TIME:     C
  The default text search configuration will be set to "english".
  Data page checksums are disabled.
  initdb: error: could not create directory "/var/lib/postgresql/data/pgdata": Permission denied
  creating directory /var/lib/postgresql/data/pgdata/pg13 ... 
  ```

These are my setting files
- PV & PVC
  ```yaml
  apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: local-pv-harbor
  spec:
    storageClassName: local-harbor
    capacity:
      storage: 5Gi
    accessModes:
      - ReadWriteOnce
    local:
      path: /var/lib/harbor/1
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - node1
  ---
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: local-pvc-harbor
    namespace: harbor
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi 
    storageClassName: local-harbor
  ---
  ```
- values file persistence part
  ```yaml
  persistence:
    enabled: true
    # Setting it to "keep" to avoid removing PVCs during a helm delete
    # operation. Leaving it empty will delete PVCs after the chart deleted
    # (this does not apply for PVCs that are created for internal database
    # and redis components, i.e. they are never deleted automatically)
    resourcePolicy: "keep"
    persistentVolumeClaim:
      registry:
        # Use the existing PVC which must be created manually before bound,
        # and specify the "subPath" if the PVC is shared with other components
        existingClaim: "local-pvc-harbor"
        # Specify the "storageClass" used to provision the volume. Or the default
        # StorageClass will be used (the default).
        # Set it to "-" to disable dynamic provisioning
        storageClass: "-"
        subPath: "registry"
        accessMode: ReadWriteOnce
        size: 5Gi
        annotations: {}
      chartmuseum:
        existingClaim: "local-pvc-harbor"
        storageClass: "-"
        subPath: "chartmuseum"
        accessMode: ReadWriteOnce
        size: 5Gi
        annotations: {}
      jobservice:
        existingClaim: "local-pvc-harbor"
        storageClass: "-"
        subPath: "jobservice"
        accessMode: ReadWriteOnce
        size: 1Gi
        annotations: {}
      # If external database is used, the following settings for database will
      # be ignored
      database:
        existingClaim: "local-pvc-harbor"
        storageClass: "-"
        subPath: "database"
        accessMode: ReadWriteOnce
        size: 1Gi
        annotations: {}
      # If external Redis is used, the following settings for Redis will
      # be ignored
      redis:
        existingClaim: "local-pvc-harbor"
        storageClass: "-"
        subPath: "redis"
        accessMode: ReadWriteOnce
        size: 1Gi
        annotations: {}
      trivy:
        existingClaim: "local-pvc-harbor"
        storageClass: "-"
        subPath: "trivy"
        accessMode: ReadWriteOnce
        size: 5Gi
        annotations: {}
  ```

It will end up with folder gid 10000 like this
<img width="421" alt="screenshoot1" src="https://user-images.githubusercontent.com/52523342/188296321-96bb5fba-ce19-4e2c-876a-1a0d18024fd0.png">

---
If I use **different PVC** in every components will see the folder gid changing in detail. (database and redis using different with others)
<img width="487" alt="screenshoot2" src="https://user-images.githubusercontent.com/52523342/188296387-3458ae4f-f413-48cc-b23a-16762068a4fe.png">

In my opinion, it's very useful if **docs or values file add warning/notice about gid problems**

---
btw, these my solution: Let database and redis use db PVC and others use component PVC
<details>
  <summary>setting files</summary>

  - PV & PVC: (create 2 PVC)
    ```yaml
    apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: local-pv-harbor-db
    spec:
      storageClassName: local-harbor
      capacity:
        storage: 5Gi
      accessModes:
        - ReadWriteOnce
      local:
        path: /var/lib/harbor/db
      nodeAffinity:
        required:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - node1
    ---
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: local-pvc-harbor-db
      namespace: harbor
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi 
      storageClassName: local-harbor
    ---
    
    apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: local-pv-harbor-component
    spec:
      storageClassName: local-harbor
      capacity:
        storage: 5Gi
      accessModes:
        - ReadWriteOnce
      local:
        path: /var/lib/harbor/component
      nodeAffinity:
        required:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - node1
    ---
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: local-pvc-harbor-component
      namespace: harbor
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi 
      storageClassName: local-harbor
    ---
    ```
  
  - values file persistence part: (Let database and redis use db PVC and others use component PVC)
    ```yaml
    persistence:
      enabled: true
      resourcePolicy: "keep"
      persistentVolumeClaim:
        registry:
          existingClaim: "local-pvc-harbor-component"
          storageClass: "-"
          subPath: "registry"
          accessMode: ReadWriteOnce
          size: 5Gi
          annotations: {}
        chartmuseum:
          existingClaim: "local-pvc-harbor-component"
          storageClass: "-"
          subPath: "chartmuseum"
          accessMode: ReadWriteOnce
          size: 5Gi
          annotations: {}
        jobservice:
          existingClaim: "local-pvc-harbor-component"
          storageClass: "-"
          subPath: "jobservice"
          accessMode: ReadWriteOnce
          size: 1Gi
          annotations: {}
        database:
          existingClaim: "local-pvc-harbor-db"
          storageClass: "-"
          subPath: "database"
          accessMode: ReadWriteOnce
          size: 1Gi
          annotations: {}
        redis:
          existingClaim: "local-pvc-harbor-db"
          storageClass: "-"
          subPath: "redis"
          accessMode: ReadWriteOnce
          size: 1Gi
          annotations: {}
        trivy:
          existingClaim: "local-pvc-harbor-component"
          storageClass: "-"
          subPath: "trivy"
          accessMode: ReadWriteOnce
          size: 5Gi
          annotations: {}
    ```
</details>

and folder gid will be
<img width="463" alt="screenshot3" src="https://user-images.githubusercontent.com/52523342/188296720-4b11853a-a37c-4d3a-9f16-7c185799ccdc.png">
