### ISSUE TITLE
registry-htpasswd existing secret

### ISSUE THREAD

**Issue by cbelloc** [goharbor/harbor-helm#1292]
Hello,

There seems to be an error on the deployment of `harbor-registry` when mounting the secret `registry-htpassword`

`k describe pod harbor-registry-78d94cb998-77fks`

```
Volumes:
  registry-htpasswd:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  .Values.registry.credentials.existingSecret ## Here
    Optional:    false
```
I feel like it's just missing the double brackets here : 
https://github.com/goharbor/harbor-helm/blob/master/templates/registry/registry-dpl.yaml (line 243)

```
      volumes:
      - name: registry-htpasswd
        secret:
          {{- if not .Values.registry.credentials.existingSecret }}
          secretName: {{ template "harbor.registry" . }}-htpasswd
          {{ else }}
          secretName: .Values.registry.credentials.existingSecret ## Here
          {{- end }}
          items:
            - key: REGISTRY_HTPASSWD
              path: passwd
```
suggested fix:

```
      volumes:
      - name: registry-htpasswd
        secret:
          {{- if not .Values.registry.credentials.existingSecret }}
          secretName: {{ template "harbor.registry" . }}-htpasswd
          {{ else }}
          secretName: {{ .Values.registry.credentials.existingSecret }}
          {{- end }}
          items:
            - key: REGISTRY_HTPASSWD
              path: passwd
```
