### ISSUE TITLE
Harbor pushed images not showing in the ui

### ISSUE THREAD

**Issue by githanium** [goharbor/harbor-helm#1295]
Hi all,

First of all I am aware this is an old already discussed issue. I followed any advice left in the following issues comments but I am still not able to display docker images in my Harbor portal using the Istio ingress controller

#1295 https://github.com/goharbor/harbor/issues/11906
#12804 https://github.com/goharbor/harbor/issues/12804
#539
#11906 https://github.com/goharbor/harbor/issues/11906

I am installing the latest version of Harbor with the provided helm-chart using the command below. The service is deployed in AWS EKS using an AWS nlb and Istio Gateway

### Chart Install

```
helm install --wait harbor --namespace ops harbor/harbor \
  --set expose.type=clusterIP \
  --set expose.tls.enabled=true \
  --set externalURL=https://harbor.hostname.co.uk \
  --set internalTLS.enabled=false \
  --set persistence.enabled=false \
  --set harborAdminPassword=bitnami \
  --set registry.relativeurls=false \
  --set registry.credentials.username=test \
  --set registry.credentials.password=test \
  --set redis.type=internal \
  --set expose.tls.secretName=harbor-tls-secret \
  --set expose.tls.auto.commonName=harbor.hostname.co.uk
```

The Istio configuration is as follow. The ingress gateway is installed in the istio-system namespace together with a public Gateway which intercept any request to the cluster and forward it to all other Virtual Services

### Gateway
```
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  annotations:
    istio-type: internal
  name: public-gateway
  namespace: istio-system
spec:
  selector:
    istio: gateway
  servers:
   - port:
       number: 80
       name: http
       protocol: HTTP
     hosts:
     - "*"
     tls:
       httpsRedirect: true 
   - port:
       number: 443
       name: https
       protocol: HTTPS   
     hosts:
     - "*"
     tls:
       mode: SIMPLE
       credentialName: gateway-tls-secret
```

### Virtual Service
```
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: harbor
spec:
  gateways:
    - istio-system/public-gateway
    - mesh
  hosts:
    - harbor.hostname.co.uk
  http:
    - match:
        - uri:
            prefix: '/c/'
      route:
        - destination:
            host: harbor-core
    - match:
        - uri:
            prefix: '/api/'
      route:
        - destination:
            host: harbor-core
    - match:
        - uri:
            prefix: '/v2/'
      route:
        - destination:
            host: harbor-registry
            port:
              number: 5000
    - match:
        - uri:
            prefix: '/v1/'
      route:
        - destination:
            host: harbor-registry
            port:
              number: 5000
      fault:
        abort:
          httpStatus: 404
    - match:
        - uri:
            prefix: '/service/'
      route:
        - destination:
            host: harbor-core
    - match:
        - uri:
            prefix: '/chartrepo/'
      route:
        - destination:
            host: harbor-core
    - route:
        - destination:
            host: harbor-portal
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: harbor-core
spec:
  hosts:
    - harbor-core
    - harbor-core.harbor.svc.cluster.local
  http:
    - match:
        - uri:
            prefix: '/v2/'
      route:
        - destination:
            host: harbor-registry
            port:
              number: 5000
    - route:
        - destination:
            host: harbor-core     
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: harbor-registry
spec:
  hosts:
  - harbor.hostname.co.uk
  ports:
  - number: 5000
    name: http-registry
  location: MESH_INTERNAL
  resolution: NONE  
```

I can login into the UI without any issue. However when I push something to the docker registry I don't see the new repositories show up in the ui. However I am able to pull the images down

Other things to note:

- I cannot docker push using the admin user credentials
- I login to the docker registry using the following `docker login --username test --password test  https://harbor.hostname.co.uk`
- It seems I cannot upload charts into the chartmuseum
