### ISSUE TITLE
docker login with ingress expose

### ISSUE THREAD

**Issue by DFazeli** [goharbor/harbor-helm#1306]
I expose harbor with ingress:
`values.yaml:`
```
expose:
  type: ingress
  tls:
    enabled: true
    certSource: auto
 ingress:
    hosts:
      core: harbor.domain.com
      notary: notary.domain.com
externalURL: https://harbor.domain.com
```
my kubernetes behind haproxy and haproxy config is:

```
frontend front-ingress-nginx-443
    mode tcp
    bind *:443
   default_backend backend-ingress-nginx-443
backend backend-ingress-nginx-443
   mode tcp
   server ingress01 1.2.3.4:443     check
   server ingress02 5.6.7.8:443     check
   server ingress03 9.10.11.12:443 check
```
I can't login to registry with docker I facing :
```
Error response from daemon: Get "https://harbor.domain.com/v2/": EOF
```
I can access to harbor dashboard `https://harbor.domain.com/`, but docker login faild!
