### ISSUE TITLE
Bug with starting registryctl container when using azure existingSecret

### ISSUE THREAD

**Issue by ekarlso** [goharbor/harbor-helm#1309]
When running Harbor with the `persistence.imageChartStorage.azure.existingSecret` registryctl fails to come up.

Defaulted container "registry" out of: registry, registryctl
Appending internal tls trust CA to ca-bundle ...
Internal tls trust CA /etc/harbor/ssl/registry/ca.crt appended ...
Internal tls trust CA appending is Done.
time="2022-09-05T20:16:39.698246374Z" level=info msg="debug server listening localhost:5001" 
panic: no accountkey parameter provided

goroutine 1 [running]:
github.com/docker/distribution/registry/handlers.NewApp({0xeebbe0?, 0xc0002ecba0?}, 0xc0003df400)
	/go/src/github.com/docker/distribution/registry/handlers/app.go:130 +0x23d1
github.com/docker/distribution/registry.NewRegistry({0xeebbe0?, 0xc0004ef260?}, 0xc0003df400)
	/go/src/github.com/docker/distribution/registry/registry.go:161 +0x145
github.com/docker/distribution/registry.glob..func1(0xc0000301a0?, {0xc000387360, 0x1, 0x1})
	/go/src/github.com/docker/distribution/registry/registry.go:119 +0x18f
github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).execute(0x1442e00, {0xc000387320?, 0x2?, 0x2?})
	/go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:495 +0x43c
github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).Execute(0x1442fa0)
	/go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:560 +0xaa
main.main()
	/go/src/github.com/docker/distribution/cmd/registry/main.go:23 +0x25

**Comment by rgarcia89** [comment]
@zyyw I am experiencing the same issue.
Key is base64 enc stored in a secret called `harbor-azure`.

Deployment yaml looks good:
```yaml
        - name: REGISTRY_STORAGE_AZURE_ACCOUNTKEY
          valueFrom:
            secretKeyRef:
              name: harbor-azure
              key: AZURE_STORAGE_ACCESS_KEY
```

secret also matches:
```yaml
 k get secret harbor-azure -o yaml
apiVersion: v1
data:
  AZURE_STORAGE_ACCESS_KEY: XYZ...
...
```

What part of harbor is creating this error message? Maybe the environment variable is not used properly.
