### ISSUE TITLE
support Ingress path

### ISSUE THREAD

**Issue by Hokwang** [goharbor/harbor-helm#131]
Hello.

If I want to use paths in ingress like below, I think this does not support yet.

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: harbor
  name: harbor-ingress
spec:
  tls:
  - hosts:
    - test.net
    secretName: ingress-tls
  rules:
  - host: test.net
    http:
      paths:
      - path: /harbor
        backend:
          serviceName: harbor
          servicePort: xxxx
```

And what do you think about using https://github.com/helm/charts (official chart repo) ?
Is there a certain problem or roadmap for using this your own repo (https://github.com/goharbor/harbor-helm) ?

Many thanks,
