### ISSUE TITLE
[Harbor 2.6.0 / Registry] Incorrect deployment template with GCS

### ISSUE THREAD

**Issue by Kanshiroron** [goharbor/harbor-helm#1321]
Hello,
We have 3 deployments of Harbor (on AWS, GCP, and OpenStack), version **2.6.0** (charts version **1.10.0**) and the deployment on GCS resulted in an incorrect configuration of the registry deployment.

We uses this following configuration (extract):
```
persistence:
  enabled: false
  imageChartStorage:
    type: gcs
    gcs:
      bucket: my-registry-bucket
      # The base64 encoded json file which contains the key
      encodedkey: <base64 encoded json key>
      #rootdirectory: /gcs/object/name/prefix
      #chunksize: "5242880"
      # To use existing secret, the key must be gcs-key.json
      existingSecret: ""
      useWorkloadIdentity: false
```

With this configuration we see that the `GCS_KEY_DATA` is correctly populated in the `harbor-registry` secret but it's not mounted onto the registry pod. Looking at the template we can notice that it requires `persistence.enabled` set to true to work:
```
{{- if and (and .Values.persistence.enabled (eq .Values.persistence.imageChartStorage.type "gcs")) (not .Values.persistence.imageChartStorage.gcs.useWorkloadIdentity ) }}
```
https://github.com/goharbor/harbor-helm/blob/1.10.0/templates/registry/registry-dpl.yaml#L120
https://github.com/goharbor/harbor-helm/blob/1.10.0/templates/registry/registry-dpl.yaml#L232

But since we are storing everything on the object storage, and jobs in the database, we don't need local persistence (PVCs). And this should not be required according to the documentation (or only if the storage type is `filesystem` I presume):

```
# The persistence is enabled by default and a default StorageClass
# is needed in the k8s cluster to provision volumes dynamically.
# Specify another StorageClass in the "storageClass" or set "existingClaim"
# if you already have existing persistent volumes to use
#
# For storing images and charts, you can also use "azure", "gcs", "s3",
# "swift" or "oss". Set it in the "imageChartStorage" section
```
I manually made the change, and I can confirm that we don't need PVCs for it to work. I will add that this is not an issue that we have with AWS and OpenStack.

Thanks for the help!
