### ISSUE TITLE
Harbor v2.6.1: An internal error occurred when modifying project configuration when enabling cache (cache.enabled: true in values.yaml) 

### ISSUE THREAD

**Issue by derekcha** [goharbor/harbor-helm#1327]
I upgraded to harbor v2.6.1 (Helm 1.10.1) version , and set cache.enabled to true in values ​​to try the cache function.
However, an **"internal server error"** occurred when updating the project configuration during subsequent tests. Can you explain why?

This is the error log caught by the core when an error occurs.

```
2022-10-18T08:04:49Z [ERROR] [/lib/http/error.go:56]: {"errors":[{"code":"UNKNOWN","message":"unknown: ERR unknown command `keys`, with args beginning with: `cache:project_metadata:projectID:2*`, "}]} 
2022-10-18T08:06:40Z [ERROR] [/lib/http/error.go:56]: {"errors":[{"code":"UNKNOWN","message":"unknown: ERR unknown command `keys`, with args beginning with: `cache:project_metadata:projectID:2*`, "}]} 
```
jobservice log

```
2022-10-18T08:02:43Z [ERROR] [/jobservice/sync/schedule.go:211]: no task found for execution: SYSTEM_ARTIFACT_CLEANUP:2
2022-10-18T08:03:43Z [ERROR] [/jobservice/sync/schedule.go:211]: no task found for execution: SYSTEM_ARTIFACT_CLEANUP:2
```
For reference, I am using external redis and set values ​​as below.
```
redis:
  type: external
  external:
    addr: "external redis address"
    sentinelMasterSet: ""
    coreDatabaseIndex: "0"
    jobserviceDatabaseIndex: "1"
    registryDatabaseIndex: "2"
    chartmuseumDatabaseIndex: "3"
    trivyAdapterIndex: "5"
    password: ""
  podAnnotations: {}
```
I look forward to hearing from you. 
Thanks.
