### ISSUE TITLE
Initial admin login not working

### ISSUE THREAD

**Issue by hcbraun** [goharbor/harbor-helm#144]
Doing an initial installation with branch 1.0.0 (a3fa7c4), i can not sign in with admin. All pods start. Logs show no errors. The ui loads. Database gets created on the volume. On core i only get this on a login attempt:
```
2019-01-17T16:48:31Z [DEBUG] [security.go:233]: can not get user information from session
2019-01-17T16:48:31Z [DEBUG] [security.go:290]: user information is nil
2019-01-17T16:48:31Z [DEBUG] [security.go:304]: using local database project manager
2019-01-17T16:48:31Z [DEBUG] [security.go:306]: creating local database security context...
```

I have a Harbor v1.6.0 deployment with branch 0.3.0 with a similar configuration running. 

My configuration for v1.7.0 / 1.0.0:
```
logLevel: debug
harborAdminPassword: "admin"
externalURL: https://newhb.example.com
imagePullPolicy: IfNotPresent

expose:
  tls:
    enabled: false
  ingress:
    hosts:
      core: newhb.example.com
      notary: newhb-notary.example.com
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/proxy-redirect-from: "http:// https://"
      nginx.ingress.kubernetes.io/client-body-buffer-size: "1024M"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/configuration-snippet: |
        more_set_input_headers    "X-Forwarded-Port: 443";
        more_set_input_headers    "X-Forwarded-Proto: https";

persistence:
  enabled: true
  persistentVolumeClaim:
    registry:
      existingClaim: newhb-registry
      storageClass: nfs
      accessMode: ReadWriteOnce
      size: 10Mi
    chartmuseum:
      existingClaim: newhb-chartmuseum
      storageClass: nfs
      accessMode: ReadWriteOnce
      size: 10Mi
    jobservice:
      existingClaim: newhb-job
      storageClass: nfs
      accessMode: ReadWriteOnce
      size: 10Mi
    database:
      existingClaim: newhb-database
      storageClass: nfs
      accessMode: ReadWriteOnce
      size: 10Mi
    redis:
      existingClaim: newhb-redis
      storageClass: nfs
      accessMode: ReadWriteOnce
      size: 10Mi

chartmuseum:
  enabled: false

clair:
  enabled: false

notary:
  enabled: false

database:
  type: internal

redis:
  type: internal
```
