### ISSUE TITLE
GCP GKE ClusterIP install - login fails

### ISSUE THREAD

**Issue by brad-taylor-yvr** [goharbor/harbor-helm#1448]
Installing via helm chart 1.11.0, targeting harbor 2.7.0
Running on Google Cloud Platform (GCP) Google Kubernetes Engine (GKE) 1.23.16-gke.1100

values file:
```
logLevel: debug

caBundleSecretName: "example-internal-ca"
caSecretName: "example-internal-ca"
externalURL: https://harbor.internal.example.com
harborAdminPassword: thePassword
secretKey: 0123456789abcdef

proxy:
  noProxy: 127.0.0.1,localhost,.local,.internal,.internal.example.com,.example.ads
  
expose:
  type: clusterIP

  tls:
    enabled: false
    certSource: secret
    secret: 
      secretName: "harbor-tls"
      notarySecretName: "harbor-tls"

  clusterIP:
    name: harbor-main-service
    annotations: 
      cloud.google.com/neg: '{ "exposed_ports":{ "80":{"name": "shared-neg-harbor-core-http-80"} }}'  #, "4443":{"name": "shared-neg-harbor-notary-http-4443"} }}'

notary:
  enabled: false
  
ipFamily:
  ipv4: 
    enabled: true

  ipv6: 
    enabled: false

# The update strategy for deployments with persistent volumes(jobservice, registry
# and chartmuseum): "RollingUpdate" or "Recreate"
# Set it as "Recreate" when "RWM" for volumes isn't supported
updateStrategy:
  type: Recreate

persistence:
  enabled: true
  
  persistentVolumeClaim:
    registry: 
      storageClass: standard

    chartmuseum: 
      storageClass: standard

    jobservice: 
      storageClass: standard

    database: 
      storageClass: standard

    redis: 
      storageClass: standard

    trivy: 
      storageClass: standard

jobservice:
# per https://goharbor.io/docs/2.5.0/install-config/harbor-ha-helm/
# switch job logs to database persistence
  jobLoggers:
    - database
```

helm install succeeds:

```
helm -n harbor-shared list

NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
harbor-tf       harbor-shared   1               2023-03-17 18:12:46.98431808 +0000 UTC  deployed        harbor-1.11.0   2.7.0      

helm -n harbor-shared status harbor-tf
NAME: harbor-tf
LAST DEPLOYED: Fri Mar 17 18:12:46 2023
NAMESPACE: harbor-shared
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Please wait for several minutes for Harbor deployment to complete.
Then you should be able to visit the Harbor portal at https://harbor.internal.example.com
For more details, please visit https://github.com/goharbor/harbor
```
deployment looks successful:
```
kubectl -n harbor-shared get all -o wide
NAME                                         READY   STATUS    RESTARTS   AGE     IP             NODE                                                  NOMINATED NODE   READINESS GATES
pod/harbor-tf-chartmuseum-7ff8d4cbdf-rxbl8   1/1     Running   0          4h44m   172.19.0.140   gke-np-application-pool-9cd1e32d-qc2d   <none>           <none>
pod/harbor-tf-core-7dc8fd868d-9t86m          1/1     Running   0          4h44m   172.19.0.137   gke-np-application-pool-9cd1e32d-qc2d   <none>           <none>
pod/harbor-tf-jobservice-588884d54b-nwcqx    1/1     Running   0          4h44m   172.19.0.144   gke-np-application-pool-9cd1e32d-qc2d   <none>           <none>
pod/harbor-tf-nginx-74bff6fc56-5xxt8         1/1     Running   0          4h44m   172.19.0.138   gke-np-application-pool-9cd1e32d-qc2d   <none>           1/1
pod/harbor-tf-portal-769cdc4b74-g7jzk        1/1     Running   0          4h44m   172.19.0.139   gke-np-application-pool-9cd1e32d-qc2d   <none>           <none>
pod/harbor-tf-redis-0                        1/1     Running   0          4h44m   172.19.0.142   gke-np-application-pool-9cd1e32d-qc2d   <none>           <none>
pod/harbor-tf-registry-66b95dcc6c-gx8st      2/2     Running   0          4h44m   172.19.0.143   gke-np-application-pool-9cd1e32d-qc2d   <none>           <none>
pod/harbor-tf-trivy-0                        1/1     Running   0          4h44m   172.19.0.141   gke-np-application-pool-9cd1e32d-qc2d   <none>           <none>

NAME                            TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE     SELECTOR
service/harbor-main-service     ClusterIP   172.19.129.129   <none>        80/TCP              4h44m   app=harbor,component=nginx,release=harbor-tf
service/harbor-tf-chartmuseum   ClusterIP   172.19.131.45    <none>        80/TCP              4h44m   app=harbor,component=chartmuseum,release=harbor-tf
service/harbor-tf-core          ClusterIP   172.19.138.128   <none>        80/TCP              4h44m   app=harbor,component=core,release=harbor-tf
service/harbor-tf-jobservice    ClusterIP   172.19.140.99    <none>        80/TCP              4h44m   app=harbor,component=jobservice,release=harbor-tf
service/harbor-tf-portal        ClusterIP   172.19.142.24    <none>        80/TCP              4h44m   app=harbor,component=portal,release=harbor-tf
service/harbor-tf-redis         ClusterIP   172.19.142.19    <none>        6379/TCP            4h44m   app=harbor,component=redis,release=harbor-tf
service/harbor-tf-registry      ClusterIP   172.19.133.140   <none>        5000/TCP,8080/TCP   4h44m   app=harbor,component=registry,release=harbor-tf
service/harbor-tf-trivy         ClusterIP   172.19.128.52    <none>        8080/TCP            4h44m   app=harbor,component=trivy,release=harbor-tf

NAME                                    READY   UP-TO-DATE   AVAILABLE   AGE     CONTAINERS             IMAGES                                                               SELECTOR
deployment.apps/harbor-tf-chartmuseum   1/1     1            1           4h44m   chartmuseum            goharbor/chartmuseum-photon:v2.7.0                                   app=harbor,component=chartmuseum,release=harbor-tf
deployment.apps/harbor-tf-core          1/1     1            1           4h44m   core                   goharbor/harbor-core:v2.7.0                                          app=harbor,component=core,release=harbor-tf
deployment.apps/harbor-tf-jobservice    1/1     1            1           4h44m   jobservice             goharbor/harbor-jobservice:v2.7.0                                    app=harbor,component=jobservice,release=harbor-tf
deployment.apps/harbor-tf-nginx         1/1     1            1           4h44m   nginx                  goharbor/nginx-photon:v2.7.0                                         app=harbor,component=nginx,release=harbor-tf
deployment.apps/harbor-tf-portal        1/1     1            1           4h44m   portal                 goharbor/harbor-portal:v2.7.0                                        app=harbor,component=portal,release=harbor-tf
deployment.apps/harbor-tf-registry      1/1     1            1           4h44m   registry,registryctl   goharbor/registry-photon:v2.7.0,goharbor/harbor-registryctl:v2.7.0   app=harbor,component=registry,release=harbor-tf

NAME                                               DESIRED   CURRENT   READY   AGE     CONTAINERS             IMAGES                                                               SELECTOR
replicaset.apps/harbor-tf-chartmuseum-7ff8d4cbdf   1         1         1       4h44m   chartmuseum            goharbor/chartmuseum-photon:v2.7.0                                   app=harbor,component=chartmuseum,pod-template-hash=7ff8d4cbdf,release=harbor-tf
replicaset.apps/harbor-tf-core-7dc8fd868d          1         1         1       4h44m   core                   goharbor/harbor-core:v2.7.0                                          app=harbor,component=core,pod-template-hash=7dc8fd868d,release=harbor-tf
replicaset.apps/harbor-tf-jobservice-588884d54b    1         1         1       4h44m   jobservice             goharbor/harbor-jobservice:v2.7.0                                    app=harbor,component=jobservice,pod-template-hash=588884d54b,release=harbor-tf
replicaset.apps/harbor-tf-nginx-74bff6fc56         1         1         1       4h44m   nginx                  goharbor/nginx-photon:v2.7.0                                         app=harbor,component=nginx,pod-template-hash=74bff6fc56,release=harbor-tf
replicaset.apps/harbor-tf-portal-769cdc4b74        1         1         1       4h44m   portal                 goharbor/harbor-portal:v2.7.0                                        app=harbor,component=portal,pod-template-hash=769cdc4b74,release=harbor-tf
replicaset.apps/harbor-tf-registry-66b95dcc6c      1         1         1       4h44m   registry,registryctl   goharbor/registry-photon:v2.7.0,goharbor/harbor-registryctl:v2.7.0   app=harbor,component=registry,pod-template-hash=66b95dcc6c,release=harbor-tf

NAME                               READY   AGE     CONTAINERS   IMAGES
statefulset.apps/harbor-tf-redis   1/1     4h44m   redis        goharbor/redis-photon:v2.7.0
statefulset.apps/harbor-tf-trivy   1/1     4h44m   trivy        goharbor/trivy-adapter-photon:v2.7.0
```

I have configured the appropriate GCP resources to create a LB for this service:
- forwarding rule
- url map
- backend service
- neg for the ClusterIP service named _harbor-main-service_
- health check - http_health_check against root context 

The NEG / backend service is healthy based on the health check.

loading the externalURL value, i get the login page with all the images, js, etc.

I attempt to login with **admin** / **thePassword** and get a 401 status code.

I see the login request in the nginx log

```
kubectl -n harbor-shared logs --since=15m  pod/harbor-tf-nginx-74bff6fc56-5xxt8 | grep -C5 -i login

[17/Mar/2023:22:11:41 +0000]:130.211.0.114 - "GET /api/v2.0/ping HTTP/1.1" 200 4 "-" "GoogleHC/1.0" 0.002 0.001 .
[17/Mar/2023:22:11:41 +0000]:130.211.0.118 - "GET /api/v2.0/ping HTTP/1.1" 200 4 "-" "GoogleHC/1.0" 0.002 0.002 .
[17/Mar/2023:22:11:42 +0000]:130.211.3.9 - "GET /api/v2.0/ping HTTP/1.1" 200 4 "-" "GoogleHC/1.0" 0.002 0.002 .
[17/Mar/2023:22:11:42 +0000]:130.211.0.114 - "GET /api/v2.0/ping HTTP/1.1" 200 4 "-" "GoogleHC/1.0" 0.002 0.002 .
[17/Mar/2023:22:11:42 +0000]:130.211.0.118 - "GET /api/v2.0/ping HTTP/1.1" 200 4 "-" "GoogleHC/1.0" 0.002 0.002 .
[17/Mar/2023:22:11:42 +0000]:10.129.0.19 - "POST /c/login HTTP/1.1" 401 0 "https://harbor.internal.example.com/account/sign-in?redirect_url=%2Fharbor%2Fprojects" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36" 1.515 1.516 .
[17/Mar/2023:22:11:43 +0000]:130.211.3.9 - "GET /api/v2.0/ping HTTP/1.1" 200 4 "-" "GoogleHC/1.0" 0.002 0.003 .
[17/Mar/2023:22:11:43 +0000]:130.211.0.114 - "GET /api/v2.0/ping HTTP/1.1" 200 4 "-" "GoogleHC/1.0" 0.002 0.002 .
[17/Mar/2023:22:11:43 +0000]:130.211.0.118 - "GET /api/v2.0/ping HTTP/1.1" 200 4 "-" "GoogleHC/1.0" 0.002 0.002 .
[17/Mar/2023:22:11:44 +0000]:130.211.3.9 - "GET /api/v2.0/ping HTTP/1.1" 200 4 "-" "GoogleHC/1.0" 0.002 0.002 .
[17/Mar/2023:22:11:44 +0000]:130.211.0.114 - "GET /api/v2.0/ping HTTP/1.1" 200 4 "-" "GoogleHC/1.0" 0.002 0.002 .

```

and also in the core log:

```
kubectl -n harbor-shared logs --since=2m  pod/harbor-tf-core-7dc8fd868d-9t86m | grep -C5 admin

2023-03-17T22:04:37Z [DEBUG] [/server/middleware/security/unauthorized.go:28][requestID="3d5856a5-1141-4df2-aebb-7ffcc6f8dd19"]: an unauthorized security context generated for request GET /api/v2.0/ping
2023-03-17T22:04:37Z [DEBUG] [/server/middleware/log/log.go:30]: attach request id fe39d04e-e02b-4eaa-ad20-ae6e1e17cd51 to the logger for the request POST /c/login
2023-03-17T22:04:37Z [DEBUG] [/server/middleware/artifactinfo/artifact_info.go:54]: In artifact info middleware, url: /c/login
2023-03-17T22:04:37Z [DEBUG] [/server/middleware/security/unauthorized.go:28][requestID="fe39d04e-e02b-4eaa-ad20-ae6e1e17cd51"]: an unauthorized security context generated for request POST /c/login
2023-03-17T22:04:37Z [DEBUG] [/core/auth/authenticator.go:145]: Current AUTH_MODE is db_auth
2023-03-17T22:04:37Z [DEBUG] [/core/auth/authenticator.go:158]: Login failed, locking admin, and sleep for 1.5s
2023-03-17T22:04:38Z [DEBUG] [/server/middleware/log/log.go:30]: attach request id 2250f297-69d6-4e4b-8863-6e7fd4b5e822 to the logger for the request GET /api/v2.0/ping
2023-03-17T22:04:38Z [DEBUG] [/server/middleware/artifactinfo/artifact_info.go:54]: In artifact info middleware, url: /api/v2.0/ping
2023-03-17T22:04:38Z [DEBUG] [/server/middleware/security/unauthorized.go:28][requestID="2250f297-69d6-4e4b-8863-6e7fd4b5e822"]: an unauthorized security context generated for request GET /api/v2.0/ping
2023-03-17T22:04:38Z [DEBUG] [/server/middleware/log/log.go:30]: attach request id 5589dd49-3fcd-4cde-908e-cdb13437949d to the logger for the request GET /api/v2.0/ping
2023-03-17T22:04:38Z [DEBUG] [/server/middleware/artifactinfo/artifact_info.go:54]: In artifact info middleware, url: /api/v2.0/ping

```

The config map for nginx looks ok to me - i see the 5 locations mapped to the upstream core and the main location mapped to upstream portal.

I've seen other issues where people have added the path mapping, but based on the reverse-proxy config in nginx, I don't think this is necessary?
- https://github.com/goharbor/harbor/issues/6879#issuecomment-770719880
- https://github.com/goharbor/harbor-helm/issues/565#issuecomment-1238816325

```
2023-03-17T22:04:37Z [DEBUG] [/core/auth/authenticator.go:145]: Current AUTH_MODE is db_auth
2023-03-17T22:04:37Z [DEBUG] [/core/auth/authenticator.go:158]: Login failed, locking admin, and sleep for 1.5s
```

Based on the two lines in the log, it's not clear to me what steps are next to troubleshoot this issue.... please advise. (Some documentation for this use case would be helpful as well... ;)
