### ISSUE TITLE
database "registry" does not exist

### ISSUE THREAD

**Issue by billy98** [goharbor/harbor-helm#145]
I'm using the V1.0.0 version，There was no problem before, but there was a problem after helm reinstalled it。
kubetnetes version 1.13.0.
```
LOG: database system was interrupted; last known up at 2019-01-19 15:09:35 UTC
FATAL: the database system is starting up
FATAL: the database system is starting up
FATAL: the database system is starting up
FATAL: the database system is starting up
LOG: database system was not properly shut down; automatic recovery in progress
LOG: redo starts at 0/2AED0508
LOG: invalid record length at 0/2AED1A10: wanted 24, got 0
LOG: redo done at 0/2AED19E8
LOG: last completed transaction was at log time 2019-01-19 15:09:56.830595+00
LOG: MultiXact member wraparound protections are now enabled
LOG: database system is ready to accept connections
LOG: autovacuum launcher started
LOG: incomplete startup packet
FATAL: database "registry" does not exist
LOG: incomplete startup packet
FATAL: database "registry" does not exist
```

**Comment by ywk253100** [comment]
What do you mean about `helm reinstall`? Did you delete the old deployment before installing it again?

**Comment by billy98** [comment]
I removed the old deployment before reinstalling it

**Comment by billy98** [comment]
```
LOG: database system was interrupted; last known up at 2019-01-27 07:06:54 UTC
FATAL: the database system is starting up
FATAL: the database system is starting up
FATAL: the database system is starting up
LOG: database system was not properly shut down; automatic recovery in progress
LOG: invalid record length at 0/14EE950: wanted 24, got 0
LOG: redo is not required
LOG: MultiXact member wraparound protections are now enabled
LOG: database system is ready to accept connections
LOG: autovacuum launcher started
FATAL: database "notaryserver" does not exist
FATAL: database "notarysigner" does not exist
FATAL: database "notaryserver" does not exist
LOG: incomplete startup packet
FATAL: database "registry" does not exist
FATAL: database "notarysigner" does not exist
LOG: incomplete startup packet
FATAL: database "registry" does not exist
FATAL: database "notaryserver" does not exist
FATAL: database "notarysigner" does not exist
FATAL: database "notaryserver" does not exist
FATAL: database "notarysigner" does not exist
FATAL: database "notaryserver" does not exist
FATAL: database "notarysigner" does not exist
FATAL: database "notaryserver" does not exist
```

**Comment by ywk253100** [comment]
Are you using the internal database or the external database? Did you delete all PVCs before reinstalling the chart?

**Comment by billy98** [comment]
I used an internal database and did not delete PVC before reinstallation. Here is my configuration.
```
expose:
  # Set the way how to expose the service. Set the type as "ingress", 
  # "clusterIP" or "nodePort" and fill the information in the corresponding 
  # section
  type: ingress
  tls:
    # Enable the tls or not. Note: if the type is "ingress" and the tls 
    # is disabled, the port must be included in the command when pull/push
    # images. Refer to https://github.com/goharbor/harbor/issues/5291 
    # for the detail.
    enabled: true
    # Fill the name of secret if you want to use your own TLS certificate
    # and private key. The secret must contain keys named tls.crt and 
    # tls.key that contain the certificate and private key to use for TLS
    # The certificate and private key will be generated automatically if 
    # it is not set
    secretName: ""
    # By default, the Notary service will use the same cert and key as
    # described above. Fill the name of secret if you want to use a 
    # separated one. Only needed when the type is "ingress".
    notarySecretName: ""
    # The commmon name used to generate the certificate, it's necessary
    # when the type is "clusterIP" or "nodePort" and "secretName" is null
    commonName: ""
  ingress:
    hosts:
      core: harbor.cnlinux.club
      notary: notary.cnlinux.club
    annotations:
      ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
  clusterIP:
    # The name of ClusterIP service
    name: harbor
    ports:
      # The service port Harbor listens on when serving with HTTP
      httpPort: 80
      # The service port Harbor listens on when serving with HTTPS
      httpsPort: 443
      # The service port Notary listens on. Only needed when notary.enabled 
      # is set to true
      notaryPort: 4443
  nodePort:
    # The name of NodePort service
    name: harbor
    ports:
      http:
        # The service port Harbor listens on when serving with HTTP
        port: 80
        # The node port Harbor listens on when serving with HTTP
        nodePort: 30002
      https: 
        # The service port Harbor listens on when serving with HTTPS
        port: 443
        # The node port Harbor listens on when serving with HTTPS
        nodePort: 30003
      # Only needed when notary.enabled is set to true
      notary: 
        # The service port Notary listens on
        port: 4443
        # The node port Notary listens on
        nodePort: 30004

# The external URL for Harbor core service. It is used to
# 1) populate the docker/helm commands showed on portal
# 2) populate the token service URL returned to docker/notary client
# 
# Format: protocol://domain[:port]. Usually:
# 1) if "expose.type" is "ingress", the "domain" should be 
# the value of "expose.ingress.hosts.core"
# 2) if "expose.type" is "clusterIP", the "domain" should be
# the value of "expose.clusterIP.name"
# 3) if "expose.type" is "nodePort", the "domain" should be
# the IP address of k8s node 
# 
# If Harbor is deployed behind the proxy, set it as the URL of proxy
externalURL: https://harbor.cnlinux.club

# The persistence is enabled by default and a default StorageClass
# is needed in the k8s cluster to provision volumes dynamicly. 
# Specify another StorageClass in the "storageClass" or set "existingClaim"
# if you have already existing persistent volumes to use
#
# For storing images and charts, you can also use "azure", "gcs", "s3", 
# "swift" or "oss". Set it in the "imageChartStorage" section
persistence:
  enabled: true
  # Setting it to "keep" to avoid removing PVCs during a helm delete 
  # operation. Leaving it empty will delete PVCs after the chart deleted
  resourcePolicy: "keep"
  persistentVolumeClaim:
    registry:
      # Use the existing PVC which must be created manually before bound
      existingClaim: "pvc-harbor"
      # Specify the "storageClass" used to provision the volume. Or the default
      # StorageClass will be used(the default).
      # Set it to "-" to disable dynamic provisioning
      storageClass: ""
      subPath: "registry"
      accessMode: ReadWriteOnce
      size: 5Gi
    chartmuseum:
      existingClaim: "pvc-harbor"
      storageClass: ""
      subPath: "chartmuseum"
      accessMode: ReadWriteOnce
      size: 5Gi
    jobservice:
      existingClaim: "pvc-harbor"
      storageClass: ""
      subPath: "jobservice"
      accessMode: ReadWriteOnce
      size: 1Gi
    # If external database is used, the following settings for database will 
    # be ignored
    database:
      existingClaim: "pvc-harbor"
      storageClass: ""
      subPath: "database"
      accessMode: ReadWriteOnce
      size: 1Gi
    # If external Redis is used, the following settings for Redis will 
    # be ignored
    redis:
      existingClaim: "pvc-harbor"
      storageClass: ""
      subPath: "redis"
      accessMode: ReadWriteOnce
      size: 1Gi
  # Define which storage backend is used for registry and chartmuseum to store
  # images and charts. Refer to 
  # https://github.com/docker/distribution/blob/master/docs/configuration.md#storage 
  # for the detail.
  imageChartStorage:
    # Specify the type of storage: "filesystem", "azure", "gcs", "s3", "swift", 
    # "oss" and fill the information needed in the corresponding section. The type
    # must be "filesystem" if you want to use persistent volumes for registry
    # and chartmuseum
    type: filesystem
    filesystem:
      rootdirectory: /storage
      #maxthreads: 100
    azure:
      accountname: accountname
      accountkey: base64encodedaccountkey
      container: containername
      #realm: core.windows.net
    gcs:
      bucket: bucketname
      # TODO: support the keyfile of gcs
      #keyfile: /path/to/keyfile
      #rootdirectory: /gcs/object/name/prefix
      #chunksize: "5242880"
    s3:
      region: us-west-1
      bucket: bucketname
      #accesskey: awsaccesskey
      #secretkey: awssecretkey
      #regionendpoint: http://myobjects.local
      #encrypt: false
      #keyid: mykeyid
      #secure: true
      #v4auth: true
      #chunksize: "5242880"
      #rootdirectory: /s3/object/name/prefix
      #storageclass: STANDARD
    swift:
      authurl: https://storage.myprovider.com/v3/auth
      username: username
      password: password
      container: containername
      #region: fr
      #tenant: tenantname
      #tenantid: tenantid
      #domain: domainname
      #domainid: domainid
      #trustid: trustid
      #insecureskipverify: false
      #chunksize: 5M
      #prefix:
      #secretkey: secretkey
      #accesskey: accesskey
      #authversion: 3
      #endpointtype: public
      #tempurlcontainerkey: false
      #tempurlmethods:
    oss:
      accesskeyid: accesskeyid
      accesskeysecret: accesskeysecret
      region: regionname
      bucket: bucketname
      #endpoint: endpoint
      #internal: false
      #encrypt: false
      #secure: true
      #chunksize: 10M
      #rootdirectory: rootdirectory

imagePullPolicy: IfNotPresent
#imagePullPolicy: Always

logLevel: debug
# The initial password of Harbor admin. Change it from portal after launching Harbor
harborAdminPassword: "Harbor12345"
# The secret key used for encryption. Must be a string of 16 chars.
secretKey: "not-a-secure-key"

# If expose the service via "ingress", the Nginx will not be used
nginx:
  image:
    repository: goharbor/nginx-photon
    tag: v1.7.0
  replicas: 1
  # resources:
  #  requests:
  #    memory: 256Mi
  #    cpu: 100m
  nodeSelector: {}
  tolerations: []
  affinity: {}
  ## Additional deployment annotations
  podAnnotations: {}

portal:
  image:
    repository: goharbor/harbor-portal
    tag: v1.7.0
  replicas: 1
# resources:
#  requests:
#    memory: 256Mi
#    cpu: 100m
  nodeSelector: {}
  tolerations: []
  affinity: {}
  ## Additional deployment annotations
  podAnnotations: {}

core:
  image:
    repository: goharbor/harbor-core
    tag: v1.7.0
  replicas: 1
# resources:
#  requests:
#    memory: 256Mi
#    cpu: 100m
  nodeSelector: {}
  tolerations: []
  affinity: {}
  ## Additional deployment annotations
  podAnnotations: {}

adminserver:
  image:
    repository: goharbor/harbor-adminserver
    tag: v1.7.0
  replicas: 1
  # resources:
  #  requests:
  #    memory: 256Mi
  #    cpu: 100m
  nodeSelector: {}
  tolerations: []
  affinity: {}
  ## Additional deployment annotations
  podAnnotations: {}

jobservice:
  image:
    repository: goharbor/harbor-jobservice
    tag: v1.7.0
  replicas: 1
  maxJobWorkers: 10
  # The logger for jobs: "file", "database" or "stdout"
  jobLogger: file
# resources:
#   requests:
#     memory: 256Mi
#     cpu: 100m
  nodeSelector: {}
  tolerations: []
  affinity: {}
  ## Additional deployment annotations
  podAnnotations: {}

registry:
  registry:
    image:
      repository: goharbor/registry-photon
      tag: v2.6.2-v1.7.0
  controller:
    image:
      repository: goharbor/harbor-registryctl
      tag: v1.7.0
  replicas: 1
  # resources:
  #  requests:
  #    memory: 256Mi
  #    cpu: 100m
  nodeSelector: {}
  tolerations: []
  affinity: {}
  ## Additional deployment annotations
  podAnnotations: {}

chartmuseum:
  enabled: true
  image:
    repository: goharbor/chartmuseum-photon
    tag: v0.7.1-v1.7.0
  replicas: 1
  # resources:
  #  requests:
  #    memory: 256Mi
  #    cpu: 100m
  nodeSelector: {}
  tolerations: []
  affinity: {}
  ## Additional deployment annotations
  podAnnotations: {}

clair:
  enabled: true
  image:
    repository: goharbor/clair-photon
    tag: v2.0.7-v1.7.0
  replicas: 1
  # The http(s) proxy used to update vulnerabilities database from internet
  httpProxy:
  httpsProxy:
  # The interval of clair updaters, the unit is hour, set to 0 to 
  # disable the updaters
  updatersInterval: 12
  # resources:
  #  requests:
  #    memory: 256Mi
  #    cpu: 100m
  nodeSelector: {}
  tolerations: []
  affinity: {}
  ## Additional deployment annotations
  podAnnotations: {}

notary:
  enabled: true
  server:
    image:
      repository: goharbor/notary-server-photon
      tag: v0.6.1-v1.7.0
    replicas: 1
  signer:
    image:
      repository: goharbor/notary-signer-photon
      tag: v0.6.1-v1.7.0
    replicas: 1
  nodeSelector: {}
  tolerations: []
  affinity: {}
  ## Additional deployment annotations
  podAnnotations: {}

database:
  # if external database is used, set "type" to "external"
  # and fill the connection informations in "external" section
  type: internal
  internal:
    image:
      repository: goharbor/harbor-db
      tag: v1.7.0
    # The initial superuser password for internal database
    password: "changeit"
    # resources:
    #  requests:
    #    memory: 256Mi
    #    cpu: 100m
    nodeSelector: {}
    tolerations: []
    affinity: {}
  external:
    host: "192.168.0.1"
    port: "5432"
    username: "user"
    password: "password"
    coreDatabase: "registry"
    clairDatabase: "clair"
    notaryServerDatabase: "notary_server"
    notarySignerDatabase: "notary_signer"
    sslmode: "disable"
  ## Additional deployment annotations
  podAnnotations: {}

redis:
  # if external Redis is used, set "type" to "external"
  # and fill the connection informations in "external" section
  type: internal
  internal:
    image:
      repository: goharbor/redis-photon
      tag: v1.7.0
    # resources:
    #  requests:
    #    memory: 256Mi
    #    cpu: 100m
    nodeSelector: {}
    tolerations: []
    affinity: {}
  external:
    host: "192.168.0.2"
    port: "6379"
    # The "coreDatabaseIndex" must be "0" as the library Harbor
    # used doesn't support configuring it
    coreDatabaseIndex: "0"
    jobserviceDatabaseIndex: "1"
    registryDatabaseIndex: "2"
    chartmuseumDatabaseIndex: "3"
    password: ""
  ## Additional deployment annotations
  podAnnotations: {}
```

**Comment by billy98** [comment]
I deleted the PVC and reinstalled the same result

**Comment by ywk253100** [comment]
Could you debug it? Seems it's environment-related, you can find the Dockerfile for database here https://github.com/goharbor/harbor/blob/v1.7.0/make/photon/db/Dockerfile

**Comment by alfieyfc** [comment]
I'm running into a similar issue. Any updates for this thread? @billy98
My configuration is using Rancher Custom Catalog, tried to follow the description of rancher/rancher#17227 and goharbor/harbor#6617. 

The `harbor-database` pod shows this `FATAL: database "registry" does not exist` log, but then still stays at a `Running` state. However, the `adminserver` pod keeps on `CrashLoopBackOff` due to this. As a result, `harbor-core` and `jobservice`, which waits on `adminserver` crashes as well.

![06-database-log](https://user-images.githubusercontent.com/41598103/52585418-a1a98600-2e6f-11e9-8cdd-081db40397a0.PNG)
![01-1-admin-server-log](https://user-images.githubusercontent.com/41598103/52585425-a66e3a00-2e6f-11e9-9afe-3562c41e61e8.PNG)
![image](https://user-images.githubusercontent.com/41598103/52585514-f77e2e00-2e6f-11e9-8221-a75522863b37.png)

**Comment by tsingchao** [comment]
My solution is as follows:
1. Execute into the container
```shell
kubectl exec -it harbor-harbor-database-0 -n harbor /bin/bash
```
2. Run the initial scripts line by line manually 
```shell
postgres=# CREATE DATABASE registry ENCODING 'UTF8';
CREATE DATABASE

postgres=# \c registry;
You are now connected to database "registry" as user "postgres".

registry=# CREATE TABLE schema_migrations(version bigint not null primary key, dirty boolean not null);
CREATE TABLE
```

Now everything is perfect.

**Comment by mattthehearn** [comment]
I had to manually create the following databases:
notarysigner
notaryserver
registry

I didn't have to create the schema_migrations table, though, that seemed to happen automatically once the databases were created.

**Comment by jsonbruce** [comment]
**Problem**

The StatefulSet `harbor-harbor-database` failed:

```
 $ kubectl logs -n kube-public -f  harbor-harbor-database-0 database
LOG:  database system was shut down at 2019-03-08 10:09:54 UTC
FATAL:  the database system is starting up
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
FATAL:  database "postgres" does not exist
FATAL:  database "postgres" does not exist
FATAL:  database "postgres" does not exist
FATAL:  database "postgres" does not exist
 Session terminated, terminating shell...LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
 ...terminated.
```

The other StatefulSet `harbor-harbor-redis` is OK:

```
 $ kubectl get statefulset -n kube-public -o wide                                                                                                                 
NAME                     READY   AGE     CONTAINERS   IMAGES
harbor-harbor-database   0/1     5h45m   database     goharbor/harbor-db:dev
harbor-harbor-redis      1/1     5h45m   redis        goharbor/redis-photon:v1.7.0
```

And the other resources like PVC is OK:

```
 $ kubectl get pvc -n kube-public -o wide                                                                                                                         
NAME                                     STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
data-harbor-harbor-redis-0               Bound    pvc-6f7daad5-415b-11e9-8432-d43d7ece4b72   1Gi        RWO            nfs-client     5h47m
database-data-harbor-harbor-database-0   Bound    pvc-6f5e04f5-415b-11e9-8432-d43d7ece4b72   1Gi        RWO            nfs-client     5h47m
harbor-harbor-chartmuseum                Bound    pvc-6e43d3f0-415b-11e9-8432-d43d7ece4b72   5Gi        RWO            nfs-client     5h47m
harbor-harbor-jobservice                 Bound    pvc-6e44ae40-415b-11e9-8432-d43d7ece4b72   1Gi        RWO            nfs-client     5h47m
harbor-harbor-registry                   Bound    pvc-6e4763a5-415b-11e9-8432-d43d7ece4b72   5Gi        RWO            nfs-client     5h47m
```

**Comment by ywk253100** [comment]
@tsingchao @mattthehearn @jsonbruce Can you guys help me to debug the issue in your environment? I cannot reproduce it.

The databases `notaryserver`, `notarysigner` and `registry` should be created automatically when the container starting up.
You can find the init sql files `initial-notaryserver.sql`, `initial-notarysigner.sql` and `initial-registry.sql` here: https://github.com/goharbor/harbor/tree/v1.7.0/make/photon/db
They are copied into the container under directory `/docker-entrypoint-initdb.d/`:https://github.com/goharbor/harbor/blob/v1.7.0/make/photon/db/Dockerfile#L27

**Comment by cgiroudargoud** [comment]
I had the same issue and noticed that my container got killed, maybe too early because of a liveness probe failure.

To solve it, I increased the `initialDelaySeconds` to 30 and `periodSeconds` (to be safe) to 100 in `templates/database/database-ss.yaml` for the liveness probe; and the db pod seemed to have succesfully created the registry db this time.

**Comment by jsonbruce** [comment]
I found the bugs eventually via few experiments. This is due to two problems:

### 1. the [`livenessProbe`](https://github.com/goharbor/harbor-helm/blob/9f589b2088d2f4e55c57bc7ced46edb2cf39618c/templates/database/database-ss.yaml#L40) and [`readinessProbe`](https://github.com/goharbor/harbor-helm/blob/9f589b2088d2f4e55c57bc7ced46edb2cf39618c/templates/database/database-ss.yaml#L46) attribute. 

**Problem**
the StatefulSet `harbor-harbor-database` takes too much time (about 2 minutes in my machine, the predefined 10s is Far from enough) to init the postgres database and execute the `docker-entrypoint.sh` script.

**Solution**
Change to
```
        livenessProbe:
          exec:
            command:
            - /docker-healthcheck.sh
          initialDelaySeconds: 120
          periodSeconds: 120
        readinessProbe:
          exec:
            command:
            - /docker-healthcheck.sh
          initialDelaySeconds: 120
          periodSeconds: 120
```

### 2. the [`docker-healthcheck.sh`](https://github.com/goharbor/harbor/blob/eda6bbf8e669b0509256335994c793af9bab8275/make/photon/db/docker-healthcheck.sh#L4) script.
**Problem**
Although the Kubernetes check the health status by the exit code, but it still can throw the "hostname command not found" error and kubelet can catch it when execute this script.

**Solution**
Change to
```
host="$(cat /etc/hostname || echo '127.0.0.1')"
```
I created a PR about that.
