### ISSUE TITLE
PSA support

### ISSUE THREAD

**Issue by xhejtman** [goharbor/harbor-helm#1472]
I believe that harbor has no reason to run with baseline policy, it should run with the restricted policy.  This would be possible, if security context of each component is extended by container security context:
```
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
```
and pod security context:
```
securityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
```

it would be nice if this could be at least enabled in values.
