### ISSUE TITLE
Allow setting internalTrafficPolicy for services

### ISSUE THREAD

**Issue by theasp** [goharbor/harbor-helm#1504]
Hi,

Would it be reasonable to allow setting `internalTrafficPolicy` for the services from values?  i.e.

```yaml
registry:
  internalTrafficPolicy: Local
```

And that winds up in the service:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "harbor.registry" . }}"
  labels:
{{ include "harbor.labels" . | indent 4 }}
spec:
  internalTrafficPolicy: {{ template "harbor.registry.interalTraficPolicy" . }}
...
```

Default would be:
```yaml
registry:
  internalTrafficPolicy: Cluster
```
