### ISSUE TITLE
Use existing secret for external database password not working except core.

### ISSUE THREAD

**Issue by yh0xa55a8** [goharbor/harbor-helm#1506]
### Issue

When providing password of external database by using a exsiting secret: 

```yaml
database:
  external:
    host: external.postgres
    port: "5432"
    username: "harbor"
    password: ""
    coreDatabase: "harbor_core"
    notaryServerDatabase: "harbor_notary_server"
    notarySignerDatabase: "harbor_notary_signer"
    existingSecret: harbor-postgresql
```

and correctly set the harbor-postgresql secret with key `password`, core container could access to the database, but notary server and signer logs:
```
Failed to connect DB after 30 seconds, time out.
```

I believe that the template did not handle the db password correctly. 

This is what I found in templates/_helpers.tpl:

```
{{- define "harbor.database.rawPassword" -}}
  {{- if eq .Values.database.type "internal" -}}
    {{- .Values.database.internal.password -}}
  {{- else -}}
    {{- .Values.database.external.password -}}
  {{- end -}}
{{- end -}}
```

It seems that all external password in pods will be set to `password` field, ignoring existing secret, except harbor-core.

Considering k8s not allow a value copy between secrets, fix this could be complex. And I'm not good at making a helm chart. Could anybody handle this?
