### ISSUE TITLE
jobservice does not connect to external redis

### ISSUE THREAD

**Issue by Brice187** [goharbor/harbor-helm#1554]
Running Harbor v2.8.2 (Helm Chart 1.12.2) on Kubernetes 1.27.3

The jobservice pod tries to connect to redis:

```
2023-07-26T12:31:04Z [ERROR] [/jobservice/api/handler.go:291]: Serve http request 'GET /api/v1/stats' error: 500 {"code":10004,"message":"check stats of server failed with error","details":"dial tcp 10.42.0.112:6379: connect: cannot assign requested address"}
```
This is the ip / port of the first redis pod:

```
$ kubectl -n harbor get pods -o wide
NAME                                 READY   STATUS    RESTARTS        AGE     IP             NODE   NOMINATED NODE   READINESS GATES
harbor-core-567f684db7-2x2v8         1/1     Running   0               20h     10.42.5.139    kd7    <none>           <none>
harbor-core-567f684db7-jp85j         1/1     Running   0               20h     10.42.10.239   kd2    <none>           <none>
harbor-database-1                    1/1     Running   0               12h     10.42.12.143   kd3    <none>           <none>
harbor-database-2                    1/1     Running   0               36h     10.42.10.190   kd2    <none>           <none>
harbor-exporter-6fdd6cbdf9-jnctf     1/1     Running   0               2d12h   10.42.5.73     kd7    <none>           <none>
harbor-exporter-6fdd6cbdf9-sgmxv     1/1     Running   2 (36h ago)     36h     10.42.6.85     kd6    <none>           <none>
harbor-jobservice-6977875957-hvrw7   1/1     Running   53 (119s ago)   20h     10.42.10.238   kd2    <none>           <none>
harbor-jobservice-6977875957-qmgf4   1/1     Running   36 (38s ago)    19h     10.42.1.146    kd5    <none>           <none>
harbor-portal-5f9df9dd49-kjhcx       1/1     Running   0               2d12h   10.42.5.74     kd7    <none>           <none>
harbor-portal-5f9df9dd49-m9pjc       1/1     Running   0               36h     10.42.6.86     kd6    <none>           <none>
harbor-registry-77485668f6-67fcj     2/2     Running   0               20h     10.42.10.237   kd2    <none>           <none>
harbor-registry-77485668f6-z5jsg     2/2     Running   0               20h     10.42.6.89     kd6    <none>           <none>
redis-node-0                         3/3     Running   1 (13h ago)     36h     10.42.0.112    kd1    <none>           <none>
redis-node-1                         3/3     Running   1 (13h ago)     2d12h   10.42.5.75     kd7    <none>           <none>
redis-node-2                         3/3     Running   1 (13h ago)     4d13h   10.42.1.141    kd5    <none>           <none>
```

Why does the jobservice try to connect to the pod instead of the service (see below)? 

## additional information

values.yaml for jobservice and redis

```
jobservice:
  image:
    repository: harbor.example.net/dockerhub/goharbor/harbor-jobservice
    tag: v2.8.2
  replicas: 2
  revisionHistoryLimit: 3
  maxJobWorkers: 10
  # The logger for jobs: "file", "database" or "stdout"
  jobLoggers:
    - database
    - stdout
  # The jobLogger sweeper duration (ignored if `jobLogger` is `stdout`)
  loggerSweeperDuration: 14 #days
  
  redis:
  type: external
  external:
    # support redis, redis+sentinel
    # addr for redis: <host_redis>:<port_redis>
    # addr for redis+sentinel: <host_sentinel1>:<port_sentinel1>,<host_sentinel2>:<port_sentinel2>,<host_sentinel3>:<port_sentinel3>
    addr: "redis-node-0.redis-headless:26379,redis-node-1.redis-headless:26379,redis-node-2.redis-headless:26379"
    # The name of the set of Redis instances to monitor, it must be set to support redis+sentinel
    sentinelMasterSet: "harbor-sentinel-set"
    # The "coreDatabaseIndex" must be "0" as the library Harbor
    # used doesn't support configuring it
    coreDatabaseIndex: "0"
    jobserviceDatabaseIndex: "1"
    registryDatabaseIndex: "2"
    trivyAdapterIndex: "5"
```

is there a helm chart issue in the template:

harbor-helm/ templates / jobservice / jobservice-cm-env.yaml
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "harbor.jobservice" . }}-env"
  labels:
{{ include "harbor.labels" . | indent 4 }}
data:
  ....
  {{- if .Values.cache.enabled }}
  _REDIS_URL_CORE: "{{ template "harbor.redis.urlForCore" . }}"
  CACHE_ENABLED: "true"
  CACHE_EXPIRE_HOURS: "{{ .Values.cache.expireHours }}"
  {{- end }}
```

harbor-helm / templates /_helpers.tpl
```
...
/*scheme://[:password@]addr/db_index?idle_timeout_seconds=30*/
{{- define "harbor.redis.urlForCore" -}}
  {{- with .Values.redis }}
    {{- $index := ternary "0" .external.coreDatabaseIndex (eq .type "internal") }}
    {{- printf "%s/%s?idle_timeout_seconds=30" (include "harbor.redis.url" $) $index -}}
  {{- end }}
{{- end -}}

/*scheme://[:password@]addr/db_index*/
{{- define "harbor.redis.urlForJobservice" -}}
  {{- with .Values.redis }}
    {{- $index := ternary "1" .external.jobserviceDatabaseIndex (eq .type "internal") }}
    {{- printf "%s/%s" (include "harbor.redis.url" $) $index -}}
  {{- end }}
{{- end -}}
...
```
