### ISSUE TITLE
Unable to upgrade from 1.12.2 to 1.12.3

### ISSUE THREAD

**Issue by JSN-1** [goharbor/harbor-helm#1564]
Unable to upgrade from 1.12.2 to 1.12.3

I am using k3s v1.26.6+k3s1 and Longhorn 1.5.1 

```
helm upgrade --install --create-namespace --version 1.12.3 harbor -n harbor harbor/harbor
```

my values:
```
expose:
  ingress:
    hosts:
      core: [hidden]
  tls:
    auto:
      commonName: [hidden]
  type: clusterIP
externalURL: https://[hidden]
nginx:
  replicas: 0
```
  
error message:
```
Error: UPGRADE FAILED: cannot patch "harbor-jobservice" with kind PersistentVolumeClaim: PersistentVolumeClaim "harbor-jobservice" is invalid: spec.resources.requests.storage: Forbidden: field can not be less than previous value
```
