### ISSUE TITLE
Harbor Registry exec format error

### ISSUE THREAD

**Issue by AdamJSoftware** [goharbor/harbor-helm#1566]
When installing from helm chart. Everything works besides the harbor registry.

For the registry container I get the following error:
```
exec /home/harbor/entrypoint.sh: exec format error
```

Here is my helm config:
```
  values:
    expose:
      ingress:
        hosts:
          core: harbor.domain.com
      tls:
        enabled: false
    externalURL: https://harbor.domain.com
```

I can access the UI no problem
