### ISSUE TITLE
Initial cpu/memory requests and limits for all components

### ISSUE THREAD

**Issue by NicoForce** [goharbor/harbor-helm#1583]
Greetings,

I'm deploying harbor for the first time as a PoC; however, with the limited resources I have, I would like to setup proper minimum required cpu and memory requests.

I couldn't find that information anywhere in the docs, furthermore, the defaults for cpu and memory are empty.

Could you help me by letting me know the minimum and recommended cpu/memory values for the different components (portal, registry, database, redis, jobs, trivy, etc.)?

**Comment by NicoForce** [comment]
Fair enough, I hope somebody else is able to comment with their experience, would be a great reference point.

**Comment by antoineco** [comment]
Based on monitoring data from the past 2 weeks in a test environnement of mine, I can recommend the following settings for an environnement with low activity:

```yaml
  values:
    core:
      resources:
        requests:
          cpu: 500m
          memory: 200Mi
        limits:
          cpu: 500m
          memory: 200Mi
    jobservice:
      resources:
        requests:
          cpu: 80m
          memory: 50Mi
        limits:
          cpu: 80m
          memory: 50Mi
    portal:
      resources:
        requests:
          cpu: 40m
          memory: 15Mi
        limits:
          cpu: 40m
          memory: 15Mi
    registry:
      registry:
        resources:
          requests:
            cpu: 150m
            memory: 150Mi
          limits:
            cpu: 150m
            memory: 150Mi
      controller:
        resources:
          requests:
            cpu: 30m
            memory: 30Mi
          limits:
            cpu: 30m
            memory: 30Mi
    database:
      internal:
        resources:
          requests:
            cpu: 150m
            memory: 300Mi
          limits:
            cpu: 150m
            memory: 300Mi
    redis:
      internal:
        resources:
          requests:
            cpu: 100m
            memory: 80Mi
          limits:
            cpu: 100m
            memory: 80Mi
    trivy:
      resources:
        requests:
          cpu: 200m
          memory: 200Mi
        limits:
          cpu: 1
          memory: 200Mi
```
