### ISSUE TITLE
notary server get wrong db password when using external secret

### ISSUE THREAD

**Issue by mattiashem** [goharbor/harbor-helm#1594]
I started harbor and using an external secret for the Postgres password.
But the notary server did not pick up the password.
It looks like the progress URL is set in helm, and then it does not have access to the secret. 

```
 helm template  my-release harbor/harbor --dry-run --debug --set database.type=external --set database.external.existingSecret="pg-harbror-app"
```

This will generate a Secret with the following.

```
# Source: harbor/templates/notary/notary-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: my-release-harbor-notary-server
  labels:
    heritage: Helm
    release: my-release
    chart: harbor
    app: "harbor"
    component: notary
type: Opaque
data:
  NOTARY_SERVER_DB_URL: cG9zdGdyZXM6Ly91c2VyOnBhc3N3b3JkQDE5Mi4xNjguMC4xOjU0MzIvbm90YXJ5X3NlcnZlcj9zc2xtb2RlPWRpc2FibGU=
```

If we decode the string

```
 echo cG9zdGdyZXM6Ly91c2VyOnBhc3N3b3JkQDE5Mi4xNjguMC4xOjU0MzIvbm90YXJ5X3NlcnZlcj9zc2xtb2RlPWRpc2FibGU= | base64 -d
postgres://user:password@192.168.0.1:5432/notary_server?sslmode=disable
```

Dont know if you can use externalSecrets then the notary string is generated like this. And can't find anything on notary uses ENV.
