### ISSUE TITLE
Harbor with redis type: external

### ISSUE THREAD

**Issue by rakeshreddyrg09** [goharbor/harbor-helm#1606]
Hello, fellow developers in harbor
I am trying to install harbor with helm chart v 1.13.0, when it comes to the redis: external,
the harbor values file says If using existingSecret, the key must be REDIS_PASSWORD
![image](https://github.com/goharbor/harbor-helm/assets/48629246/cc29aa6e-641e-4088-a30d-1c192cb6813d)

but when I install the redis using helm chart (from bitnami) version 18.0.4 (appVersion: 7.2.1) the secret name is redis and its key is redis-password, not REDIS_PASSWORD. Can you please look into this team.

For the time being I have manually edited the helm chart of redis to change the key name of the secret to REDIS_PASSWORD and installed the harbor.

here is the below issue I am facing
![image](https://github.com/goharbor/harbor-helm/assets/48629246/27b5d4ab-1be0-444a-88ec-7cc93eab8113)

Steps to reproduce the problem:
Install harbor helm chart version 1.13.0
install redis helm chart version 18.0.4 (from bitnami)
change the redis type: external

**Comment by antoineco** [comment]
I'm also using the Redis Helm chart from Bitnami together with Harbor.
It allows using [your own secret](https://github.com/bitnami/charts/blob/5d99de8f754368dc8e29b9555b0411244029208c/bitnami/redis/values.yaml#L134-L141) too, so the easiest work around is probably to use the Redis Helm chart with the following values:

```yaml
# redis chart
auth:
  existingSecret: redis
  existingSecretPasswordKey: REDIS_PASSWORD
```

and ensure that the namespace where Harbor and Redis are deployed contains a secret of that shape:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: redis
  namespace: my-harbor-namespace
type: Opaque
data:
  REDIS_PASSWORD: bXktcmVkaXMtcGFzc3dvcmQ=
```
