### ISSUE TITLE
CSRF_KEY in core-secret.yaml not passed as environment variable

### ISSUE THREAD

**Issue by Gigigotrek** [goharbor/harbor-helm#1631]
The CSRF_KEY is generated in the [core-secret.yaml](https://github.com/goharbor/harbor-helm/blob/main/templates/core/core-secret.yaml#L27) but it not passed to the [core-dpl.yaml](https://github.com/goharbor/harbor-helm/blob/main/templates/core/core-dpl.yaml) as environment variable.

```
        env:
          - name: CSRF_KEY
            valueFrom:
              secretKeyRef:
                name: {{ template "harbor.core" . }}
                key: CSRF_KEY
```

Also, this secret should allow to be passed from other secret to be generated with ExternalSecret.
