### ISSUE TITLE
initdb: error: could not create directory "/var/lib/postgresql/data/pgdata": Permission denied

### ISSUE THREAD

**Issue by softlion** [goharbor/harbor-helm#1651]
I checked all values in the values.yaml and my pvc are standard.  
I created a specific pv and pvc for the db.  
The pv uses  volumeMode: Filesystem, is that supported ?

```yaml
  hostPath:
    path: /usr/k8slocal/pvc-harbor-db
    type: DirectoryOrCreate
```

Logs of the db pod:
```yaml
initdb: error: could not create directory "/var/lib/postgresql/data/pgdata": Permission denied
creating directory /var/lib/postgresql/data/pgdata/pg14 ...
```

I've seen old closed issues about that with no solution.
