### ISSUE TITLE
Trivy default CPU limit in values.yaml makes it impossible to run without limits when deploying through ArgoCD

### ISSUE THREAD

**Issue by franznemeth** [goharbor/harbor-helm#1656]
We are running multiple instances of harbor and we're using ArgoCD to manage these instances.
Since there is a default CPU limit for the trivy deployment in the harbor helm chart it is not possible to run trivy without limits since ArgoCD merges our values.yaml with the default values.yaml coming from the helm chart.

See: https://github.com/goharbor/harbor-helm/blob/726c44e0a9482d78a32cffb78afdf64baf677651/values.yaml#L720C1-L722C18

Steps to reproduce:
1.) Have a git repository that is connected to ArgoCD.
2.) Deploy the harbor helm chart the following way:
Chart.yaml
```yaml
apiVersion: v2
name: harbor
description: Harbor
type: application
version: 0.0.1
appVersion: "v0.0.1"
dependencies:
  - name: harbor
    version: 1.13.1
    repository: https://helm.goharbor.io
```
and a values.yaml like so:
```yaml
harbor:
  trivy:
    resources:
      limits: null
```

It will still rollout trivy with the default limits of 1CPU and 1GiB of memory.

My proposal would be to remove the default limits of trivy and let the user decide whether they want to set them or not. There are no default resources limits in the values.yaml so this would make it more consistent as well.

I am happy to create a PR for this if this is accepted.
