### ISSUE TITLE
Permission denied in database pod

### ISSUE THREAD

**Issue by mattthehearn** [goharbor/harbor-helm#171]
Hi all!  My harbor installation is failing, it seems because the database pod doesn't start.  The logs indicate that it's having trouble accessing configuration:

```
╰ 11:56:54 $ kubectl logs hearnharbor-harbor-database-0 
LOG:  could not open configuration file "/var/lib/postgresql/data/postgresql.conf": Permission denied
FATAL:  configuration file "/var/lib/postgresql/data/postgresql.conf" contains errors
```

My guess is that I've somehow misconfigured the persistent volume claim, but I can't figure out where it's gone wrong.  Other pods that use the PVC don't seem to have any issues.  I'm using GlusterFS, managed by Heketi.  Here is the relevant persistence section of values.yaml:

```
persistence:                                                                                                                                                                                                                                
    enabled: true                                                                                                                                                                                                                             
    # Setting it to "keep" to avoid removing PVCs during a helm delete                                                                                                                                                                        
    # operation. Leaving it empty will delete PVCs after the chart deleted                                                                                                                                                                    
    resourcePolicy: "keep"                                                                                                                                                                                                                    
    persistentVolumeClaim:                                                                                                                                                                                                                    
      registry:                                                                                                                                                                                                                               
~       # Use the existing PVC which must be created manually before bound                                                                                                                                                                    
~_      existingClaim: "harbor-pvc01"                                                                                                                                                                                                         
        # Specify the "storageClass" used to provision the volume. Or the default                                                                                                                                                             
        # StorageClass will be used(the default).                                                                                                                                                                                             
        # Set it to "-" to disable dynamic provisioning                                                                                                                                                                                       
~       storageClass: "gluster-heketi"                                                                                                                                                                                                        
        subPath: ""                                                                                                                                                                                                                           
        accessMode: ReadWriteOnce                                                                                                                                                                                                             
        size: 5Gi                                                                                                                                                                                                                             
      chartmuseum:                                                                                                                                                                                                                            
~       existingClaim: "harbor-pvc01"                                                                                                                                                                                                         
~       storageClass: "gluster-heketi"                                                                                                                                                                                                        
        subPath: ""                                                                                                                                                                                                                           
        accessMode: ReadWriteOnce                                                                                                                                                                                                             
        size: 5Gi                                                                                                                                                                                                                             
      jobservice:                                                                                                                                                                                                                             
~       existingClaim: "harbor-pvc01"                                                                                                                                                                                                         
~       storageClass: "gluster-heketi"                                                                                                                                                                                                        
        subPath: ""                                                                                                                                                                                                                           
        accessMode: ReadWriteOnce                                                                                                                                                                                                             
        size: 1Gi                                                                                                                                                                                                                             
      # If external database is used, the following settings for database will                                                                                                                                                                
      # be ignored                                                                                                                                                                                                                            
      database:                                                                                                                                                                                                                               
~       existingClaim: "harbor-pvc01"                                                                                                                                                                                                         
~       storageClass: "gluster-heketi"                                                                                                                                                                                                        
        subPath: ""                                                                                                                                                                                                                           
        accessMode: ReadWriteOnce                                                                                                                                                                                                             
        size: 1Gi                                                                                                                                                                                                                             
      # If external Redis is used, the following settings for Redis will                                                                                                                                                                      
      # be ignored                                                                                                                                                                                                                            
      redis:                                                                                                                                                                                                                                  
~       existingClaim: "harbor-pvc01"                                                                                                                                                                                                         
~       storageClass: "gluster-heketi"                                                                                                                                                                                                        
        subPath: ""                                                                                                                                                                                                                           
        accessMode: ReadWriteOnce                                                                                                                                                                                                             
        size: 1Gi
```

Here's the yaml I used to create the PVC:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-pvc01
  annotations:
    volume.beta.kubernetes.io/storage-class: gluster-heketi  
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi 
```

As near as I can tell, GlusterFS and Heketi are working fine.  I'm sure I've just screwed up some permissions setting, but I'm struggling to identify which.

**Comment by ywk253100** [comment]
As you have already configured the `existingClaim`, the `storageClass` will take no effect anymore.
And as all the components are using the same `existingClaim`(harbor-pvc01), you need to configure the `subPath` for every component with different values to avoid the conflict.

**Comment by ywk253100** [comment]
This is commented on master branch already: https://github.com/goharbor/harbor-helm/blob/master/values.yaml#L107

**Comment by Naisisor** [comment]
@ywk253100 你好，我也遇到了相同的问题，我的配置，如下：
```
persistence:
  ...
  database:
      existingClaim: "database-pvc"
      storageClass: "-"
      subPath: "database"
      accessMode: ReadWriteOnce
      size: 1Gi
  ...
```
我使用的是阿里云挂载盘，我尝试了两种存储卷类型：
1. oss 类型的存储卷：使用 oss 类型的存储卷，就会很报错，错误信息如下：
 ```
  The files belonging to this database system will be owned by user "postgres".
  This user must also own the server process.
    The database cluster will be initialized with locales
    COLLATE:  en_US.UTF-8
    CTYPE:    en_US.UTF-8
    MESSAGES: C
    MONETARY: C
    NUMERIC:  C
    TIME:     C
  The default text search configuration will be set to "english".
    Data page checksums are disabled.
    fixing permissions on existing directory /var/lib/postgresql/data ... ok
  creating subdirectories ... ok
  selecting default max_connections ... 100
  selecting default shared_buffers ... 128MB
  selecting default timezone ... UTC
  selecting dynamic shared memory implementation ... posix
  creating configuration files ... ok
  LOG:  could not link file "pg_xlog/xlogtemp.24" to "pg_xlog/000000010000000000000001": Operation not permitted
  FATAL:  could not open file "pg_xlog/000000010000000000000001": No such file or directory
  child process exited with exit code 1
  initdb: removing contents of data directory "/var/lib/postgresql/data"
  running bootstrap script ... 
  ``` 
2. 云盘：database 可以正常启动
