### ISSUE TITLE
Deploying chart with 1.7.1 images tags causes core to continuously crash

### ISSUE THREAD

**Issue by danielfbm** [goharbor/harbor-helm#173]
While using the latest chart (currently using revision 72d0f74) with v1.7.1 or equivalent image tags will cause harbor-core to crash continuously:
```
2019-03-03T04:59:18Z [ERROR] [utils.go:101]: failed to connect to tcp://adminserver:8080, retry after 2 seconds :dial tcp: lookup adminserver on 10.96.0.10:53: no such host
```

I believe that this was introduced in this [Pull-request 163](https://github.com/goharbor/harbor-helm/pull/163)

Another issue that I noticed was the lack of some versions/image tags in the Docker Hub repos. For instance, The [harbor-portal repo](https://hub.docker.com/r/goharbor/harbor-portal/tags) does not have v1.6.X neither v1.7.2 v1.7.3. I am not sure if this issue should be posted here, but I believe this adminservice dependency was removed in either v1.7.2 or 3. While using dev tags the issue does not happen.

**Comment by paulczar** [comment]
Yeah the current version of the chart kills out the admin server, the older images need the admin server.

Revision https://github.com/goharbor/harbor-helm/tree/99e8fa67b1dd42908f48a929ff772db8bf657cea seems to do the trick ... and here's my list of images/tags:

```yaml

portal:
  image:
    repository: goharbor/harbor-portal
    tag: v1.7.1

core:
  image:
    repository: goharbor/harbor-core
    tag: v1.7.1

adminserver:
  image:
    repository: goharbor/harbor-adminserver
    tag: v1.7.1

jobservice:
  image:
    repository: goharbor/harbor-jobservice
    tag: v1.7.1

registry:
  registry:
    image:
      repository: goharbor/registry-photon
      tag: v2.6.2-v1.7.1
  controller:
    image:
      repository: goharbor/harbor-registryctl
      tag: v1.7.1

chartmuseum:
  image:
    repository: goharbor/chartmuseum-photon
    tag: v0.7.1-v1.7.1

clair:
  image:
    repository: goharbor/clair-photon
    tag: v2.0.7-v1.7.1


notary:
  server:
    image:
      repository: goharbor/notary-server-photon
      tag: v0.6.1-v1.7.1


  signer:
    image:
      repository: goharbor/notary-signer-photon
      tag: v0.6.1-v1.7.1


database:
    image:
      repository: goharbor/harbor-db
      tag: v1.7.1

redis:
    image:
      repository: goharbor/redis-photon
      tag: v1.7.1
```
