### ISSUE TITLE
"/var/lib/postgresql/data/pgdata/pg14" has invalid permissions

### ISSUE THREAD

**Issue by mibaumit** [goharbor/harbor-helm#1746]
After installing harbor via helm with below "harbor-values.yml" on kubernetes cluster it crashes after a while:

First harbor-database-0 then harbor-core and harbor-jobservice end up in CrashLoopBackOff due to permissions error:

Error from "kubectl logs pod/harbor-database-0 -n harbor":

```
Defaulted container "database" out of: database, data-migrator (init), data-permissions-ensurer (init)
2024-04-22 13:45:37.101 UTC [1] FATAL:  data directory "/var/lib/postgresql/data/pgdata/pg14" has invalid permissions
2024-04-22 13:45:37.101 UTC [1] DETAIL:  Permissions should be u=rwx (0700) or u=rwx,g=rx (0750).

```

we are using following helm-values.yml

```
expose:
  type: ingress
  ingress:
    annotations:
      kubernetes.io/tls-acme: "true"
    hosts:
      core: harbor.dev.test.de
  tls:
    enabled: true
    certSource: auto
externalURL: https://harbor.dev.test.de
harborAdminPassword: xxxx
chartmuseum:
  enabled: false
clair:
  enabled: false
notary:
  enabled: false
trivy:
  enabled: false
jobservice:
  jobLogger: stdout
size: "20Gi"
persistence:
  persistentVolumeClaim:
    registry:
      size: 15Gi
volumePermissions:
  enabled: true
```

Does anyone have a clue what could cause this?
