### ISSUE TITLE
Harbor Helm custom values.yaml file

### ISSUE THREAD

**Issue by jmakanjuola** [goharbor/harbor-helm#176]
## Issue 1: `chart-museum`

We already have an existing `chart-museum` in place already. But the issue is that it appears that Harbor still deploys `chart-museum` even though `chart-museum` was undefined in my custom 'values.yaml' file. 

## Issue 2: `ingress hosts`

Here is the  Harbor ingress from actual `values.yaml` file.

```
ingress:
    hosts:
      core: core.harbor.domain
      notary: notary.harbor.domain
    annotations:
      ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
```

Below is ingress from my actual custom `values.yaml ` file 

```
ingress:
  enabled: true
  annotation:
    kubernetes.io/ingress.class: "nginx-internal"
    kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    notary: "notary.harbor.development.lab"
    core: "core.harbor.development.lab"
  tls:
    - secretName: harbor-tls
      hosts:
        -  "notary.harbor.development.lab"
    - secretName: core-tls
      hosts:
        - "core.harbor.development.lab"
```

After deploying Harbor, here are the outputs 

```
==> v1beta1/Ingress
NAME                                  HOSTS                                    ADDRESS  PORTS  AGE
infrastructure-harbor-harbor-ingress  core.harbor.domain,notary.harbor.domain  80, 443  13m
```

it appears that the ingress hosts names still defaults to `core.harbor.domain & notary.harbor.domain` instead of the custom hosts defined in my custom `values.yaml` file.  

All thoughts and suggestions are welcome! Thanks a lot in advance.
