### ISSUE TITLE
[harbor 1.14.2] setting s3 chunksize or other multiparth configuration options crashes the registry

### ISSUE THREAD

**Issue by adippl** [goharbor/harbor-helm#1769]
Something is wrong with docker registry binary in the latest version of this chart.
Setting any of these values in s3 configuration crashes the registry.

```
multipartcopychunksize
multipartcopythresholdsize
chunksize
```

Example configuration I'm used in my tests
```
persistence:
  imageChartStorage:
    type: s3
    s3:
      region: xxx
      bucket: harbor-test-bucket
      regionendpoint: xxx
      secure: true
      storageclass: NONE 
      accesskey: xxx
      secretkey: xxx
      multipartcopymaxconcurrency: 100
      forcepathstyle: true
      chunksize: 134217728
```
134217728 = 128MiB is a correct value between 5MiB and 5GiB

Crashing registry container.

```
Appending internal tls trust CA to ca-bundle ...
find: '/etc/harbor/ssl': No such file or directory
Internal tls trust CA appending is Done.
time="2024-06-08T15:08:33.5063299Z" level=info msg="debug server listening localhost:5001" 
panic: invalid value for chunksize: 1.34217728e+08

goroutine 1 [running]:
github.com/docker/distribution/registry/handlers.NewApp({0xee7800?, 0xc0003d59b0?}, 0xc0003db000)
	/go/src/github.com/docker/distribution/registry/handlers/app.go:129 +0x23a5
github.com/docker/distribution/registry.NewRegistry({0xee7800?, 0xc0003d4ae0?}, 0xc0003db000)
	/go/src/github.com/docker/distribution/registry/registry.go:161 +0x125
github.com/docker/distribution/registry.glob..func1(0x8?, {0xc000389f50, 0x1, 0x1})
	/go/src/github.com/docker/distribution/registry/registry.go:119 +0x185
github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).execute(0x148a420, {0xc000389f10?, 0x2?, 0x2?})
	/go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:495 +0x3ff
github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).Execute(0x148a5c0)
	/go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:560 +0xaa
main.main()
	/go/src/github.com/docker/distribution/cmd/registry/main.go:23 +0x1a
```
