### ISSUE TITLE
Registry Credentials `htpasswdString` and `existingSecret` do not work as expected

### ISSUE THREAD

**Issue by Nathan-Nesbitt** [goharbor/harbor-helm#1830]
This is the original issue: https://github.com/goharbor/harbor/issues/20822#issuecomment-2362518519

I investigated further, looks that the issue is in relation to the `values.yaml` 

```yaml
credentials:
    username: "harbor_registry_user"
    password: "harbor_registry_password"
    # If using existingSecret, the key must be REGISTRY_PASSWD and REGISTRY_HTPASSWD
    existingSecret: ""
    # Login and password in htpasswd string format. Excludes `registry.credentials.username`  and `registry.credentials.password`. May come in handy when integrating with tools like argocd or flux. This allows the same line to be generated each time the template is rendered, instead of the `htpasswd` function from helm, which generates different lines each time because of the salt.
    # htpasswdString: $apr1$XLefHzeG$Xl4.s00sMSCCcMyJljSZb0 # example string
    htpasswdString: ""
```

If you use the `username` and `password` values, it will work as expected. But if you try to use the `htpasswdString` or `existingSecret`, it does not work. We do see the error from the previously defined bug.

To test the existing secret we set it to an existing secret in the namespace, reference it in the `yaml`, then fill in both the `username` and `password` values in the secret. We also check by putting in the `htpasswdString` into the secret to test if that works. 

It could be a misunderstanding on how there are supposed to work, but as far as I can tell the secret is configured properly. 

Any information on the proper setup / potential causes of this would be greatly appreciated :)

**Comment by Vad1mo** [comment]
this is a "common"/"known" bug, I mentioned that a few times. There was also a comment in the yaml, (apparently its gone) 

if `htpasswdString` is set, you also need to set `username` and `password` , with matching username and password. because `username` and `password` are used on the sender side (in harbor-core) whereas  htpasswdString is used on registry.

**Comment by Nathan-Nesbitt** [comment]
> this is a "common"/"known" bug, I mentioned that a few times. There was also a comment in the yaml, (apparently its gone) 
> 
> if `htpasswdString` is set, you also need to set `username` and `password` , with matching username and password. because `username` and `password` are used on the sender side (in harbor-core) whereas  htpasswdString is used on registry. 

Thanks for letting me know, so does this apply to the secret as well? So you would need 

- username
- password
- htpasswdString 

All defined in the secret?

Because I've found that even when we set all 3 within the secret, it's causing an issue.

**Comment by Vad1mo** [comment]
I would say so, but it seems doubtable made a different experience. Try to render the manifests locally and see if you get the matching username password taken from your secrets

**Comment by Nathan-Nesbitt** [comment]
@Vad1mo how would we check the username/password/htpasswdString that is pulled into the application? Is there a way to have it log environment variables on run for each and dump the variables where they are being used?

We have these two scenarios:

1. (Works) Username + password directly in the `values.yaml`
2. (Doesn't work) Username + password stored in a secret, secret specified in the `values.yaml`

So I'm thinking it could be:

1. The secret isn't formatted correctly (key names aren't as expected)
2. The value for specifying the secret in the `values.yaml` should be different


Thanks :)

**Comment by bobindagit** [comment]
Hey guys, I've managed to deploy Helm Chart version 1.16.0.

Here is some important points:

### REGISTRY_HTPASSWD:
- Generate htpasswd string using command (**use `harbor_registry_user` as a login!!!**):
`htpasswd -nbBC 10 harbor_registry_user {PASSWORD}`
- Generated password part in htpasswd should start with: `$2a$`

### REGISTRY_PASSWD:
- Plain password which was used in previous step

### values.yaml

- **harbor-credentials** has **REGISTRY_HTPASSWD** and **REGISTRY_PASSWD** keys in it

```
registry:
  credentials:
    existingSecret: harbor-credentials
```

**Comment by ebuildy** [comment]
My 2 cents, we use External Secret Operator, with a password generator to generate the secret:

```yaml
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: registry-password
spec:
  refreshPolicy: CreatedOnce
  target:
    name: registry-password
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        REGISTRY_PASSWD: "{{`{{ .password }}`}}"
        REGISTRY_HTPASSWD: "{{ `{{ htpasswd `harbor_registry_user` .password }}` }}"
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: ClusterGenerator
        name: cluster-generator
```

**Comment by Allowencer** [comment]
> Hey guys, I've managed to deploy Helm Chart version 1.16.0.
> 
> Here is some important points:
> 
> ### REGISTRY_HTPASSWD:
> * Generate htpasswd string using command (**use `harbor_registry_user` as a login!!!**):
>   `htpasswd -nbBC 10 harbor_registry_user {PASSWORD}`
> * Generated password part in htpasswd should start with: `$2a$`
> 
> ### REGISTRY_PASSWD:
> * Plain password which was used in previous step
> 
> ### values.yaml
> * **harbor-credentials** has **REGISTRY_HTPASSWD** and **REGISTRY_PASSWD** keys in it
> 
> ```
> registry:
>   credentials:
>     existingSecret: harbor-credentials
> ```

I could kiss you for this post. You just saved me from ripping out my hair

ENSURE the username is harbor_registry_user for sure!

Harbor v2.14.3, I successfully am using an existingSecret in the registry.credentials. section.

Secret YAML:
```
apiVersion: v1
kind: Secret
metadata:
  name: harbor-registry-cred
  namespace: harbor
type: Opaque
stringData:
  REGISTRY_PASSWD: <password_in_plain_text_no_quotes_around_it>
  REGISTRY_HTPASSWD: harbor_registry_user:$2a$<bts_value>
```
