### ISSUE TITLE
Kubernetes cannot pull from a Harbor Registry deployed with ClusterIP

### ISSUE THREAD

**Issue by felixs8696** [goharbor/harbor-helm#1838]
I have a helmfile like such

```
# helmfile.dev.yaml
repositories:
  - name: harbor
    url: https://helm.goharbor.io

releases:
  - name: harbor
    chart: harbor/harbor
    namespace: harbor
    values:
      - expose:
          type: clusterIP
        externalURL: "http://harbor.harbor.svc.cluster.local:80"
        persistence:
          enabled: true
          persistentVolumeClaim:
            registry:
              size: 10Gi
```

I am able to push to it using a simple kaniko job like such
```
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    job-name: build-hello-world-0.0.0-test-3
  name: build-hello-world-0.0.0-test-3
  namespace: default
spec:
  template:
    metadata:
      labels:
        job-name: build-hello-world-0.0.0-test-3
    spec:
      containers:
      - args:
        - --context=tar:///mnt/build-contexts/1234567890/context.tar.gz
        - --dockerfile=Dockerfile
        - --destination=harbor.harbor.svc.cluster.local:80/hello-world:0.0.0
        - --verbosity=debug
        image: gcr.io/kaniko-project/executor:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: DOCKER_CONFIG
            value: /kaniko/.docker
        name: kaniko
        volumeMounts:
        - mountPath: /mnt/build-contexts
          name: build-context-pvc
        - mountPath: /kaniko/.docker
          name: build-registry-secret
      restartPolicy: Never
      volumes:
      - name: build-context-pvc
        persistentVolumeClaim:
          claimName: build-context-pvc
      - name: build-registry-secret
        secret:
          defaultMode: 420
          secretName: build-registry-creds
```

However, when I try to make a dimple deployment based on this image that I've successfully pushed, I get this erroring event

```
│ Events:                                                                                                                                                                                                                                            │
│---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------│
│ Type      Reason     Age                   From               Message                                                                                                                                                                            │
│---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------│
│ Normal    Scheduled  13m                   default-scheduler  Successfully assigned default/hello-world-864ce95b-build-57f7d5f68f-lf6vd to minikube                                                                                              │
│ Warning   Failed     10m (x4 over 13m)     kubelet            Failed to pull image "harbor.harbor.svc.cluster.local:80/hello-world:0.0.0": Error response from daemon: Get "https://harbor.harbor.svc.cluster.local:80/v2/": dial tcp: lookup harbor.harbor.svc.cluster.local: │
│                                                             Temporary failure in name resolution                                                                                                                                                 │
```

Here is my deployment.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-build
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-build
  template:
    metadata:
      labels:
        app: hello-world-build
    spec:
      containers:
      - env:
        - name: DOCKER_CONFIG
          value: /.docker
        image: harbor.harbor.svc.cluster.local:80/hello-world:0.0.0
        imagePullPolicy: IfNotPresent
        name: hello-world
        ports:
        - containerPort: 8000
          protocol: TCP
        volumeMounts:
        - mountPath: /.docker
          name: build-registry-secret
      volumes:
      - name: build-registry-secret
        secret:
          defaultMode: 420
          secretName: build-registry-creds
```
