### ISSUE TITLE
Cannot change default harbor admin password

### ISSUE THREAD

**Issue by framctr** [goharbor/harbor-helm#1839]
I deployed Harbor successfully on Kubernetes and everything is working fine. However, I cannot change the default admin password from the chart values.
```yaml
  repo: https://helm.goharbor.io
  chart: harbor
  version: "1.15.1"
  values:
    [...]
    existingSecretAdminPassword: harbor-admin-password
    existingSecretAdminPasswordKey: HARBOR_ADMIN_PASSWORD
```

I tried adding the `harborAdminPassword: ""` to force using password from secret, but it does not work.

After applying changes, Harbor restart all containers, with the `core` one loading the admin password from the secret, but Harbor keeps default password when logging in from the dashboard.

Note: Harbor password is built according to the required rules (8-128 characters long with at least 1 uppercase, 1 lowercase and 1 number)

The admin password can be changed only from dashboard or from accessing the PostgreSQL DB directly with `psql`.
