### ISSUE TITLE
/license /LICENSE endpoints always exposed

### ISSUE THREAD

**Issue by Newman-Hui** [goharbor/harbor-helm#1892]
**Is your feature request related to a problem? Please describe.**
When exposing the ingress, the /license and /LICENSE paths are always exposed. When using Nginx, this isn't an issue as you can use the "server-snippet" annotation to block the path; however, Traefik does not offer a solution without an existing path for it. Since the ingress paths in the template don't explicitly set a path for /license and /LICENSE, middlewares like replacePathPrefix don't apply.

**Describe the solution you'd like**
Either create set the path for /license and /LICENSE, or allow users to set their own paths in the values.yaml

**Describe the main design/architecture of your solution**
```yaml
# values.yaml
expose:
  ingress:
    additionalPaths: {}
    # - path: {{ some_path }}
    #    pathType: {{ some_path_type }}
    #    backend:
    #      service:
    #        name: {{ some_service }}
    #        port:
    #          number: {{ some_port }}

#/templates/ingress/ingress.yaml
  rules:
  - http:
      paths:
{{ toYaml $ingress.additionalPaths | indent 6 }}
```
