### ISSUE TITLE
Enhance Harbor Helm Chart: Granular Persistence Configuration for Individual Components

### ISSUE THREAD

**Issue by EduGoma** [goharbor/harbor-helm#1912]
Is your feature request related to a problem? Please describe.
Currently, the Harbor Helm chart offers limited configurability when enabling persistence. Users can only enable persistence globally, which applies to all components of Harbor. This limitation can be frustrating when users want to enable persistence for specific components, such as the registry, Trivy, Jobservice, database (PostgreSQL), or Redis, without applying it to the entire stack. This lack of granularity makes it difficult to optimize storage usage and costs according to specific requirements.

Describe the solution you'd like
I propose that the Harbor Helm chart introduces the ability to configure persistence on a per-component basis. This means that in the values.yaml file, users should be able to enable or disable persistence independently for each component. For example, users should have the option to configure persistence for:

- Registry
- Trivy
- Jobservice
- Database (PostgreSQL)
- Redis

This granular approach would allow users to better align storage configuration with their operational needs and resources.

**Comment by MinerYang** [comment]
Hi @EduGoma ,

May I know why you want to disable some of these PVs, it should not be configurable since harbor needs this relevant data to be persistent.

However for the registry PV  you could choose to use cloud storage

**Comment by janpipan** [comment]
You can granularly disable persistent volume with existing Helm chart. Here are the examples of how you can do that for PostgreSQL, Jobservice, and Registry, but following similar approach you can also disable PVCs for Trivy and Redis. Do note however that if you want to disable the creation of PVCs you will need to run these services externally. 

For PostgreSQL, if you look at the following line in the StatefulSet file, you can see that the StatefulSet gets created only if you are using internal database.
https://github.com/goharbor/harbor-helm/blob/6c342ac9ef2597c9130e556f13b33832d4faafa0/templates/database/database-ss.yaml#L1
This means that you can configure database parameters and use external database. Example looks something like this:

```yaml
database:
  type: external
  external:
    host: <postgres-server-fqdn>
    port: 5432
    username: <postgres-user>
    existingSecret: <secret-name-with-credentials>
    sslmode: <sslmode>
    coreDatabase: <db-name>
```

Jobservice can store logs in three different ways: file, database, and stdout. By default it is configured to store logs to file which requires additional PVC for jobservice pods. As you can see simlar as with PostgreSQL, the PVC only gets created when jobservice is configured to store logs into the filesystem
https://github.com/goharbor/harbor-helm/blob/6c342ac9ef2597c9130e556f13b33832d4faafa0/templates/jobservice/jobservice-pvc.yaml#L1
Alternatively you can persiste logs from jobservice into the database or you can just output them to the stdout. If you want to store them into the database you have set your values like this:

```yaml
jobservice:
  jobLogger:
    - database
```

Registry can store data into the filesystem or multiple types of blob storages. Again if you look into the templates the PVC only gets created if `imageChartStorage.type` is set to `filesystem`. If you want to S3 or S3 compatible storage like minio you can use configuration similar to this:
```yaml
persistence:
  imageChartStorage:
    type: s3
    s3: 
      region: "minio"
      existingSecret: <secret-name-with-credentials>
      regionendpoint: https://<minio-server-fqdn>
      bucket: harbor
      secure: true
      skipverify: false
    disableredirect: false
```
