### ISSUE TITLE
No way to store the Redis password securely

### ISSUE THREAD

**Issue by BojanZelic** [goharbor/harbor-helm#2136]
Redis Auth password is set in a configmap instead of a Secret.

```
# values.yaml
  redis:
    type: external
    external:
      addr: "harbor-ha-redis-node-0.harbor-ha-redis-headless.harbor.svc.cluster.local:6379..."
      sentinelMasterSet: "mymaster"
      username: ""
      password: "<password_redacted>"
      # If using existingSecret, the key must be REDIS_PASSWORD
      #existingSecret: "test"
```

the `redis.external.existingSecret` param doesn't actually pull the value from the K8s secret, instead it does a helm `lookup` function and ends up storing the password as part of the connection string in the harbor configmap. This causes problems when trying to deploy via argocd as argocd doesn't support helm `lookup`.  

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-core
...
data:
  _REDIS_URL_CORE: "redis+sentinel://:<password_redacted>@harbor-ha-redis-node-0.harbor-ha-redis-headless.harbor.svc.cluster.local:6379..."
```
