### ISSUE TITLE
Argocd issues

### ISSUE THREAD

**Issue by ergoxi** [goharbor/harbor-helm#2139]
Argocd doesn't support helm lookup (https://github.com/argoproj/argo-cd/issues/21745) and this causes it to periodically generate random secret values on sync when using the harbor helm chart.

If you're having issues with harbor and see pods randomly restarting this may be the cause.

Here are some fields that you must set in your harbor values.yaml:
```yaml
  # Note: take a look at the root harbor values.yaml for requirements for these values
  jobservice:
    secret: "" 
  core:
    secret: ""
    tokenKey: |
    tokenCert: |
    xsrfKey: ""
  registry:
    secret: ""
    credentials:
       htpasswdString: ""
```
