### ISSUE TITLE
How to use multiple jobservice replicas?

### ISSUE THREAD

**Issue by hongbo-miao** [goharbor/harbor-helm#2154]
Here is my deployment code:

```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production-hm-harbor
  namespace: production-hm-argo-cd
  labels:
    app.kubernetes.io/name: hm-harbor
spec:
  project: production-hm
  sources:
    - repoURL: https://helm.goharbor.io
      # https://goharbor.io/docs/1.10/install-config/harbor-ha-helm/
      # https://artifacthub.io/packages/helm/harbor/harbor
      targetRevision: 1.16.2
      chart: harbor
      helm:
        releaseName: hm-harbor
        values: |
          # https://github.com/goharbor/harbor-helm/blob/main/values.yaml
          ---
          expose:
            type: ingress
            ingress:
              hosts:
                core: harbor.hongbomiao.com
            tls:
              enabled: false
          externalURL: https://harbor.hongbomiao.com
          existingSecretAdminPassword: hm-harbor-secret
          existingSecretAdminPasswordKey: HARBOR_ADMIN_PASSWORD
          core:
            replicas: 3
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                cpu: 100m
                memory: 256Mi
          jobservice:
            replicas: 3
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                cpu: 100m
                memory: 256Mi
          portal:
            replicas: 3
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                cpu: 100m
                memory: 256Mi
          registry:
            replicas: 3
            registry:
              resources:
                requests:
                  cpu: 50m
                  memory: 128Mi
                limits:
                  cpu: 500m
                  memory: 512Mi
            controller:
              resources:
                requests:
                  cpu: 50m
                  memory: 128Mi
                limits:
                  cpu: 100m
                  memory: 256Mi
          trivy:
            replicas: 1
            resources:
              requests:
                cpu: 200m
                memory: 128Mi
              limits:
                cpu: 500m
                memory: 1Gi
          redis:
            type: internal
            internal:
              resources:
                requests:
                  cpu: 50m
                  memory: 128Mi
                limits:
                  cpu: 100m
                  memory: 256Mi
          persistence:
            enabled: true
            resourcePolicy: keep
            persistentVolumeClaim:
              jobservice:
                jobLog:
                  accessMode: ReadWriteOnce
                  size: 1Gi
                  storageClass: production-hm-harbor-storage-class
              trivy:
                accessMode: ReadWriteOnce
                size: 5Gi
                storageClass: production-hm-harbor-storage-class
              redis:
                accessMode: ReadWriteOnce
                size: 1Gi
                storageClass: production-hm-harbor-storage-class
            imageChartStorage:
              type: s3
              s3:
                region: us-west-2
                bucket: production-hm-harbor-bucket
                existingSecret: hm-harbor-secret
            existingSecretAdminPasswordKey: HARBOR_ADMIN_PASSWORD
          database:
            type: external
            external:
              host: production-hm-harbor-postgres.xxxxxxxxxxxx.us-west-2.rds.amazonaws.com
              port: 5432
              username: harbor_user
              coreDatabase: harbor_db
              existingSecret: hm-harbor-secret
              sslmode: require
    - repoURL: git@github.com:hongbo-miao/hongbomiao.com.git
      targetRevision: main
      path: kubernetes/argo-cd/applications/production-hm/harbor/kubernetes-manifests
  destination:
    namespace: production-hm-harbor
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated:
      prune: true
```

However, when Argo CD applies the changes, I got erro

> Multi-Attach error for volume "pvc-196e63bb-d63e-4db5-ae69-6c82a58d3e31" Volume is already used by pod(s) hm-harbor-jobservice-6b9b7fd455-slscg

This is because I set jobservice replicas to 3, multiple pods try to bind one Persistent Volume and only first one can bind.

I saw in the past there is a similar issue https://github.com/goharbor/harbor-helm/issues/1320 but that one is "fixed" by removing scandata.

Right now the `jobLog` is causing issue, what would be proper way to deploy? Thank you! ☺️
