### ISSUE TITLE
Helm Upgrade to >= 1.13.1 fails with YAML parse error on harbor/templates/core/core-cm.yaml

### ISSUE THREAD

**Issue by Tim-herbie** [goharbor/harbor-helm#2162]
Hello,

I tried to update my harbor helm chart from 1.13.0 to above (e.g. 1.13.1) and it fails. I can´t see any actions that I would to take for an upgrade. I checked the source code too, but can´t see a diff that could explain the error. When I install the helm with 1.13.0, everything works great.

Error message:
```
Error: UPGRADE FAILED: YAML parse error on harbor/templates/core/core-cm.yaml: error converting YAML to JSON: yaml: line 38: did not find expected key
```

Command:
```
helm upgrade --install harbor \
	--namespace=harbor \
	--set externalURL=https://harbor.example.de \
	--set portal.replicas=2 \
	--set core.replicas=2 \
	--set registry.replicas=2 \
	--set trivy.replicas=1 \
	--values harbor-values.yaml \
	--version 1.13.1  \
	harbor/harbor
```

harbor-values file:
```
---
expose:
  type: clusterIP
  tls:
    enabled: false
  updateStrategy:
    type: RollingUpdate
nginx:
  nodeSelector:
    node-role.kubernetes.io/worker: "true"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: In
                values:
                  - "true"
portal:
  nodeSelector:
    node-role.kubernetes.io/worker: "true"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: In
                values:
                  - "true"
core:
  nodeSelector:
    node-role.kubernetes.io/worker: "true"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: In
                values:
                  - "true"
jobservice:
  storageClass: "longhorn"
  accessMode:
    - ReadWriteMany
  nodeSelector:
    node-role.kubernetes.io/worker: "true"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: In
                values:
                  - "true"
registry:
  storageClass: "longhorn"
  accessMode:
    - ReadWriteMany
  nodeSelector:
    node-role.kubernetes.io/worker: "true"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: In
                values:
                  - "true"
trivy:
  storageClass: "longhorn"
  nodeSelector:
    node-role.kubernetes.io/worker: "true"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: In
                values:
                  - "true"
database:
  storageClass: "longhorn"
  type: external
  external:
    host: "harbor-postgres-db.harbor.svc.cluster.local"
    username: "harbor"
    existingSecret: "harbor.harbor-postgres-db.credentials.postgresql.acid.zalan.do"
    sslmode: "require"
  internal:
    nodeSelector:
      node-role.kubernetes.io/worker: "true"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-role.kubernetes.io/worker
                  operator: In
                  values:
                    - "true"
redis:
  storageClass: "longhorn"
  type: "external"
  external:
    addr: "redis.harbor.svc.cluster.local"
    existingSecret: "redis-credentials"
  nodeSelector:
    node-role.kubernetes.io/worker: "true"
  internal:
    nodeSelector:
      node-role.kubernetes.io/worker: "true"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: In
                values:
                  - "true"
exporter:
  nodeSelector:
    node-role.kubernetes.io/worker: "true"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: In
                values:
                  - "true"
persistence:
  persistentVolumeClaim:
    registry:
      existingClaim: "harbor-registry"
```
