### ISSUE TITLE
ArgoCD unable to sync due to missing PVC properties

### ISSUE THREAD

**Issue by drewhemm** [goharbor/harbor-helm#2174]
Children of `volumeClaimTemplates` for Redis, Trivy and Database are missing the manifest properties `apiVersion` and `kind`. Kubernetes adds these by default and ArgoCD constantly tries to remove them, making it unable to sync.

Symptoms:
![image](https://github.com/user-attachments/assets/e425e5c0-2048-44d2-8011-4e1ba3b74173)
![image](https://github.com/user-attachments/assets/13272399-315a-4566-8203-75be5dcb48af)

Cause:
![image](https://github.com/user-attachments/assets/a8708d4b-4f3d-474e-823f-db731312d5b1)

Fix: see [Files changed](https://github.com/goharbor/harbor-helm/pull/2173/files).

**Comment by drewhemm** [comment]
Proposed fix: https://github.com/goharbor/harbor-helm/pull/2173

**Comment by drewhemm** [comment]
Here is a temporary workaround while we wait for the PR to be approved and merged:

```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
spec:
  destination:
    namespace: harbor
    server: https://kubernetes.default.svc
  # Temporarily ignore differences in StatefulSet volumeClaimTemplates
  # apiVersion and kind fields to avoid issues with the Harbor chart.
  # Remove once this PR is merged: https://github.com/goharbor/harbor-helm/pull/2173
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jqPathExpressions:
      - .spec.volumeClaimTemplates[].apiVersion
      - .spec.volumeClaimTemplates[].kind
```

![Image](https://github.com/user-attachments/assets/c1e26c9a-7790-4b10-af3f-49021df9df7a)
