### ISSUE TITLE
Harbor 2.13 - Jobservice PVC does not bond

### ISSUE THREAD

**Issue by blindshare** [goharbor/harbor-helm#2200]
Hi all. 
Im running k8s 1.33.1 on Ubuntu Server 24.04

I tried installing harbor via helm but it failed out-of-the box. The reason is missing PV's. 
Now since I (at the moment) lack a storage server, I decided to manually create some local-storage PV's
Unfortunately this is not a simple task as harbor expects certain "names" for its PVC. Otherwise the PVC will not bond to its PV.
So I decided to create a separate StorageClass that is capable of creating PV's automatically

```
kind: StorageClass
metadata:
  name: local-storage
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Retain
```
And this is my harbor-values.yaml

```
expose:
  type: nodePort
  tls:
    enabled: true
    auto:
      commonName: harbor.local
    secretName: harbor-tls
    notarySecretName: notary-tls
  nodePort:
    ports:
      http:
        port: 80
        nodeport: 30080
      https:
        port: 443
        nodePort: 30443
      notary:
        port: 4443
        nodePort: 30444

externalURL: https://harbor.local:30443

# Explizite TLS-Konfiguration für alle Komponenten
nginx:
  tls:
    enabled: true

persistence:
  enabled: true
  persistentVolumeClaim:
    registry:
      size: 20Gi
      storageClass: local-storage
    database:
      size: 10Gi
      storageClass: local-storage
    redis:
      size: 5Gi
      storageClass: local-storage
    # A bug in the current helm template ignores the global 'persistence.persistentVolumeClaim.jobservice', size config and assignes no StorageClass !
    # To solve the issue disable the global PVC setting below and modify the "persistence:" settings in the Jobservice section
    # jobservice:
    #  size: 5Gi
    #  storageClass: local-storage
    trivy:
      size: 10Gi
      storageClass: local-storage

# Initiale Admin-Anmeldedaten
harborAdminPassword: "XXXXXXXX"

# Redis mit NodeAffinity und Tolerations
redis:
  type: internal
  internal:
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 500m
    nodeSelector:
      kubernetes.io/hostname: k8s-control
    tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule

# Trivy Scanner Konfiguration
trivy:
  enabled: true
  nodeSelector:
    kubernetes.io/hostname: k8s-control
  tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule

# NodeAffinity und Tolerations für alle Harbor-Komponenten
# Alle Pods auf Control-Plane Node schedulen
core:
  nodeSelector:
    kubernetes.io/hostname: k8s-control
  tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule

portal:
  nodeSelector:
    kubernetes.io/hostname: k8s-control
  tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule

registry:
  registry:
    nodeSelector:
      kubernetes.io/hostname: k8s-control
    tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
  controller:
    nodeSelector:
      kubernetes.io/hostname: k8s-control
    tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule

database:
  internal:
    nodeSelector:
      kubernetes.io/hostname: k8s-control
    tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule

jobservice:
  persistence:
    enabled: true
    storageClass: "local-storage"
    size: 5Gi
  nodeSelector:
    kubernetes.io/hostname: k8s-control
  tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule

nginx:
  nodeSelector:
    kubernetes.io/hostname: k8s-control
  tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule
```

As you can see I already modified the "Jobservice" part, but still all these settings are getting ignored !
```
kubectl get pv,pvc -n harbor-system
NAME                                                        CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                           STORAGECLASS    VOLUMEATTRIBUTESCLASS   REASON   AGE
persistentvolume/pvc-24ec0374-0346-40fa-bd68-46c06fb219df   10Gi       RWO            Retain           Bound    harbor-system/database-data-harbor-database-0   local-storage   <unset>                          18m
persistentvolume/pvc-a8d863ce-89bd-42f5-9200-6d3cff6fdde5   10Gi       RWO            Retain           Bound    harbor-system/data-harbor-trivy-0               local-storage   <unset>                          18m
persistentvolume/pvc-e8694d27-416a-424b-b653-888967364b2f   20Gi       RWO            Retain           Bound    harbor-system/harbor-registry                   local-storage   <unset>                          18m
persistentvolume/pvc-f98e506b-1da0-43dd-8327-ae52a8b57d6c   5Gi        RWO            Retain           Bound    harbor-system/data-harbor-redis-0               local-storage   <unset>                          18m

NAME                                                    STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS    VOLUMEATTRIBUTESCLASS   AGE
persistentvolumeclaim/data-harbor-redis-0               Bound     pvc-f98e506b-1da0-43dd-8327-ae52a8b57d6c   5Gi        RWO            local-storage   <unset>                 18m
persistentvolumeclaim/data-harbor-trivy-0               Bound     pvc-a8d863ce-89bd-42f5-9200-6d3cff6fdde5   10Gi       RWO            local-storage   <unset>                 18m
persistentvolumeclaim/database-data-harbor-database-0   Bound     pvc-24ec0374-0346-40fa-bd68-46c06fb219df   10Gi       RWO            local-storage   <unset>                 18m
persistentvolumeclaim/harbor-jobservice                 Pending                                                                                        <unset>                 18m
persistentvolumeclaim/harbor-registry                   Bound     pvc-e8694d27-416a-424b-b653-888967364b2f   20Gi       RWO            local-storage   <unset>                 18m
```
The Jobservice Pod will remain in "pending" state as no PVC can bond. For some reason the PV doesn't get created

**Comment by MinerYang** [comment]
jobservice persistent config in values.yaml should looks like this
https://github.com/goharbor/harbor-helm/blob/ac65d7b4d6dd5f42b0e1521be2c488bc1663b1c4/values.yaml#L141C5-L148C24
```
 jobservice:
    jobLog:
       existingClaim: ""
       storageClass: ""
       subPath: ""
       accessMode: ReadWriteOnce
       size: 1Gi
       annotations: {}
```
