### ISSUE TITLE
ArgoCD created manifests missing values

### ISSUE THREAD

**Issue by MaroIT** [goharbor/harbor-helm#2203]
I tried to deploy Harbor helm chart using ArgoCD and configured values.yaml as below:

```yaml
expose:
  type: ingress

  tls:
    enabled: true
    certSource: secret
    secret:
      secretName: engemaro-tls

  ingress:
    hosts:
      core: harbor.engemaro.com
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
    className: ""
externalURL: "https://harbor.engemaro.com"
persistence:
  enabled: true
  resourcePolicy: keep
  persistentVolumeClaim:
    registry:
      storageClass: local-path
      subPath: ""
      accessMode: ReadWriteOnce
      size: 5Gi
    jobservice:
      jobLog:
        storageClass: local-path
        subPath: ""
        accessMode: ReadWriteOnce
        size: 1Gi
    database:
      storageClass: local-path
      subPath: ""
      accessMode: ReadWriteOnce
      size: 1Gi
    redis:
      storageClass: local-path
      subPath: ""
      accessMode: ReadWriteOnce
      size: 1Gi
    trivy:
      storageClass: local-path
      accessMode: ReadWriteOnce
      size: 5Gi

  imageChartStorage:
    type: filesystem
    filesystem:
      rootdirectory: /storage
harborAdminPassword: "<REDACTED>"
internalTLS:
  enabled: false
core:
  extraEnvVars: []
  nodeSelector: {}
  tolerations: {}
  affinity: {}
jobservice:
  extraEnvVars: []
  nodeSelector: {}
  tolerations: {}
  affinity: {}
registry:
  credentials:
    #existingSecret: "harbor-registry-htpasswd"
    htpasswdString: "<REDACTED>"
  relativeurls: false

  extraEnvVars: []
  nodeSelector: {}
  tolerations: {}
  affinity: {}
redis:
  type: internal
  extraEnvVars: []
  nodeSelector: {}
  tolerations: {}
  affinity: {}
database:
  type: internal
  internal:
    password: "<REDACTED>"
    shmSizeLimit: 512Mi
    extraEnvVars: []
    nodeSelector: {}
    tolerations: {}
    affinity: {}
trivy:
  enabled: true
  # extraEnvVars: []
  # nodeSelector: {}
  # tolerations: {}
  # affinity: {}
metrics:
  enabled: false
  core:
    path: /metrics
    port: 8001
  registry:
    path: /metrics
    port: 8001
  jobservice:
    path: /metrics
    port: 8001
  exporter:
    path: /metrics
    port: 8001
  serviceMonitor:
    enabled: true
```

Even tho I can see them in ArgoCD UI, so Argo reads them properly, they are not implemented in manifests, that leaded to missing `storageClass` parameters in manifests or even not reading host for ingress :/ I have checked and looks like values.yaml is properly configured, but maybe you will find something.

![Image](https://github.com/user-attachments/assets/37b7a73d-9890-4cb1-b2a1-234b7c529008)

![Image](https://github.com/user-attachments/assets/f22b962b-ce26-408f-8b83-5b57a6623d42)

![Image](https://github.com/user-attachments/assets/39672b81-a58a-40bd-80a5-d16ab93c012a)
