### ISSUE TITLE
FATAL:  no pg_hba.conf entry for host "192.168.5.148", user "postgres", database "postgres", SSL off

### ISSUE THREAD

**Issue by lizhongit** [goharbor/harbor-helm#251]
My Env:

Helm: v.2.13.1 (Client/Server)
Kubernetes: v1.14.0

values.yaml

```yaml
expose:
  
  type: "ingress"
  tls:
    enabled: true
  
  ingress:
    hosts:
      core: "docker.niz.com"
      notary: "notary.niz.com"

  annotations:
    kubernetes.io/ingress.class: "traefik"
    ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/proxy-body-size: "0"



persistence:
  persistentVolumeClaim:
    registry:
      existingClaim: "harbor-registry-pvc"


    chartmuseum:
      existingClaim: "harbor-chartmuseum-pvc"

  
    jobservice:
      existingClaim: "harbor-jobservice-pvc"
    

    database: 
      existingClaim: "harbor-database-pvc"


    redis:
      existingClaim: "harbor-redis-pvc"


externalURL: "https://docker.niz.com"

secretkey: "ccZUtrWDjsiDtqMq"

core:
  secret: "82T4IWwwnlViaCif" 


jobservice:
  secret: "xic6g1fXe0Tt0Hgp"


registry:
  secret: "kStcajBupZcQubDC"


Notary:
  enabled: true
```

Got pod status after helm install a few minutes
```shell
node4 harbor # kubectl get po -n harbor                       
NAME                                           READY   STATUS             RESTARTS   AGE
harbor-harbor-chartmuseum-74f6b6fbc9-nksx5     1/1     Running            0          7m36s
harbor-harbor-clair-7c795c87c4-f6h5z           0/1     CrashLoopBackOff   28         123m
harbor-harbor-core-796f8775dd-dhlzd            0/1     CrashLoopBackOff   7          7m36s
harbor-harbor-core-847db59f-xqwgd              0/1     CrashLoopBackOff   9          22m
harbor-harbor-database-0                       0/1     Running            32         123m
harbor-harbor-jobservice-65f6cf8c88-n4fw9      0/1     Running            36         123m
harbor-harbor-notary-server-6f77b5d74-5xktb    0/1     CrashLoopBackOff   5          7m8s
harbor-harbor-notary-signer-5db8bc79c5-pwmbg   0/1     CrashLoopBackOff   5          7m8s
harbor-harbor-portal-74dff88588-4tngk          1/1     Running            0          123m
harbor-harbor-redis-0                          1/1     Running            0          123m
harbor-harbor-registry-648578844d-2cp4t        2/2     Running            0          7m36s
```

I got logs from named harbor-harbor-database-0 of pod:

```shell
LOG:  could not create IPv6 socket: Address family not supported by protocol
FATAL:  the database system is starting up
LOG:  database system was shut down at 2019-06-05 09:48:04 UTC
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
FATAL:  no pg_hba.conf entry for host "192.168.5.148", user "postgres", database "postgres", SSL off
FATAL:  no pg_hba.conf entry for host "192.168.5.148", user "postgres", database "postgres", SSL off
```

Am I missing something for it?
