### ISSUE TITLE
expose.tls.secretName try to volume mount to core pod

### ISSUE THREAD

**Issue by Hokwang** [goharbor/harbor-helm#261]
Hi,

I have local kubernetes 

I want to use ingress with tls enabled.

I guess here's the problem.

When I use tls in ingress,
```
kubectl create namespace ingress-nginx
kubectl create secret tls ingress-tls --key key.pem --cert cert.pem -n ingress-nginx
helm install stable/nginx-ingress -n ingress-nginx-harbor --namespace ingress-nginx -f ingress-nginx-harbor-values.yaml
```

ingress-nginx-harbor-values.yaml is
```
controller:
  extraArgs:
    default-ssl-certificate: "ingress-nginx-prod/ingress-tls"
<snip>
```

and my values.yaml for harbor is
```
expose:
  type: ingress
  tls:
    enabled: true
    secretName: "ingress-tls"
  ingress:
    hosts:
      core: harbor.sec
<snip>
```
and then run 
```helm install harbor/harbor -n harbor --namespace harbor -f harbor-values.yaml```

Here's an error.
```
# kubectl describe pod/harbor-harbor-core-69d55875f5-cd6gk -n harbor
Events:
  Type     Reason       Age                  From                  Message
  ----     ------       ----                 ----                  -------
  Warning  FailedMount  105s (x5 over 113s)  kubelet, host  MountVolume.SetUp failed for volume "ca-download" : secret "ingress-tls" not found
  Normal   Scheduled    15s                  default-scheduler     Successfully assigned harbor/harbor-harbor-core-69d55875f5-cd6gk to host
```
few minutes later,
```
Warning  FailedMount  3m27s                  kubelet, host  Unable to mount volumes for pod "harbor-harbor-core-69d55875f5-cd6gk_harbor(22ba4fd1-90f0-11e9-ad13-246e966fb6cc)": timeout expired waiting for volumes to attach or mount for pod "harbor"/"harbor-harbor-core-69d55875f5-cd6gk". list of unmounted volumes=[ca-download]. list of unattached volumes=[config secret-key token-service-private-key ca-download psc default-token-n6bhw]
```

This related with core-dpl.yaml 
https://github.com/goharbor/harbor-helm/blob/8420734bb0e8d9f8e760e60b8933ccef58c023ed/templates/core/core-dpl.yaml#L111-L123

I don't understand why core need ca cert and why use ingress's!
and the secret does not have ca.crt as you know.

Now work-around is 
```kubectl create secret generic ingress-tls --from-file=ca.crt=cacerts -n harbor```
create(extract) cacerts file manually and 
create same name secret forcely.

Thanks.
