### ISSUE TITLE
some pvc does not delete when using helm delete --purge

### ISSUE THREAD

**Issue by Hokwang** [goharbor/harbor-helm#268]
Hi,

I install harbor using helm chart.

```
# helm install harbor/harbor -n harbor-stage --namespace harbor-stage -f harbor-stage-values.yaml
...
==> v1/PersistentVolumeClaim
NAME                             STATUS   VOLUME                                    CAPACITY  ACCESS MODES  STORAGECLASS  AGE
harbor-stage-harbor-chartmuseum  Pending  nfs-client-stage                          <invalid>
harbor-stage-harbor-jobservice   Bound    pvc-4301002a-9413-11e9-ad13-246e966fb6cc  2Gi   RWO  nfs-client-stage  <invalid>
harbor-stage-harbor-registry     Bound    pvc-43019166-9413-11e9-ad13-246e966fb6cc  20Gi  RWO  nfs-client-stage  <invalid>
```

my values.yaml is
```
<snip>
persistence:
  enabled: true
  resourcePolicy: ""
  persistentVolumeClaim:
    registry:
      storageClass: "nfs-client-stage"
      size: 20Gi
    chartmuseum:
      storageClass: "nfs-client-stage"
      size: 10Gi
    jobservice:
      storageClass: "nfs-client-stage"
      size: 2Gi
    database:
      storageClass: "nfs-client-stage"
    redis:
      storageClass: "nfs-client-stage"
      size: 2Gi
<snip>
```

and then, run ```# helm delete --purge harbor-stage``` command.

after few seconds, there's two pvc is not deleted still.
```
# k get pvc -n harbor-stage
NAME                                           STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS       AGE
data-harbor-stage-harbor-redis-0               Bound    pvc-22b542d8-940e-11e9-ad13-246e966fb6cc   2Gi        RWO            nfs-client-stage   36m
database-data-harbor-stage-harbor-database-0   Bound    pvc-22b021e8-940e-11e9-ad13-246e966fb6cc   1Gi        RWO            nfs-client-stage   36m
```

and these did not be shown in helm status list first, 
and these naming rule is different with others.

Thanks.

**Comment by Zenon1991** [comment]
This is not a problem, this is a feature :) I guess that that the reclaim policy is set to "Retain" in your storageclass. If you delete your deployment, the pvc still bounds the volume. 

If you want to delete the PVCs:
```
kubectl delete pvc data-harbor-stage-harbor-redis-0
kubectl delete pvc database-data-harbor-stage-harbor-database-0
```


If you want that the pvcs get deleted automatically you need to change the reclaimPolicy to "Delete" in the storageclass.yaml, e.g.:

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: rook-ceph-block
provisioner: ceph.rook.io/block
parameters:
  blockPool: replicapool
  # The value of "clusterNamespace" MUST be the same as the one in which your rook cluster exist
  clusterNamespace: rook-ceph-system
  # Specify the filesystem type of the volume. If not specified, it will use `ext4`.
# Optional, default reclaimPolicy is "Delete". Other options are: "Retain", "Recycle" as documented in https://kubernetes.io/docs/concepts/storage/storage-classes/
reclaimPolicy: Delete
```
