### ISSUE TITLE
secret mount error

### ISSUE THREAD

**Issue by x893675** [goharbor/harbor-helm#292]
hi

i have k8s 1.11 and helm 2.14.2

my values.yaml for harbor is
```yaml
expose:
  type: nodePort
  tls:
    enabled: false
  nodePort:
    name: harbor
    ports:
      http:
        port: 80
        nodePort: 30002
      https:
        port: 443
        nodePort: 30003
      notary:
        port: 4443
        nodePort: 30004

persistence:
  enabled: false

notary:
  enabled: false
```

Here's an error:
`Error: failed to create subPath directory for volumeMount "secret-key" of container "core"`

This related with deployment harbor-core.yaml
```yaml
     volumeMounts:
        - mountPath: /etc/core/app.conf
          name: config
          subPath: app.conf
        - mountPath: /etc/core/key
          name: secret-key
          subPath: key
        - mountPath: /etc/core/private_key.pem
          name: token-service-private-key
          subPath: tls.key
        - mountPath: /etc/core/token
          name: psc
      volumes:
      - configMap:
          defaultMode: 420
          name: harbor-harbor-core
        name: config
      - name: secret-key
        secret:
          defaultMode: 420
          items:
          - key: secretKey
            path: key
          secretName: harbor-harbor-core
      - name: token-service-private-key
        secret:
          defaultMode: 420
          secretName: harbor-harbor-core
      - emptyDir: {}
        name: psc
```

Kindly help me in this regard.
 thanks!
