### ISSUE TITLE
helm add chartrepo error

### ISSUE THREAD

**Issue by kenwoodjw** [goharbor/harbor-helm#308]
```
helm repo add --ca-file ca.crt     --username admin --password Harbor12345 hub  https://registry.qikqiak.com/chartrepo/test-chart                                                                                     
```
```
Error: Looks like "https://registry.qikqiak.com/chartrepo/test-chart" is not a valid chart repository or cannot be reached: Get https://registry.qikqiak.com/chartrepo/test-chart/index.yaml: x509: certificate is valid for ingress.local, not registry.qikqiak.com
```
this is my values.yaml
```
expose:
  type: ingress
  tls:
    enabled: true
  ingress:
    hosts:
      core: registry.qikqiak.com
      notary: notary.qikqiak.com
    annotations:
      kubernetes.io/ingress.class: "traefik"
      ingress.kubernetes.io/ssl-redirect: "true"
      ingress.kubernetes.io/proxy-body-size: "0"
externalURL: https://registry.qikqiak.com

persistence:
  enabled: true
  resourcePolicy: "keep"
  persistentVolumeClaim:
    registry:
      storageClass: "harbor-data"
    chartmuseum:
      storageClass: "harbor-data"
    jobservice:
      storageClass: "harbor-data"
    database:
      storageClass: "harbor-data"
    redis:
      storageClass: "harbor-data"
```
the ca file is secret of ingress 
docker login is fine. Can anyone tell what is problem ?
