### ISSUE TITLE
Redirect HTTP request to HTTPS request failed with updated nodePort value for values.yaml

### ISSUE THREAD

**Issue by uddmorningsun** [goharbor/harbor-helm#312]
```
[root@dx-app2 harbor]# wget https://github.com/goharbor/harbor-helm/archive/v1.1.1.tar.gz
```

If I don't use default nodePort values(30002, 30003) provided by `values.yaml`, request HTTP will be failed and then produces redirecting error(see https://img.vim-cn.com/5f/ecfdb97cfd5278dcdcfddd8598aab98f7f9e02.png ) (browser dev-tools opened persistent log options). I also try Chrome browser to request the same URL, it will produce the same results

```
[root@dx-app2 harbor-helm-1.1.1]# hostname -I 
10.150.7.178 172.17.0.1 172.18.0.1 

[root@dx-app2 harbor-helm-1.1.1]# ls
cert  Chart.yaml  CONTRIBUTING.md  docs  LICENSE  myvalues.yaml  README.md  templates  values.yaml
[root@dx-app2 harbor-helm-1.1.1]# helm install --name my-harbor --wait --debug -f ./myvalues.yaml .

[root@dx-app2 harbor-helm-1.1.1]# cat myvalues.yaml 
expose:
  type: nodePort
  tls:
    enabled: true
    commonName: "10.150.7.178"
  nodePort:
    ports:
      http:
        nodePort: 31980
      https:
         nodePort: 31990
externalURL: https://10.150.7.178:31990
persistence:
  enabled: false
```

All related pods are healthy, nodePort info:

```
[root@dx-app2 harbor-helm-1.1.1]# k get svc | grep harbor
harbor                           NodePort    10.101.83.8      <none>        80:31980/TCP,443:31990/TCP,4443:30004/TCP   8m

... ...

[root@dx-app2 harbor-helm-1.1.1]# curl -L http://10.150.7.178:31980
curl: (7) Failed connect to 10.150.7.178:443; Connection refused
```

If I use default nodePort values(30002, 30003), request HTTP is OK, but it doesn't redirect HTTP request to HTTPS. `myvalues.yaml`:

```
expose:
  type: nodePort
  tls:
    enabled: true
    commonName: "10.150.7.178"
externalURL: https://10.150.7.178:30003
persistence:
  enabled: false
```

```
[root@dx-app2 harbor-helm-1.1.1]# helm install --name my-harbor --wait --debug -f ./myvalues.yaml .  

[root@dx-app2 harbor-helm-1.1.1]# k get svc | grep harbor
harbor                           NodePort    10.106.64.172    <none>        80:30002/TCP,443:30003/TCP,4443:30004/TCP   3m

... ...
```

https://img.vim-cn.com/9c/53b61e008d956c15716637080695af6f605cb5.png
