### ISSUE TITLE
MountVolume.SetUp failed for volume "ca-download" : references non-existent secret key

### ISSUE THREAD

**Issue by zlingqu** [goharbor/harbor-helm#315]
When I deploy key and CRT with trusted ca, the core module cannot be started.
 I think the ./templates/core/core-dpl.yaml file fixes that there must be ca.crt and ca.key in secretname.

My configuration file is as follows
```
type: ingress
  tls:
    enabled: true
    secretName: "https-key-secret"
    notarySecretName: ""
```

I user traefik-ingress.

The following error appears when using kubectl describe pod

![image](https://user-images.githubusercontent.com/41672611/62836052-cef5b600-bc91-11e9-90b3-62c505fbeed8.png)
