### ISSUE TITLE
missing notarySecretName leads to cert-manager looping

### ISSUE THREAD

**Issue by Sayrus** [goharbor/harbor-helm#365]
Using this tls configuration will lead to cert-manager looping:
```yaml
expose:
  type: "ingress"
  ingress:
    hosts:
      core: "my-core-host"
  tls:
    enabled: true
    secretName: harbor-tls
```

The reason is the following Ingress which uses twice the same secret name on different hosts:
```
    tls:
    - hosts:
      - my-core-host
      secretName: harbor-tls
    - hosts:
      - notary.harbor.domain
      secretName: harbor-tls
```

**Current behavior:**
Harbor is "healthy", cert-manager hang permanently on "certificate already exist" as it tries to create two instances.
As the certificate is never generated, harbor is never accessible.

This behavior is only valid if a certificate with an alternative name can be created. This seems like a strange thing to ask from an automated certificate manager. (Whether it is cert-manager or something else)

**Expected behavior:**
- Creation should fail as the ingress configuration is usually invalid
- Print a warning as a comment if the behavior is "expected" 
- Maybe we shouldn't autofill notary with `$tls.secretName`
```
    {{- if $tls.notarySecretName }}
  - secretName: {{ $tls.notarySecretName }}
    {{- else if $tls.secretName }}
  - secretName: {{ $tls.secretName }}
    {{- else }}
  - secretName: "{{ template "harbor.ingress" . }}"
    {{- end }}
```

I'm not sure this is intended, but if the behavior is expected:
- The same switch should exists for `core` with a variable `coreSecretName` so that it is less of a pitfall

Of course, part of the problem is due to cert-manager not handling two hosts with the same secret name correctly (he should fail with an explicit error message or, if he could, generate a certificate with an alternative name).
