### ISSUE TITLE
feature request: support portal look and feel customization

### ISSUE THREAD

**Issue by wu105** [goharbor/harbor-helm#418]
Harbor the application offers look and feel customization, see https://github.com/goharbor/harbor/blob/master/docs/customize_look%26feel_guide.md

It seems that it can be done by overriding /usr/share/nginx/html/setting.json in the portal image and add a couple of image files to /usr/share/nginx/html/images.

Can we add configuration values that would configure the the portal deployment manifest for look and feel customization?   It could be done by using a configure map to override the setting.json and add image files via volume mounts.

**Comment by ywk253100** [comment]
@wu105 Sorry for the late reply. The documentation https://github.com/goharbor/harbor/blob/master/docs/customize_look%26feel_guide.md provides a way for users to customize the UI in the development view, as mentioned in the guide, re-build is needed to make it work. We don’t provide any configuration for that both on docker-compose installation or helm chart one currently.

Provide the configuration means we should cover the feature in the testing(automation or manually), that isn’t a few lines of codes, it means a lot of efforts. So we would not support it until many community users really need it. Thanks for your understanding

So probably, building your own portal image is an another solution for you

**Comment by wu105** [comment]
Please see https://github.com/goharbor/harbor/issues/5329 that seems confirm that customizing look and feel does NOT need a rebuild.

I also tested that no rebuild is necessary, although the document would need updating, see https://github.com/goharbor/harbor/issues/9669 .

We customized the look and feel, after installing using helm, by modifying the deployment manifest of Harbor Portal, adding volumes and  mounts similar to #393.  In effect, we simply appended the following:
```
        volumeMounts:
        - mountPath: /usr/share/nginx/html/setting.json
          name: lookandfeel
          subPath: setting.json
        - mountPath: /usr/share/nginx/html/images/harbor-logo.svg
          name: lookandfeel
          subPath: harbor-logo.svg
        - mountPath: /usr/share/nginx/html/static/images/my-logo.svg
          name: lookandfeel
          subPath: my-logo.svg
        - mountPath: /usr/share/nginx/html/static/images/my-bg-pattern.svg
          name: lookandfeel
          subPath: my-bg-pattern.svg
        - mountPath: /usr/share/nginx/html/favicon.ico
          name: lookandfeel
          subPath: favicon.ico
      volumes:
      - configMap:
          defaultMode: 420
          name: harborlookandfeel
        name: lookandfeel
```
For completeness, here is the configure map:
```
kubectl create configmap  harborlookandfeel --from-file=harbor-logo.svg=lookandfeel/my-icon-pattern.svg --from-file=my-logo.svg=lookandfeel/my-logo-empty.svg --from-file=my-bg-pattern.svg=lookandfeel/my-bg-pattern.svg --from-file=setting.json=lookandfeel/setting.json --from-file=favicon.ico=lookandfeel/my-little.ico
```
and the setting.json:
```
{
  "headerBgColor": "rgb(207,0,0)",
  "headerLogo": "my-logo.svg",
  "loginBgImg": "my-bg-pattern.svg",
  "appTitle": "Docker Image and Helm Chart Repository",
  "projects": "Repo",
  "project": {
    "companyName": "My Company",
    "projectName": "DEVOPS",
    "introduction": {
      "zh-cn": "",
      "es-es": "",
      "en-us": "My Company Docker Image and Helm Chart for DEVOPS"
    }
  }
}
```

It would be nice if you could add those extra volumes and mounts sections to the values. The generated manifests will be the same if the user does not specify the extra volume mounts, and you do not need to support or test it other than make sure that the yaml is formed properly if the user do supply the extra volumes and mounts.  We would be happy to construct the volumes, mounts, arrange for the configmap, compose the setting.json, etc., on our own -  It is much more desirable to make the modification via helm.  Hopefully this is not much of work for you and you can reconsider.
