### ISSUE TITLE
The database service crash on startup with "initdb: cannot be run as root"

### ISSUE THREAD

**Issue by beshkenadze** [goharbor/harbor-helm#490]
**Chart version:** 1.3.0

Full log:

> initdb: cannot be run as root
> Please log in (using, e.g., "su") as the (unprivileged) user that will
> own the server process.

Values:

```
---
  database: 
    external: 
      password: "redacted"
    internal: 
      password: "redacted"
  expose: 
    ingress: 
      hosts: 
        core: "harbor-core.domain.com"
        notary: "harbor-notary.domain.com"
    tls: 
      notarySecretName: "wildcard"
      secretName: "wildcard"
  externalURL: "harbor.domain.com"
  harborAdminPassword: "redacted"
  persistence: 
    persistentVolumeClaim: 
      registry: 
        size: "15Gi"
  redis: 
    external: 
      password: "redacted"
  secretkey: "redacted"
  uaaSecretName: "wildcard"
```
