### ISSUE TITLE
harbor-ui: "failed to authenticate harbor: Failed to authenticate user:

### ISSUE THREAD

**Issue by mikelnick** [goharbor/harbor-helm#50]
Full disclosure - I'm not using helm but trying to convert this repo to bend to how we deploy to kubernetes. I am using the tag 0.3 as a guide.  I'm relying on kube dns for inter component connectivity.

I am very close, but a key component isn't working for me - harbor actually connecting to the registry pod.  I have my own nginx pod running too to allow connection to the UI from outside my cluster.  This appears to also be complicating my set up.  I'm just looking for some guidance on these items because I've re-read the documentation serveral times and am missing something.

Logs from UI Container Starting, which 3 things jump out at me and I'm not sure where to correct:
```
Start ui
2018-09-24T23:18:09Z [INFO] Config path: /etc/ui/app.conf
2018-09-24T23:18:09Z [INFO] initializing configurations...
2018-09-24T23:18:09Z [INFO] key path: /etc/ui/key
2018-09-24T23:18:09Z [INFO] initializing client for adminserver http://harbor-adminserver.svc.cluster.local:8080 ...
2018-09-24T23:18:09Z [INFO] initializing the project manager based on local database...
2018-09-24T23:18:09Z [INFO] configurations initialization completed
2018-09-24T23:18:09Z [INFO] Registering database: type-PostgreSQL harbor.rds.amazonaws.com port-5432 databse-harbor sslmode-"disable"
2018-09-24T23:18:09Z [INFO] Register database completed
2018-09-24T23:18:09Z [INFO] User id: 1 already has its encrypted password.
2018-09-24T23:18:09Z [INFO] Enable redis cache for chart caching
2018-09-24T23:18:09Z [INFO] API controller for chart repository server is successfully initialized
2018-09-24T23:18:09Z [INFO] Policy scheduler start at 2018-09-24T23:18:09Z
2018-09-24T23:18:09Z [INFO] initialized clair database
2018-09-24T23:18:09Z [INFO] Handle notification with topic 'scan_all_policy': notifier.ScanPolicyNotification{Type:"daily", DailyTime:0}
2018-09-24T23:18:09Z [INFO] Policy Alternate Policy is scheduled
2018-09-24T23:18:09Z [INFO] Policies:1, Tasks:0, CompletedTasks:0, FailedTasks:0
2018-09-24T23:18:09Z [INFO] Waiting for -83880 seconds after comparing offset 0 and utc time 83880
2018-09-24T23:18:09Z [INFO] Start syncing repositories from registry to DB... 
2018-09-24T23:18:09Z [ERROR] [utils.go:45]: 401 {"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"registry","Class":"","Name":"catalog","Action":"*"}]}]}
2018-09-24T23:18:09Z [ERROR] [main.go:168]: 401 {"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"registry","Class":"","Name":"catalog","Action":"*"}]}]}
2018-09-24T23:18:09Z [INFO] Init proxy
2018/09/24 23:18:09 [I] [asm_amd64.s:2337] http server Running on http://:8080
2018-09-24T23:20:00Z [WARNING] Not found an entry.
2018-09-24T23:20:02Z [ERROR] [security.go:211]: failed to authenticate harbor: Failed to authenticate user, due to error 'Not found an entry'
2018-09-24T23:20:02Z [WARNING] Not found an entry.
2018-09-24T23:20:04Z [ERROR] [security.go:211]: failed to authenticate harbor: Failed to authenticate user, due to error 'Not found an entry'
```
1. 401 on connection to registry pod
2. Running on http://:8080 - seems like the ui dns needs to be specified
3. failed to authenticate harbor: Failed to authenticate user, due to error Not found an entry

Here is my service and deployment file for ui 
```
---
apiVersion: v1
kind: Service
metadata:
  name: "harbor-ui"
  namespace: ournamespace
  labels:
    name: "harbor-ui"
    dns_zone: "{{ dns_zone }}"
spec:
  ports:
    - name: http
      port: 8080
      nodePort: 0
      protocol: TCP
  type: NodePort
  selector:
    name: "harbor-ui"
    sha: "{{ docker_version[0:7] }}"

---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: "harbor-ui-{{ docker_version[0:7] }}"
  namespace: ournamespace
  labels: 
    app: harbor-ui
    sha: "{{ docker_version[0:7] }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: "harbor-ui"
        sha: "{{ docker_version[0:7] }}"
    spec:
      containers:
        - name: "harbor-ui"
          image: "ourreg/harbor-ui:{{ docker_version }}"
          env:
            - name: UI_SECRET
              valueFrom:
                secretKeyRef:
                  name: harbor-config
                  key: harbor-ui-secret
            - name: JOBSERVICE_SECRET
              valueFrom:
                secretKeyRef:
                  name: harbor-config
                  key: harbor-jobservice-secret
            - name: _REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: harbor-config
                  key: harbor-redis-url
            - name: GODEBUG
              value: netdns=cgo
            - name: LOG_LEVEL
              value: info
            - name: CONFIG_PATH
              value: /etc/ui/app.conf
            - name: ENABLE_HARBOR_SCAN_ON_PUSH
              value: "1"
            - name: ADMINSERVER_URL
              value: "http://harbor-adminserver.svc.cluster.local:8080"
            - name: CHART_CACHE_DRIVER
              value: "redis"
            - name: secretKey
              valueFrom:
                secretKeyRef:
                  name: harbor-config
                  key: harbor-secretKey
            - name: secret
              valueFrom:
                secretKeyRef:
                  name: harbor-config
                  key: harbor-secret
            - name: tokenServiceRootCertBundle
              valueFrom:
                secretKeyRef:
                  name: harbor-certs
                  key: root.crt
            - name: tokenServicePrivateKey
              valueFrom:
                secretKeyRef:
                  name: harbor-certs
                  key: private_key.pem
            - name: WITH_CLAIR
              value: "true"
            - name: CLAIR_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: harbor-config
                  key: harbor-clair-pgsql-host
            - name: CLAIR_DB_PORT
              value:  "5432"
            - name: CLAIR_DB_USERNAME
              value: "harborclair"
            - name: CLAIR_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: harbor-config
                  key: harbor-clair-db-password
            - name: CLAIR_DB
              value: "harborclair"
            - name: CLAIR_URL
              value: "http://harbor-clair.svc.cluster.local:6060"
            - name: CLAIR_DB_SSLMODE
              value: "disable"
            - name: SYNC_REGISTRY
              value: "true"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: harbor-certs
              mountPath: /ssl/
            - name: harbor-config
              mountPath: /etc/ui/config
      imagePullSecrets:
        - name: portus-pull-secret
      volumes:
        - name: harbor-config
          secret:
            secretName: harbor-config
        - name: harbor-certs
          secret:
            secretName: harbor-certs

```

Here is my service and deployment file for admin server, I'm relying on kube secrets to supply the sensitive information
```
---
kind: Service
apiVersion: v1
metadata:
  name: "harbor-adminserver"
  namespace: ournamespace
  labels:
    name: "harbor-adminserver"
    dns_zone: "{{ dns_zone }}"
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
  type: NodePort
  selector:
    name: "harbor-adminserver"
    sha: "{{ docker_version[0:7] }}"

---

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: "harbor-adminserver-{{ docker_version[0:7] }}"
  namespace: ournamespace
  labels: 
    app: harbor-adminserver
    sha: "{{ docker_version[0:7] }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: "harbor-adminserver"
        sha: "{{ docker_version[0:7] }}"
    spec:
      containers:
        - name: "harbor-adminserver"
          image: "ourreg/harbor-adminserver:{{ docker_version }}"
          env:
            - name: secretKey
              valueFrom:
                  secretKeyRef:
                    name: harbor-config
                    key: harbor-secretKey
            - name: EMAIL_PWD
              valueFrom:
                  secretKeyRef:
                    name: harbor-config
                    key: harbor-email-pwd
            - name: HARBOR_ADMIN_PASSWORD
              valueFrom:
                  secretKeyRef:
                    name: harbor-config
                    key: harbor-admin-password
            - name: JOBSERVICE_SECRET
              valueFrom:
                  secretKeyRef:
                    name: harbor-config
                    key: harbor-jobservice-secret
            - name: UI_SECRET
              valueFrom:
                  secretKeyRef:
                    name: harbor-config
                    key: harbor-ui-secret
            - name: POSTGRESQL_HOST
              valueFrom:
                secretKeyRef:
                  name: harbor-config
                  key: harbor-pgsql-host
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                  secretKeyRef:
                    name: harbor-config
                    key: harbor-pgsql-password
            - name: POSTGRESQL_SSLMODE
              value: "disable"
            - name: POSTGRESQL_PORT
              value: "5432"
            - name: POSTGRESQL_USERNAME
              value: "harbor"
            - name: POSTGRESQL_DATABASE
              value: "harbor"
            - name: EMAIL_HOST
              value: "ourmailserver"
            - name: EMAIL_PORT
              value: "587"
            - name: EMAIL_USR
              value: "ouruser"
            - name: EMAIL_SSL
              value: "true"
            - name: EMAIL_FROM
              value: "ourfrom@email.com"
            - name: EMAIL_INSECURE
              value: "false"
            - name: EXT_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: harbor-config
                  key: https-harbor-dns-value
            - name: UI_URL
              value: "http://harbor-ui.svc.cluster.local:8080"
            - name: JOBSERVICE_URL
              value: "http://harbor-jobservice.svc.cluster.local:8080"
            - name: REGISTRY_URL
              value: "http://harbor-registry.svc.cluster.local:5000"
            - name: TOKEN_SERVICE_URL
              value: "http://harbor-ui.svc.cluster.local:8080/service/token"
            - name: WITH_NOTARY
              value: "false"
            - name: NOTARY_URL
              value: "http://notary-server.svc.cluster.local:4443"
            - name: LOG_LEVEL
              value: "info"
            - name: IMAGE_STORE_PATH
              value: "/" # This is a temporary hack.
            - name: AUTH_MODE
              value: "ldap_auth"
            - name: SELF_REGISTRATION 
              value: "on"
            - name: LDAP_URL
              value: "ldaps://ourldapserver"
            - name: LDAP_SEARCH_DN
              valueFrom:
                secretKeyRef:
                  name: harbor-config
                  key: "harbor-ldap-search-dn"
            - name: LDAP_SEARCH_PWD
              valueFrom:
                secretKeyRef:
                  name: harbor-config
                  key: harbor-ldap-search-pwd
            - name: LDAP_BASE_DN
              value: "ourbasedn"
            - name: LDAP_FILTER 
              value: ""
            - name: LDAP_UID
              value: "cn"
            - name: LDAP_SCOPE
              value: "2"
            - name: LDAP_TIMEOUT
              value: "5"
            - name: LDAP_VERIFY_CERT
              value: "false"
            - name: DATABASE_TYPE
              value: "postgresql"
            - name: PROJECT_CREATION_RESTRICTION
              value: "everyone"
            - name: VERIFY_REMOTE_CERT
              value: "off"
            - name: MAX_JOB_WORKERS
              value: "3"
            - name: TOKEN_EXPIRATION
              value: "30"
            - name: CFG_EXPIRATION
              value: "5"
            - name: GODEBUG
              value: "netdns=cgo"
            - name: ADMIRAL_URL
              value: "NA"
            - name: RESET 
              value: "false"
            - name: WITH_CLAIR
              value: "true"
            - name: CLAIR_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: harbor-config
                  key: harbor-clair-pgsql-host
            - name: CLAIR_DB_PORT
              value:  "5432"
            - name: CLAIR_DB_USERNAME
              value: "harborclair"
            - name: CLAIR_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: harbor-config
                  key: harbor-clair-db-password
            - name: CLAIR_DB
              value: "harborclair"
            - name: CLAIR_URL
              value: "http://harbor-clair.svc.cluster.local:6060"
            - name: CLAIR_DB_SSLMODE
              value: "disable"
            - name: REGISTRY_STORAGE_PROVIDER_NAME
              value: "s3"
            - name: WITH_CHARTMUSEUM
              value: "true"
            - name: CHART_REPOSITORY_URL
              valueFrom:
                secretKeyRef:
                  name: harbor-config
                  key: chartmuseum-dns-value
            - name: PORT
              value: "8080"
            - name: JSON_CFG_STORE_PATH
              value: /etc/adminserver/config/config.json
            - name: KEY_PATH
              value: /etc/adminserver/secrets/harbor-secretKey
          ports:
            - containerPort: 8080
          volumeMounts:
          - name: harbor-certs
            mountPath: /ssl/
          - name: harbor-config
            mountPath: /etc/adminserver/secrets
      imagePullSecrets:
        - name: portus-pull-secret
      volumes:
        - name: harbor-config
          secret:
            secretName: harbor-config
        - name: harbor-certs
          secret:
            secretName: harbor-certs
```

Here is my proxy harbor.conf (we have a base nginx.conf not included here

```
# this is necessary for us to be able to disable request buffering in all cases
proxy_http_version 1.1;

upstream ui {
  server harbor-ui.svc.cluster.local:8080;
}

upstream registry {
  least_conn;
  server harbor-registry.svc.cluster.local:5000;
}

log_format timed_combined '$remote_addr - '
  '"$request" $status $body_bytes_sent '
  '"$http_referer" "$http_user_agent" '
  '$request_time $upstream_response_time $pipe';
access_log /dev/stdout timed_combined;

server {
  listen 443 ssl;
  server_name HARBOR_DNS_VALUE;
  server_tokens off;
  # SSL
  ssl_certificate /etc/ssl/harbornginx/harbor.crt;
  ssl_certificate_key /etc/ssl/harbornginx/harbor.key;

  # Recommendations from https://raymii.org/s/tutorials/Strong_SSL_Security_On_nginx.html
  ssl_protocols TLSv1.1 TLSv1.2;
  ssl_ciphers '!aNULL:kECDH+AESGCM:ECDH+AESGCM:RSA+AESGCM:kECDH+AES:ECDH+AES:RSA+AES:';
  ssl_prefer_server_ciphers on;
  ssl_session_cache shared:SSL:10m;

  # disable any limits to avoid HTTP 413 for large image uploads
  client_max_body_size 0;

  # required to avoid HTTP 411: see Issue #1486 (https://github.com/docker/docker/issues/1486)
  chunked_transfer_encoding on;
  location / {
    proxy_pass http://ui/;
    proxy_set_header X-Forwarded-Ssl on;
    proxy_set_header Host               $http_host;   # required for docker client's sake
    proxy_set_header X-Real-IP          $remote_addr; # pass on real client's IP
    proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto  https;

    # Add Secure flag when serving HTTPS
    proxy_cookie_path / "/; secure";
    proxy_read_timeout                  900;
    proxy_buffering                     on;
  }

  location /api/ {
    proxy_pass http://ui/api/;
    proxy_set_header                X-Forwarded-Ssl     on;
    proxy_set_header Host               $http_host;   # required for docker client's sake
    proxy_set_header X-Real-IP          $remote_addr; # pass on real client's IP
    proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto  https;
    proxy_read_timeout                  900;
    proxy_buffering                     on;
  }
  location ~ ^/(login|log_out|sendEmail|language|reset|userExists|reset_password|chartrepo) {
    proxy_pass http://ui;
    proxy_set_header                X-Forwarded-Ssl     on;
    proxy_set_header Host               $http_host;   # required for docker client's sake
    proxy_set_header X-Real-IP          $remote_addr; # pass on real client's IP
    proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto  https;
    proxy_read_timeout                  900;
    proxy_buffering                     on;
  }
  location /v1/ {
    return 404;
  }
  location /v2/ {
    proxy_pass http://registry/;
    proxy_set_header Host               $http_host;   # required for docker client's sake
    proxy_set_header X-Real-IP          $remote_addr; # pass on real client's IP
    proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto  https;
    proxy_read_timeout                  900;
    proxy_buffering                     on;
    proxy_redirect  http://registry/v2/ https://HARBOR_DNS_VALUE/v2/;
          
  }

  location /service/ {
    proxy_pass http://ui/service/;
    proxy_set_header                X-Forwarded-Ssl     on;
    proxy_set_header Host               $http_host;   # required for docker client's sake
    proxy_set_header X-Real-IP          $remote_addr; # pass on real client's IP
    proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto  https;
    proxy_read_timeout                  900;
    proxy_buffering                     on;
  }		
  location /service/notifications {
    return 404;
  }
}
  server {
    listen 80;
    server_name HARBOR_DNS_VALUE;
    return 301 https://$host$request_uri;
} 
```

This issue with the proxy I'm having is that it allows me to successfully run docker login harbor.dns.com but then pushes/pulls do not work - 404's.  But this configuration is also incorrect because it makes harbor.dns.com/v2/v2/ required to actually navigate to the registry api.

I appreciate any pointers, I've struggled with this for a few days on this.
