### ISSUE TITLE
Jobservice tries to access registry-harbor-database although using external DB

### ISSUE THREAD

**Issue by cmur2** [goharbor/harbor-helm#508]
I configured in my values.yml the following:
```yaml
database:
  # if external database is used, set "type" to "external"
  # and fill the connection informations in "external" section
  type: external
  external:
    host: example.org
# snip
jobservice:
  # The logger for jobs: "file", "database" or "stdout"
  jobLogger: database
```
but at runtime get the following error: `Close job logger failed: logger: DB, err: dial tcp: lookup registry-harbor-database`
This suggests that the jobservice assumes to always use the `internal` DB even when specified differently. Do I need to configure something else in addition or is this a bug with the Helm chart or with Harbor itself?
