### ISSUE TITLE
helm charts got the wrong oss addr

### ISSUE THREAD

**Issue by gary0121** [goharbor/harbor-helm#510]
oss:
      accesskeyid: xxx
      accesskeysecret: xxx
      region: oss-cn-beijing
      bucket: hose-registry
      endpoint: hose-registry.oss-cn-beijing.aliyuncs.com
      #internal: false
      #encrypt: false
      #secure: true
      #chunksize: 10M
      #rootdirectory: rootdirectory

ERROR:
Get http://hose-registry.hose-registry.oss-cn-beijing.aliyuncs.com/?encoding-type=url&marker=&max-keys=50&prefix=ci: dial tcp: lookup hose-registry.hose-registry.oss-cn-beijing.aliyuncs.com on 172.21.0.10:53: no such host

It should be:
http://hose-registry.oss-cn-beijing.aliyuncs.com

**Comment by wind2008hxy** [comment]
don't set the endpoint
```
oss:
  accesskeyid: xxx
  accesskeysecret: xxx
  region: oss-cn-beijing
  bucket: hose-registry
```
