### ISSUE TITLE
nginx readiness probe doesn't work under istio

### ISSUE THREAD

**Issue by R0GG** [goharbor/harbor-helm#576]
Hello,

It seems that the readiness probe of nginx does not work under istio because nginx proxy forwards the Host header (`proxy_set_header Host $host;`) of curl which is 127.0.0.1 (or the pod IP).

As this is an HTTP request, it goes through envoy router which routes the requests based on the HOST http header (in our case is 127.0.0.1).
Envoy then fails to match any routes with 127.0.0.1 as HOST header.

A possible fix could be to remove `proxy_set_header Host $host;` and in the nginx conf something like bellow so that the url match the name of the k8s service.
```
upstream {{ template "harbor.portal" . }} {
  server {{ template "harbor.portal" . }};
}

location / {
  proxy_pass http://{{ template "harbor.portal" . }}/;
}
```

related: #406

**Comment by R0GG** [comment]
update I got it working without the changes of the NGINX conf
For that i had to create EnvoyFilters:
```
---
apiVersion: networking.istio.io/v1alpha3
kind:
metadata:
  name: harbor-portal
  namespace: harbor
spec:
  workloadSelector:
    labels:
      app: harbor
  configPatches:
  - applyTo: VIRTUAL_HOST
    context: ANY
    match:
      routeConfiguration:
        name: "harbor-harbor-portal.harbor.svc.cluster.local:80"
    patch:
      operation: MERGE
      value:
        domains:
          - "*"

---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: harbor-core-registry-5000
  namespace: harbor
spec:
  workloadSelector:
    labels:
      app: harbor
  configPatches:
  - applyTo: VIRTUAL_HOST
    context: ANY
    match:
      routeConfiguration:
        name: "harbor-harbor-registry.harbor.svc.cluster.local:5000"
    patch:
      operation: MERGE
      value:
        domains:
          - "*"

---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: harbor-core
  namespace: harbor
spec:
  workloadSelector:
    labels:
      app: harbor
  configPatches:
  - applyTo: VIRTUAL_HOST
    context: ANY
    match:
      routeConfiguration:
        name: "harbor-harbor-core.harbor.svc.cluster.local:80"
    patch:
      operation: MERGE
      value:
        domains:
          - "*"
```
