### ISSUE TITLE
harbor-chartmuseum Use swift run Error

### ISSUE THREAD

**Issue by hongruiji** [goharbor/harbor-helm#577]
I use Helm install Harbor 1.10.2 ;
registry and chartmuseum storage use ceph swift ;
registry service ok , but chartmuseum service run error : 

```sh
[root@k8s01 harbor]# kubectl logs harbor-harbor-chartmuseum-5cdf7d85f9-x6mpx 
main.main()
	/go/src_code/cmd/chartmuseum/main.go:52 +0x1c4
```

My CM: 
```yaml
data:
  ALLOW_OVERWRITE: "true"
  AUTH_ANONYMOUS_GET: "false"
  BASIC_AUTH_USER: chart_controller
  CACHE: redis
  CACHE_REDIS_ADDR: harbor-redis-ha-haproxy:6379
  CACHE_REDIS_DB: "3"
  CHART_POST_FORM_FIELD_NAME: chart
  CONTEXT_PATH: ""
  DEBUG: "false"
  DEPTH: "1"
  DISABLE_API: "false"
  DISABLE_METRICS: "false"
  DISABLE_STATEFILES: "false"
  INDEX_LIMIT: "0"
  LOG_JSON: "true"
  MAX_STORAGE_OBJECTS: "0"
  MAX_UPLOAD_SIZE: "20971520"
  OS_AUTH_URL: http://172.28.88.28:7480/auth/v1.0
  OS_PROJECT_NAME: test1
  OS_USERNAME: test1:swift
  PORT: "9999"
  PROV_POST_FORM_FIELD_NAME: prov
  STORAGE: openstack
  STORAGE_OPENSTACK_CONTAINER: test1bucket1
  STORAGE_OPENSTACK_REGION: sqcs-group
  TLS_CERT: ""
  TLS_KEY: ""
kind: ConfigMap
```

I test image: 
goharbor/chartmuseum-photon:v1.10.2
goharbor/chartmuseum-photon:v0.9.0-v1.10.1

The error log displayed is the same.  

For help
