### ISSUE TITLE
docker push retries end with dial tcp 10.0.0.21:7480: i/o timeout

### ISSUE THREAD

**Issue by xin053** [goharbor/harbor-helm#579]
## problem

```shell
a6d503001157: Pushing [==================================================>]  1.437MB
dial tcp 10.0.0.21:7480: i/o timeout
```

## env
system: ubuntu 18.04
k8s: 1.16.8
harbor chart: 1.3.2
harbor: 1.10.2 with ingress-nginx(tls enabled)

I use ceph rgw as s3 backend

```yaml
s3:
      region: default
      bucket: harbor
      accesskey: VAP77WJNXFYZQV*****
      secretkey: YxeRaBAadeXz3dJ4itihQnNe6bcV*****
      regionendpoint: http://10.0.0.21:7480
      encrypt: false
      # keyid: mykeyid
      secure: False
      # v4auth: true
      chunksize: "52428800"
      # rootdirectory: /s3/object/name/prefix
      # storageclass: STANDARD
```

`http://10.0.0.21:7480` is the address of ceph rgw

when I push image from another network that can not reach `10.0.0.21:7480`, `docker push` retry several times end with `dial tcp 10.0.0.21:7480: i/o timeout`. And I see that the image had been upload to ceph rgw. I can only push image in a network that can reach `10.0.0.21:7480`.

```shell
a6d503001157: Pushing [==================================================>]  1.437MB
dial tcp 10.0.0.21:7480: i/o timeout
```

when I change `regionendpoint` to a external address that can be access from anywhere, everything thing is fine.

Is it a bug or suppose to be that way?
