### ISSUE TITLE
Traefik Support installing Harbor via helm? 

### ISSUE THREAD

**Issue by rsoika** [goharbor/harbor-helm#582]
I can see that the helm chart seem to support traefik in some way. But I can't find any example how to use this.

I have installed a self managed Kubernetes Cluster with Traefik V2.
What I need is an example how to install harbor via helm to use my existing traefik reverse proxy. 

Should I create a Ingress rule by myself, or can I configure this by setting specific parameters when installing Harbor via helm?

Thanks for a short example or any hints.

**Comment by rsoika** [comment]
I did a lot of trail and error and come to a working solution with the following install command (where my-registry.foo.com is my public domain name):


```
helm install registry harbor/harbor --set persistence.enabled=false\
    -n harbor --namespace harbor\
    --set expose.ingress.hosts.core=my-registry.foo.com \
    --set expose.ingress.annotations.'traefik\.ingress\.kubernetes\.io/router\.entrypoints'=websecure \
    --set externalURL=https://my-registry.foo.com \
    --set notary.enabled=false
```

Can someone confirm that this is the expected configuration? If so we maybe should add this example to the REAEMD.md file?

**Comment by reasonerjt** [comment]
Leveraging the ingress controller by different vendor is mainly about setting the annotations correct.

Unfortunately, I have limited bandwidth to verify each ingress controller.
I wish to suggest you follow the doc of Traefik to set the right annotations.  

I'll create an item in faq somewhere in this repo for other users' reference.

**Comment by djpbessems** [comment]
This might be relevant information:
I have added the following `ingressRoute` and left the ingress annotations unmodified:
```
piVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: harbor
  namespace: harbor
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`registry.example.com`)
    kind: Rule
    services:
    - name: harbor-harbor-portal
      namespace: harbor
      port: 80
  - match: Host(`registry.example.com`) && PathPrefix(`/api/`, `/service/`, `/v2/`, `/chartrepo/`, `/c/`)
    kind: Rule
    services:
    - name: harbor-harbor-core
      namespace: harbor
      port: 80
  - match: Host(`notary.example.com`)
    kind: Rule
    services:
    - name: harbor-harbor-notary-server
      namespace: harbor
      port: 4443
  tls:
    certResolver: default
    domains:
    - main: '*.example.com'
      sans:
      - 'example.com'
```
