### ISSUE TITLE
trivy is pending when I set  `persistence.enabled= false`

### ISSUE THREAD

**Issue by Archer1A** [goharbor/harbor-helm#596]
# trivy is pending when I set  `persistence.enabled= false`
 helm 3.1.1 
harbor chart version : 1.4..0 
values.yaml 

```yaml
persistence:
  enabled: false
  # Setting it to "keep" to avoid removing PVCs during a helm delete
  # operation. Leaving it empty will delete PVCs after the chart deleted
  resourcePolicy: "keep"
  persistentVolumeClaim:
    registry:
      # Use the existing PVC which must be created manually before bound,
      # and specify the "subPath" if the PVC is shared with other components
      existingClaim: ""
      # Specify the "storageClass" used to provision the volume. Or the default
      # StorageClass will be used(the default).
      # Set it to "-" to disable dynamic provisioning
      storageClass: ""
      subPath: ""
      accessMode: ReadWriteOnce
      size: 5Gi
    chartmuseum:
      existingClaim: ""
      storageClass: ""
      subPath: ""
      accessMode: ReadWriteOnce
      size: 5Gi
    jobservice:
      existingClaim: ""
      storageClass: ""
      subPath: ""
      accessMode: ReadWriteOnce
      size: 1Gi
    # If external database is used, the following settings for database will
    # be ignored
    database:
      existingClaim: ""
      storageClass: ""
      subPath: ""
      accessMode: ReadWriteOnce
      size: 1Gi
    # If external Redis is used, the following settings for Redis will
    # be ignored
    redis:
      existingClaim: ""
      storageClass: ""
      subPath: ""
      accessMode: ReadWriteOnce
      size: 1Gi
    trivy:
      existingClaim: ""
      storageClass: ""
      subPath: ""
      accessMode: ReadWriteOnce
      size: 5Gi
  # Define which storage backend is used for registry and chartmuseum to store
  # images and charts. Refer to
  # https://github.com/docker/distribution/blob/master/docs/configuration.md#storage
  # for the detail.
  imageChartStorage:
    # Specify whether to disable `redirect` for images and chart storage, for
    # backends which not supported it (such as using minio for `s3` storage type), please disable
    # it. To disable redirects, simply set `disableredirect` to `true` instead.
    # Refer to
    # https://github.com/docker/distribution/blob/master/docs/configuration.md#redirect
    # for the detail.
    disableredirect: false
    # Specify the "caBundleSecretName" if the storage service uses a self-signed certificate.
    # The secret must contain keys named "ca.crt" which will be injected into the trust store
    # of registry's and chartmuseum's containers.
    # caBundleSecretName:

    # Specify the type of storage: "filesystem", "azure", "gcs", "s3", "swift",
    # "oss" and fill the information needed in the corresponding section. The type
    # must be "filesystem" if you want to use persistent volumes for registry
    # and chartmuseum
    type: filesystem
    filesystem:
      rootdirectory: /storage
      #maxthreads: 100
    azure:
      accountname: accountname
      accountkey: base64encodedaccountkey
      container: containername
      #realm: core.windows.net
    gcs:
      bucket: bucketname
      # The base64 encoded json file which contains the key
      encodedkey: base64-encoded-json-key-file
      #rootdirectory: /gcs/object/name/prefix
      #chunksize: "5242880"
    s3:
      region: us-west-1
      bucket: bucketname
      #accesskey: awsaccesskey
      #secretkey: awssecretkey
      #regionendpoint: http://myobjects.local
      #encrypt: false
      #keyid: mykeyid
      #secure: true
      #v4auth: true
      #chunksize: "5242880"
      #rootdirectory: /s3/object/name/prefix
      #storageclass: STANDARD
    swift:
      authurl: https://storage.myprovider.com/v3/auth
      username: username
      password: password
      container: containername
      #region: fr
      #tenant: tenantname
      #tenantid: tenantid
      #domain: domainname
      #domainid: domainid
      #trustid: trustid
      #insecureskipverify: false
      #chunksize: 5M
      #prefix:
      #secretkey: secretkey
      #accesskey: accesskey
      #authversion: 3
      #endpointtype: public
      #tempurlcontainerkey: false
      #tempurlmethods:
    oss:
      accesskeyid: accesskeyid
      accesskeysecret: accesskeysecret
      region: regionname
      bucket: bucketname
      #endpoint: endpoint
      #internal: false
      #encrypt: false
      #secure: true
      #chunksize: 10M
      #rootdirectory: rootdirectory

```
pod describe 
```
[root@vic-master harbor]# kubectl describe  po registry-harbor-trivy-0
Name:           registry-harbor-trivy-0
Namespace:      default
Priority:       0
Node:           <none>
Labels:         app=harbor
                chart=harbor
                component=trivy
                controller-revision-hash=registry-harbor-trivy-8484974c7b
                heritage=Helm
                release=registry
                statefulset.kubernetes.io/pod-name=registry-harbor-trivy-0
Annotations:    checksum/secret: f493ba86d592194271e7f4679a3dd31daae525292dedbf295b9909aca9e94b5a
Status:         Pending
IP:
IPs:            <none>
Controlled By:  StatefulSet/registry-harbor-trivy
Containers:
  trivy:
    Image:      goharbor/trivy-adapter-photon:v2.0.0
    Port:       8080/TCP
    Host Port:  0/TCP
    Limits:
      cpu:     1
      memory:  1Gi
    Requests:
      cpu:      200m
      memory:   512Mi
    Liveness:   http-get http://:api-server/probe/healthy delay=5s timeout=1s period=10s #success=1 #failure=10
    Readiness:  http-get http://:api-server/probe/ready delay=5s timeout=1s period=10s #success=1 #failure=3
    Environment:
      SCANNER_LOG_LEVEL:             info
      SCANNER_TRIVY_CACHE_DIR:       /home/scanner/.cache/trivy
      SCANNER_TRIVY_REPORTS_DIR:     /home/scanner/.cache/reports
      SCANNER_TRIVY_DEBUG_MODE:      false
      SCANNER_TRIVY_VULN_TYPE:       os,library
      SCANNER_TRIVY_GITHUB_TOKEN:    <set to the key 'gitHubToken' in secret 'registry-harbor-trivy'>  Optional: false
      SCANNER_TRIVY_SEVERITY:        UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
      SCANNER_TRIVY_IGNORE_UNFIXED:  false
      SCANNER_TRIVY_SKIP_UPDATE:     false
      SCANNER_TRIVY_INSECURE:        false
      SCANNER_API_SERVER_ADDR:       :8080
      SCANNER_STORE_REDIS_URL:       <set to the key 'redisURL' in secret 'registry-harbor-trivy'>  Optional: false
      SCANNER_JOB_QUEUE_REDIS_URL:   <set to the key 'redisURL' in secret 'registry-harbor-trivy'>  Optional: false
    Mounts:
      /home/scanner/.cache from data (rw)
Conditions:
  Type           Status
  PodScheduled   False
Volumes:
  data:
    Type:        PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:   data-registry-harbor-trivy-0
    ReadOnly:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age                 From               Message
  ----     ------            ----                ----               -------
  Warning  FailedScheduling  36s (x12 over 15m)  default-scheduler  pod has unbound immediate PersistentVolumeClaims (repeated 2 times)

```
