### ISSUE TITLE
database pod cannot mount NFS export provided by isilon csi after pod deletion

### ISSUE THREAD

**Issue by cocampbe** [goharbor/harbor-helm#615]
This is informational. The info would be useful maybe in a FAQ, or troubleshooting guide. I am using the EMC Isilon CSI as the storageclass for the harbor deployment. On initial deploy, everything works as expected. In testing, I noticed that if the database ss pod is recreated for any reason, the pod gets stuck at Init. When looking at the description of the pod, I saw that the pod could not mount the isilon export. After much digging, I figured out the issue. The database pod changes the ownership of the volume mount to 999:999. When the pod restarts, part of the isilon CSI does a GET of metadata on the exported volume. The account the CSI uses to access the API no longer is the owner of the share on Isione OneFS. Because of this, the GET replies with a 403 and the mount fails. 

The fix/workaround is to set a subpath on the  persistant colume claim sectoin in the values.yaml.

```
database:
     existingClaim: ""
     storageClass: "isilon"
     subPath: "data"
     accessMode: ReadWriteMany
     size: 25Gi
```

Doing this allows the CSI to still be able to query metadata on the export and in turn allows the pod to remount the pv.
