### ISSUE TITLE
trivy.subPath is not used in templates/trivy/trivy-sts.yaml

### ISSUE THREAD

**Issue by linenlin01** [goharbor/harbor-helm#670]
suggest added  in volumeMounts section

subPath: {{ $trivy.subPath }}

```
          volumeMounts:
          - name: data
            mountPath: /home/scanner/.cache
            subPath: {{ $trivy.subPath }}
            readOnly: false

```
