### ISSUE TITLE
internal server error when trying to access Task logs

### ISSUE THREAD

**Issue by fl-max** [goharbor/harbor-helm#680]
I am getting the following error when trying to access the Task logs:
`{"errors":[{"code":"UNKNOWN","message":"internal server error"}]}`

In the core Pod I see:
```shell
[ERROR] [/server/error/error.go:53]: {"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"failed to get log of task 139: http error: code 500, message {\"code\":10009,\"message\":\"failed to get the job log\",\"details\":\"no log data getter is configured\"}"}]} 
/harbor/src/server/error/error.go:81, github.com/goharbor/harbor/src/server/error.apiError
/harbor/src/server/error/error.go:50, github.com/goharbor/harbor/src/server/error.SendError
/harbor/src/common/api/base.go:67, github.com/goharbor/harbor/src/common/api.(*BaseAPI).RenderError
/harbor/src/common/api/base.go:228, github.com/goharbor/harbor/src/common/api.(*BaseAPI).SendInternalServerError
/harbor/src/core/api/replication_execution.go:238, github.com/goharbor/harbor/src/core/api.(*ReplicationOperationAPI).GetTaskLog
/usr/local/go/src/reflect/value.go:460, reflect.Value.call
/usr/local/go/src/reflect/value.go:321, reflect.Value.Call
/harbor/src/vendor/github.com/astaxie/beego/router.go:853, github.com/astaxie/beego.(*ControllerRegister).ServeHTTP
/harbor/src/server/middleware/transaction/transaction.go:62, github.com/goharbor/harbor/src/server/middleware/transaction.Middleware.func1.1
/harbor/src/lib/orm/orm.go:63, github.com/goharbor/harbor/src/lib/orm.WithTransaction.func1
/harbor/src/server/middleware/transaction/transaction.go:71, github.com/goharbor/harbor/src/server/middleware/transaction.Middleware.func1
/harbor/src/server/middleware/middleware.go:57, github.com/goharbor/harbor/src/server/middleware.New.func1.1
/usr/local/go/src/net/http/server.go:2007, net/http.HandlerFunc.ServeHTTP
/harbor/src/server/middleware/notification/notification.go:31, github.com/goharbor/harbor/src/server/middleware/notification.Middleware.func1
/harbor/src/server/middleware/middleware.go:57, github.com/goharbor/harbor/src/server/middleware.New.func1.1
/usr/local/go/src/net/http/server.go:2007, net/http.HandlerFunc.ServeHTTP
/harbor/src/server/middleware/orm/orm.go:53, github.com/goharbor/harbor/src/server/middleware/orm.MiddlewareWithConfig.func1
/harbor/src/server/middleware/middleware.go:57, github.com/goharbor/harbor/src/server/middleware.New.func1.1
/usr/local/go/src/net/http/server.go:2007, net/http.HandlerFunc.ServeHTTP
/harbor/src/server/middleware/middleware.go:52, github.com/goharbor/harbor/src/server/middleware.New.func1.1
/usr/local/go/src/net/http/server.go:2007, net/http.HandlerFunc.ServeHTTP
/harbor/src/server/middleware/security/security.go:62, github.com/goharbor/harbor/src/server/middleware/security.Middleware.func1.1
/usr/local/go/src/net/http/server.go:2007, net/http.HandlerFunc.ServeHTTP
/harbor/src/server/middleware/csrf/csrf.go:55, github.com/goharbor/harbor/src/server/middleware/csrf.attach.func1
/usr/local/go/src/net/http/server.go:2007, net/http.HandlerFunc.ServeHTTP
/harbor/src/vendor/github.com/gorilla/csrf/csrf.go:297, github.com/gorilla/csrf.(*csrf).ServeHTTP
/harbor/src/server/middleware/csrf/csrf.go:75, github.com/goharbor/harbor/src/server/middleware/csrf.Middleware.func2
/harbor/src/server/middleware/middleware.go:57, github.com/goharbor/harbor/src/server/middleware.New.func1.1
/usr/local/go/src/net/http/server.go:2007, net/http.HandlerFunc.ServeHTTP
/harbor/src/server/middleware/session/session.go:34, github.com/goharbor/harbor/src/server/middleware/session.Middleware.func1.1
/usr/local/go/src/net/http/server.go:2007, net/http.HandlerFunc.ServeHTTP
/harbor/src/server/middleware/log/log.go:33, github.com/goharbor/harbor/src/server/middleware/log.Middleware.func1
/harbor/src/server/middleware/middleware.go:57, github.com/goharbor/harbor/src/server/middleware.New.func1.1
/usr/local/go/src/net/http/server.go:2007, net/http.HandlerFunc.ServeHTTP
/harbor/src/server/middleware/requestid/requestid.go:37, github.com/goharbor/harbor/src/server/middleware/requestid.Middleware.func1
/harbor/src/server/middleware/middleware.go:57, github.com/goharbor/harbor/src/server/middleware.New.func1.1
/usr/local/go/src/net/http/server.go:2007, net/http.HandlerFunc.ServeHTTP
/usr/local/go/src/net/http/server.go:2802, net/http.serverHandler.ServeHTTP
/usr/local/go/src/net/http/server.go:1890, net/http.(*conn).serve
```

And in the Job service Pod:
`[ERROR] [/jobservice/api/handler.go:288]: Serve http request 'GET /api/v1/jobs/ffb5444c9ca3353f56f8249d/log' error: 500 {"code":10009,"message":"failed to get the job log","details":"no log data getter is configured"}`

I suspect this may be due to setting `jobservice.jobLogger: stdout`. I prefer this go to STDOUT so that Loki may capture the logs. Is it possible to define more than one logger (ie. `jobservice.jobLogger: "stdout,file"`)? This would solve both use-cases.

**Comment by steven-zou** [comment]
@fl-max 

Not all the log provider support log data getter. So far, only File and Database log providers support such features.

STDOUT does not support.

**Comment by reasonerjt** [comment]
@fl-max 
As for supporting multiple logger in jobservice, if you still need this feature could you open an issue in goharbor/harbor repo?

This repo is focusing on the helm chart of Harbor.

**Comment by steven-zou** [comment]
@fl-max 
> I suspect this may be due to setting `jobservice.jobLogger: stdout`. I prefer this go to STDOUT so that Loki may capture the logs. Is it possible to define more than one logger (ie. `jobservice.jobLogger: "stdout,file"`)? This would solve both use-cases.

From the job service side, yes, we support enabling multiple loggers at the same time. It seems that the harbor chart only exposes one logger setting option in the values.yaml.

**Comment by fl-max** [comment]
@steven-zou so if I understand you correctly, [this CM property](https://github.com/goharbor/harbor-helm/blob/42e1887f914e15d54538d03534a038eb43896966/templates/jobservice/jobservice-cm.yaml#L24) should allow for multiple loggers (ie. list size >1)? But are you saying even if I defined both `file` and `stdout` loggers here, I'd still suffer from the same error in my original comment?

If not and having >1 Logger defined is practical, one way to handle this is to just have all if conditions check if the string exists in `jobservice.jobLogger`. For example:
```yaml
    job_loggers:
      {{- if contains "file" .Values.jobservice.jobLogger }}
      - name: "FILE"
        level: {{ .Values.logLevel | upper }}
        settings: # Customized settings of logger
          base_dir: "/var/log/jobs"
        sweeper:
          duration: 14 #days
          settings: # Customized settings of sweeper
            work_dir: "/var/log/jobs"
      {{- end }}
      {{- if contains "database" .Values.jobservice.jobLogger }}
      - name: "DB"
        level: {{ .Values.logLevel | upper }}
        sweeper:
          duration: 14 #days
      {{- end }}
       {{- if contains "stdout" .Values.jobservice.jobLogger }}
      - name: "STD_OUTPUT"
        level: {{ .Values.logLevel | upper }}
      {{- end }}
```
This would allow for setting `jobservice.jobLogger: "stdout,file"` and both being set as loggers.

Maybe even go a step further by allowing the user to define their own Loggers. This will help with future proofing as new loggers are introduced and/or properties are updated.
```yaml
    job_loggers:
      {{- if .Values.jobservice.customJobLoggers }}
      {{- toYaml .Values.jobservice.customJobLoggers | nindent 6 }}
      {{- else }}
      {{- if contains "file" .Values.jobservice.jobLogger }}
      - name: "FILE"
        level: {{ .Values.logLevel | upper }}
        settings: # Customized settings of logger
          base_dir: "/var/log/jobs"
        sweeper:
          duration: 14 #days
          settings: # Customized settings of sweeper
            work_dir: "/var/log/jobs"
      {{- end }}
      {{- if contains "database" .Values.jobservice.jobLogger }}
      - name: "DB"
        level: {{ .Values.logLevel | upper }}
        sweeper:
          duration: 14 #days
      {{- end }}
      {{- if contains "stdout" .Values.jobservice.jobLogger }}
      - name: "STD_OUTPUT"
        level: {{ .Values.logLevel | upper }}
      {{- end }}
      {{- end }}
```
By using an outer-if condition, we can maintain backwards compatibility with existing deployments.

Thoughts?
