### ISSUE TITLE
upgrade : error: couldn't find key secret in harbor service job

### ISSUE THREAD

**Issue by zdhamasha** [goharbor/harbor-helm#699]
INFO:
```bash
NAME       	REVISION	UPDATED                 	STATUS  	CHART       	APP VERSION	NAMESPACE  
kube-harbor	6       	Wed Aug 19 15:16:53 2020	DEPLOYED	harbor-1.4.2	2.0.2      	kube-harbor
```
We found an issue during the upgrading in the secret called  **harbor-jobservice**  

The issue was in the deployment 

```yaml
          - name: CORE_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ template "harbor.core" . }}
                key: secret
```
the deployment is looking for a value with key name **secret**, on the other hand the secret has different key name which is
**REGISTRY_CREDENTIAL_PASSWORD**
```yaml
data:
  JOBSERVICE_SECRET: {{ .Values.jobservice.secret | default (randAlphaNum 16) | b64enc | quote }}
  REGISTRY_CREDENTIAL_PASSWORD: {{ .Values.registry.credentials.password | b64enc | quote }}
```

Another thing about the the **livenessProbe.initialDelaySeconds** in the **harbor core** should increased to avoid restart pod during upgrading the schema  

the following works for me 
```yaml
--set core.livenessProbe.initialDelaySeconds="5000"
```
