### ISSUE TITLE
413 Payload Too Large on login (ingress)

### ISSUE THREAD

**Issue by 0pendev** [goharbor/harbor-helm#731]
When deploying ingress with the following command : 
`
    helm install skube-registry harbor/harbor\
	 --namespace skube-system\
	 --set externalURL=https://harbor.local\
	 --set expose.type=ingress\
	 --set expose.ingress.hosts.core=harbor.local\
	 --set expose.ingress.hosts.notary=harbor.local
`

I can access the login page but when trying to login the HTTP request fails with the following error : 
`
413 Payload Too Large
The request is too large. 
`

**Comment by 0pendev** [comment]
For anyone with this issue just use the following values : 
```yaml
    externalURL: https://harbor.local
    expose:
      type: ingress
      ingress:
        hosts:
          core: harbor.local
          notary: notary.local
        annotations:
          #Update sizes for your needs
          ingress.kubernetes.io/proxy-body-size: "1m"
          ingress.kubernetes.io/ssl-redirect: "true"
          nginx.ingress.kubernetes.io/proxy-body-size: "1m"
          nginx.ingress.kubernetes.io/ssl-redirect: "true"

```
