### ISSUE TITLE
Issues in running harbor with restricted psp

### ISSUE THREAD

**Issue by tvvignesh** [goharbor/harbor-helm#756]
Hi. This is how I have setup psp in my cluster: https://raw.githubusercontent.com/kubernetes/website/master/content/en/examples/policy/restricted-psp.yaml (restricted PSP which disables root access, previlege escalation and more as recommended everywhere)

I am not able to run harbor with this policy set (have tried an entire day).

1) The chart does not have any securityContext and so it fails.

2) Postgres init containers wont work since it runs as user 0 which is denied as per this policy and disabling initcontainers will lead to permission denied for `/var/lib/postgresql/data`

3) I even tried chart from bitnami and even that fails since that also tries to run the initcontainer with user 0 which is not allowed.

This happens for almost all deployments within harbor chart - tried modifying the chart manually but they are leading to different errors.

Can someone please help? I am trying to set harbor up in a psp restricted cluster but am not able to. If anyone has already done it, can I have some reference? Thanks.

CC: @ywk253100 @reasonerjt

**Comment by msiebuhr** [comment]
As to (2), Postgres really _really_ wants to own the folder it's storing data in. Since it is not running as root, it cannot change permissions on the mount (owned by root:postgres, if you set `securityContext -> fsGroup: 999). If you set $PGDATA=/var/lib/postgresql/data/pgdata`, it will create the required sub-folder and thus be the owner of it.

Our minimal deployment made like this:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      securityContext:
        runAsUser: 999 # See https://github.com/docker-library/postgres/blob/bfc5d81c8f5647c690f452dc558e64fddb1802f6/10/Dockerfile
        runAsGroup: 999
        fsGroup: 999
      containers:
        - name: postgres
          image: postgres:10.4
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
```
