### ISSUE TITLE
Add support for Istio

### ISSUE THREAD

**Issue by missnebun** [goharbor/harbor-helm#77]
Would be nice to add support for Istio VirtualService.

**Comment by temporafugiunt** [comment]
I seconds this, I was able to get harbor installed into a cluster that supports ingresses through Istio Gateways and VirtualService definitions rather than a standard Ingress. And I can login to the portal and all the services seem to be functional but no matter what I do I cannot push images into the registry, they always fail for various reasons related to the fact that harbor itself is not in control of the TLS portion of the connection anymore.

**Comment by ruzickap** [comment]
@temporafugiunt - may I ask you to share the commands which you used for installing Istio and Harbor to make Harbor accessible form the "outside" ?

**Comment by ruzickap** [comment]
If someone is interested, here is the working configuration (with helm chart / container upload/download images with working notary):

```bash
helm install --wait --name harbor --namespace harbor-system harbor/harbor --version v1.1.1 \
  --set expose.type=clusterIP \
  --set expose.tls.enabled=true \
  --set expose.tls.secretName=ingress-cert-${LETSENCRYPT_ENVIRONMENT} \
  --set persistence.enabled=false \
  --set externalURL=https://harbor.${MY_DOMAIN} \
  --set harborAdminPassword=password
```

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: harbor-gateway
  namespace: harbor-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http-harbor
      protocol: HTTP2
    hosts:
    - harbor.${MY_DOMAIN}
  - port:
      number: 443
      name: https-harbor
      protocol: HTTPS
    hosts:
    - harbor.${MY_DOMAIN}
    - notary.${MY_DOMAIN}
    tls:
      mode: PASSTHROUGH
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: harbor-http-virtual-service
  namespace: harbor-system
spec:
  hosts:
  - harbor.${MY_DOMAIN}
  gateways:
  - harbor-gateway
  http:
  - match:
    - port: 80
    route:
    - destination:
        host: harbor.harbor-system.svc.cluster.local
        port:
          number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: harbor-https-virtual-service
  namespace: harbor-system
spec:
  hosts:
  - harbor.${MY_DOMAIN}
  gateways:
  - harbor-gateway
  tls:
  - match:
    - port: 443
      sniHosts:
      - harbor.${MY_DOMAIN}
    route:
    - destination:
        host: harbor.harbor-system.svc.cluster.local
        port:
          number: 443
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: harbor-notary-virtual-service
  namespace: harbor-system
spec:
  hosts:
  - notary.${MY_DOMAIN}
  gateways:
  - harbor-gateway
  tls:
  - match:
    - port: 443
      sniHosts:
      - notary.${MY_DOMAIN}
    route:
    - destination:
        host: harbor.harbor-system.svc.cluster.local
        port:
          number: 4443
```

Not sure if it's the right way, but it is working for me...

**Comment by EvertonSA** [comment]
@ruzickap can you explain a little your setup? 

- You have created a secondary Istio gateway only for container registry? In a cloud environment, is this going to provision another load balancer?
- You have defined the letsencrypt cert on the helm definition. Does it mean that you need to provision another letsencrypt cert for Harbor? My letsencrypt cert is in another namespace (istio-system) and I think it should not be shared.

To all: anyone else lucky to have Harbor running on istio?

**Comment by ruzickap** [comment]
My setup is described here: https://ruzickap.github.io/k8s-knative-gitlab-harbor/part-04/
(the document is not completed yet, but it may be still handy)

- Yes Harbor has it's own Istio gateway `harbor-gateway`. No there is only one loadbalancer in my environment.

- I'm using wildcard letsencrypt certificate (`*.mylabs.dev`) (once certificate for all services). The secret with the certificate generated by `cert-manager` is copied form `cert-manager` namespace to all other namespaces by tool called `kubed`.

**Comment by EvertonSA** [comment]
@ruzickap What a beautiful setup mate. Didn't know about kubed, I will give it a try.

**Comment by EvertonSA** [comment]
@ruzickap you have --set persistence.enabled=false  in your helm command, is this because it is a dev environment?

**Comment by ruzickap** [comment]
Yes exactly...

**Comment by jabbors** [comment]
Here's my working configuration. I don't install the nginx service at all and proxy the requests directly to the services from a VirtualService.

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: harbor
spec:
  gateways:
    - wildcard-gateway
  hosts:
    - harbor.${MY_DOMAIN}
  http:
    - match:
        - uri:
            prefix: '/c/'
      route:
        - destination:
            host: harbor-core
    - match:
        - uri:
            prefix: '/api/'
      route:
        - destination:
            host: harbor-core
    - match:
        - uri:
            prefix: '/v2/'
      route:
        - destination:
            host: harbor-registry
            port:
              number: 5000
    - match:
        - uri:
            prefix: '/v1/'
      route:
        - destination:
            host: harbor-registry
            port:
              number: 5000
      fault:
        abort:
          httpStatus: 404
    - match:
        - uri:
            prefix: '/service/'
      route:
        - destination:
            host: harbor-core
    - match:
        - uri:
            prefix: '/chartrepo/'
      route:
        - destination:
            host: harbor-core
    - route:
        - destination:
            host: harbor-portal
```

The gateway is configured to only accept HTTPS traffic and serves wildcard certificate for my domain.

**Comment by tvvignesh** [comment]
Thanks @jabbors The config worked really well.

**Comment by jabbors** [comment]
I updated my post with an additional virtual service fixing the vulnerability scanner.

**Comment by jabbors** [comment]
@dylanhitt no, I'm using token authentication.

**Comment by jabbors** [comment]
Pasted from https://github.com/goharbor/harbor/issues/12560

>I'm currently using harbor 1.10.2 in production behind a Istio VirtualService and with external storage (s3). My Istio configuration is posted in goharbor/harbor-helm#77.
>
>In an attempt to upgrade to version 2.0.1, I've been experimenting in a playground environment with a fresh setup but struggles to figure out why pushed images doesn't show up in the UI. I'm using the same workaround as for version 1.10.2, which is routing /v2/ requests directly to the registry service. I can login to registry just fine (docker login myharbor.domain) and even push and pull images. But the images does not show up in the UI at all.
>
>Anyone who knows what could be up? Does /v2/ requests actually have to go through the core service?

>I eliminated Istio and replace the VirtualService with nginx. Similarly to the VritualService, I configured nginx to proxy /v2/ request directly to the registry service.
>
>Again I was able to push and pull an image but the image does not show up in the UI.

> I've verified that the I can see images in the UI when I deploy harbor 2.0.1 with helm and external storage configured. The only difference with helm and my setup is that I'm using token authentication in favour of the default basic authentication with helm.

**Comment by robbertvdg** [comment]
@jabbors for harbor 2.0 I tried your setup, however I can't get the token authentication to work (401 with docker login). I feel like this might be skipped when routing the request to the registry directly? 

One thing I am not clear of is the wildcard gateway, can you elaborate on that? And did you manage to get it working with harbor 2.0?

**Comment by jabbors** [comment]
> I feel like this might be skipped when routing the request to the registry directly?

Token authentication works and I've been able to push and pull images to a harbor 2.0 setup with istio, but I can't see the images in the web UI.

>One thing I am not clear of is the wildcard gateway, can you elaborate on that?

Below is the definition for the wildcard gateway

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: wildcard-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*.example.com'
    port:
      name: http
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      privateKey: /etc/istio/ingressgateway-certs/tls.key
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
```

`example.com` is of course replaced with a real domain and the certificate exposed by the gateway is a wildcard certificate. This way you can host many services (eg. harbor.example.com, notary.example.com, awesome app.example.com) behind one gateway.

> did you manage to get it working with harbor 2.0?

Not yet. It's been on ice as I've been busy with other tasks. For this week I've dedicated time to debug it further as I recently found another istio related issue regarding tag retention rules and deletion of tags not retained. The issue seems to be similar, a request towards the registry api `/v2/` is sent to the core service, which just acts as a proxy for the registry, but the core application returns a 404 for every request. It does not even reach the registry service. And I attempt to find out why that is and how to possibly fix it.

**Comment by robbertvdg** [comment]
Thanks for your quick response, it is a lot clearer now! What type of token authentication did you use? We have oidc authentication, which has problems routing the /v2 endpoint to the registry.

**Comment by jabbors** [comment]
@robbertvdg we use database authentication.

**Comment by robbertvdg** [comment]
When routing /v2 to registry I see an authorization header in my envoy logs at the registry inbound, however it isn't the token needed for OIDC authentication (is this the default database authentication token?) and the correct token is not retrieved at the /service/token endpoint. 

Routing /v2 to harbor-core does provide the correct token but results in a TLS handshake error at the registry istio-proxy, resulting in a 503. Maybe this will help you debugging.

**Comment by jabbors** [comment]
I've made some progress in my debugging. I was not able to detect any TLS handshake errors at all in the istio-proxies. 

What I did notice was a misconfiguration from our side. We had forgotten to name the service ports with protocols. https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/.

After updating the service manifests with a `http-` prefix for most services. I could eliminate my workaround in the virtual service and direct all traffic directly to the core service.

This is for version 1.10.1 and it did not fix tag deletions through tag retention runs, which I was hoping it should. Nevertheless, I'll continue my debugging and check if I get a working 2.x setup.

**Comment by robbertvdg** [comment]
We also patched these services with `http-` and `tcp-` prefixes. For the record, we have mTLS enabled, route /v2 to core and then see a handshake error between core and the registry after the OIDC token has been retrieved

**Comment by jabbors** [comment]
@diabloxenon there is no need for two gateways and virtual services. I've got it working with only one gateway and virtual service, without exposing the registry directly on `/v2`

At first I had it exposed directly on `/v2` but then I found in misconfiguration in our manifests (lack of protocol in service port name) and route these requests to core exactly as it's proxied in the helm nginx config.

**Comment by diabloxenon** [comment]
@jabbors In the beginning, I have also tried using only one gateway too but the fact is that even after using the same routing config as present in helm nginx config, it still wasn't connecting to the harbor core. Instead, it was showing 404 and redirecting all requests back to harbor portal which didn't made any sense. So, after splitting the gateway into two for core and portal, it worked perfectly fine for me.

Secondly, I have configured it w/o explicitly declaring the protocol in our service manifests and surprisingly, it still worked. I guess there are many more ways to do it.

**Comment by osaffer** [comment]
I would be curious to see your configuration.
I have strange behaviour, the Login page appears, but I cannot login while password is correct.

I m trying to configure with TLS.

**Comment by nfrush** [comment]
Does anyone have an update configuration wise? I'm getting a 404 when attempting to login via Docker and I can't push any helm charts (I'll get a 404 there too).

**Comment by kasim457** [comment]
> 
> 
> If someone is interested, here is the working configuration (with helm chart / container upload/download images with working notary):
> 
> ```shell
> helm install --wait --name harbor --namespace harbor-system harbor/harbor --version v1.1.1 \
>   --set expose.type=clusterIP \
>   --set expose.tls.enabled=true \
>   --set expose.tls.secretName=ingress-cert-${LETSENCRYPT_ENVIRONMENT} \
>   --set persistence.enabled=false \
>   --set externalURL=https://harbor.${MY_DOMAIN} \
>   --set harborAdminPassword=password
> ```
> 
> ```yaml
> apiVersion: networking.istio.io/v1alpha3
> kind: Gateway
> metadata:
>   name: harbor-gateway
>   namespace: harbor-system
> spec:
>   selector:
>     istio: ingressgateway
>   servers:
>   - port:
>       number: 80
>       name: http-harbor
>       protocol: HTTP2
>     hosts:
>     - harbor.${MY_DOMAIN}
>   - port:
>       number: 443
>       name: https-harbor
>       protocol: HTTPS
>     hosts:
>     - harbor.${MY_DOMAIN}
>     - notary.${MY_DOMAIN}
>     tls:
>       mode: PASSTHROUGH
> ---
> apiVersion: networking.istio.io/v1alpha3
> kind: VirtualService
> metadata:
>   name: harbor-http-virtual-service
>   namespace: harbor-system
> spec:
>   hosts:
>   - harbor.${MY_DOMAIN}
>   gateways:
>   - harbor-gateway
>   http:
>   - match:
>     - port: 80
>     route:
>     - destination:
>         host: harbor.harbor-system.svc.cluster.local
>         port:
>           number: 80
> ---
> apiVersion: networking.istio.io/v1alpha3
> kind: VirtualService
> metadata:
>   name: harbor-https-virtual-service
>   namespace: harbor-system
> spec:
>   hosts:
>   - harbor.${MY_DOMAIN}
>   gateways:
>   - harbor-gateway
>   tls:
>   - match:
>     - port: 443
>       sniHosts:
>       - harbor.${MY_DOMAIN}
>     route:
>     - destination:
>         host: harbor.harbor-system.svc.cluster.local
>         port:
>           number: 443
> ---
> apiVersion: networking.istio.io/v1alpha3
> kind: VirtualService
> metadata:
>   name: harbor-notary-virtual-service
>   namespace: harbor-system
> spec:
>   hosts:
>   - notary.${MY_DOMAIN}
>   gateways:
>   - harbor-gateway
>   tls:
>   - match:
>     - port: 443
>       sniHosts:
>       - notary.${MY_DOMAIN}
>     route:
>     - destination:
>         host: harbor.harbor-system.svc.cluster.local
>         port:
>           number: 4443
> ```
> 
> Not sure if it's the right way, but it is working for me...

Hi Team, I was trying to configure harbor with Istio service in on-premise k8s cluster.  We are not using any cert-manager and wildcard certificates.  We have only one domain name something like "example.kasim.com".  I had noticed in the GW and VS services configuration mentioned in this issue (#77), they used harbor.${MY_DOMAIN} in both GW and VS configuration.  Do i have to use same thing with single domain in my case "example.kasim.com".

**Comment by uderik** [comment]
Hello,
here's my working configuration.
harbor installed via helm-operator and **don't add istio injection to harbor namespace**
```
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor-system
spec:
  chart:
    name: harbor
    repository: https://helm.goharbor.io
    version: 1.5.3
  releaseName: harbor
  targetNamespace: harbor-system
  values:
    externalURL: https://harbor.domain.com
    harborAdminPassword: admin123
    persistence:
      enabled: true
```
gateway.yaml
```
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: harbor-http-gateway
  namespace: harbor-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http-harbor
      protocol: HTTP
    hosts:
     - harbor.domain.com
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https-harbor
      protocol: HTTPS
    hosts:
      - harbor.domain.com
    tls:
      mode: SIMPLE
      credentialName: domain.com-certificate
```
vs.yaml
```
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: harbor-http-virtual-service
  namespace: harbor-system
spec:
  gateways:
    - harbor-http-gateway.harbor-system
  hosts:
    - harbor.domain.com
  http:
  - match:
    - uri:
        prefix: '/c/'
    rewrite:
      uri: '/c/'
    route:
      - destination:
          host: harbor-harbor-core
          port:
            number: 80
  - match:
    - uri:
        prefix: '/api/'
    rewrite:
      uri: '/api/'
    route:
      - destination:
          host: harbor-harbor-core
          port:
            number: 80
  - match:
    - uri:
        prefix: '/v2/'
    rewrite:
      uri: '/v2/'
    route:
      - destination:
          host: harbor-harbor-core
          port:
            number: 80
  - match:
    - uri:
        prefix: '/chartrepo/'
    rewrite:
      uri: '/chartrepo/'
    route:
      - destination:
          host: harbor-harbor-core
          port:
            number: 80
  - match:
    - uri:
        prefix: '/service/'
    rewrite:
      uri: '/service/'
    route:
      - destination:
          host: harbor-harbor-core
          port:
            number: 80
  - match:
    - uri:
        prefix: /
    rewrite:
      uri: /
    route:
    - destination:
        host: harbor-harbor-portal
        port:
          number: 80

```

**Comment by kasim457** [comment]
> 
> 
> Thanks @jabbors The config worked really well.

@tvvignesh , I am also trying to expose harbor application with Istio gw and VS.  However, I ended-up with 503 error message.  Could you give me more details of your GW and VS.  I deployed harbor application using helm chart in separate namespace called harbor-system. 

```
helm install --wait  harbor --namespace harbor-system harbor/harbor --version v1.5.1 \
  --set expose.type=clusterIP \
  --set expose.tls.enabled=false \
  --set persistence.enabled=true \
  --set persistence.persistentVolumeClaim.registry.storageClass=rook-ceph-block \
  --set persistence.persistentVolumeClaim.database.storageClass=rook-ceph-block \
  --set persistence.persistentVolumeClaim.jobservice.storageClass=rook-ceph-block \
  --set persistence.persistentVolumeClaim.chartmuseum.storageClass=rook-ceph-block \
  --set persistence.persistentVolumeClaim.redis.storageClass=rook-ceph-block \
  --set persistence.persistentVolumeClaim.trivy.storageClass=rook-ceph-block \
  --set externalURL=http://abc.example.com \
  --set harborAdminPassword=XXXXXXXX
```

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: harbor-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http-harbor
      protocol: HTTP2
    hosts:
    - abc.example.com
  - port:
      number: 443
      name: https-harbor
      protocol: HTTPS
    hosts:
    - abc.example.com
    
    tls:
      mode: SIMPLE


apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: harbor
spec:
  gateways:
    - harbor-gateway
  hosts:
    - abc.example.com
  http:
    - match:
        - uri:
            prefix: '/c/'
      route:
        - destination:
            host: harbor-harbor-harbor-core.harbor-system.svc.cluster.local
    - match:
        - uri:
            prefix: '/api/'
      route:
        - destination:
            host: harbor-harbor-core.harbor-system.svc.cluster.local
    - match:
        - uri:
            prefix: '/v2/'
      route:
        - destination:
            host: harbor-harbor-registry.harbor-system.svc.cluster.local
            port:
              number: 5000
    - match:
        - uri:
            prefix: '/v1/'
      route:
        - destination:
            host: harbor-harbor-registry.harbor-system.svc.cluster.local
            port:
              number: 5000
      fault:
        abort:
          httpStatus: 404
    - match:
        - uri:
            prefix: '/service/'
      route:
        - destination:
            host: harbor-harbor-core.harbor-system.svc.cluster.local
    - match:
        - uri:
            prefix: '/chartrepo/'
      route:
        - destination:
            host: harbor-harbor-core.harbor-system.svc.cluster.local
    - route:
        - destination:
            host: harbor-harbor-portal.harbor-system.svc.cluster.local


```

**Comment by perezjasonr** [comment]
how are you all getting away with not providing the common name?

```
The \"expose.tls.auto.commonName\" is required!" .Values.expose.tls.auto.commonName>:
      error calling required: The "expose.tls.auto.commonName
```

everyone who has clusterIP as the type doesn't seem to be providing it, and yet this is what I'm getting.

**Comment by xinnjie** [comment]
The simplist (and most proper IMO) way to adapt istio gateway is to add a `VirtualService` route traffic to harbor nginx pod, and let nginx dispatch request to different components of a harbor relase. Traffic routes may change over time, if we write routing rules by ourself in the `VritualService`, it may become broken sometime.

Here is the example.


`values.yaml`:

```
expose:
  type: clusterIP
  tls:
    enabled: false
externalURL: "https://harbor.example.domain"
```

`virtualservice.yaml`:

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: harbor-virtualservice
  namespace: harbor
spec:
  gateways:
    - istio-system/gateway
  hosts:
    - "harbor.example.domain"
  http:
    - route:
        - destination:
            host: harbor
            port:
              number: 80
```

`gateway.yaml`:

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http-harbor
        protocol: HTTP
      hosts:
        - "harbor.example.domain"
      tls:
        httpsRedirect: true
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: example-domain-cert
      hosts:
        - "harbor.example.domain"
```
