### ISSUE TITLE
Fail to login the portal 405 (Not Alloweed)

### ISSUE THREAD

**Issue by smart-shore** [goharbor/harbor-helm#779]
When I login portal with default password  `Harbor12345` I get an error that  `Invalid user name or password.`
and I check the browser console it show me `POST http://myhost/c/login 405 (Not Alloweed)`
My browser is `Chrome`, and the helm version I use `1.4.3`

**Comment by Tchoupinax** [comment]
Hello, i have the same issue :(

**Comment by ywk253100** [comment]
Could you check that whether all pods of harbor are running as expected?

**Comment by smart-shore** [comment]
I have fixed  it ,thanks 
I use `istio` as the `ingress controller` and  change zhe `backend` config of `harbor-portal` to the last one finish it 

```yaml
 http:
   paths:
   - backend:
        serviceName: harbor-harbor-portal
        servicePort: 80
```
