### ISSUE TITLE
Helm chart issue - jobservice: readiness probe failed

### ISSUE THREAD

**Issue by fabstao** [goharbor/harbor-helm#819]
Hi!

I can't deploy Harbor using Helm chart, I am using rook-ceph for PVC binding and it works fine, using external PostgreSQL and Redis.

Chart version: v1.5.2

Rancher version: v2.5.3 (using Rancher's manager helm)

Already deployed other Helm charts successfully, including Redis cluster and PostgreSQL using Rancher's Helm.

```
Events:
  Type     Reason                  Age                    From                     Message
  ----     ------                  ----                   ----                     -------
  Warning  FailedScheduling        6m26s (x4 over 6m31s)  default-scheduler        error while running "VolumeBinding" filter plugin for pod "harbor-1-1609346651-harbor-jobservice-577f9c98db-w49gh": pod has unbound immediate PersistentVolumeClaims
  Normal   Scheduled               6m22s                  default-scheduler        Successfully assigned harbor/harbor-1-1609346651-harbor-jobservice-577f9c98db-w49gh to rkem2
  Normal   SuccessfulAttachVolume  6m22s                  attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-a9e3198e-0b16-49a0-a55d-8d0c6a669766"
  Normal   Pulling                 6m                     kubelet                  Pulling image "goharbor/harbor-jobservice:v2.1.2"
  Normal   Pulled                  5m53s                  kubelet                  Successfully pulled image "goharbor/harbor-jobservice:v2.1.2"
  Normal   Created                 2m39s (x2 over 5m50s)  kubelet                  Created container jobservice
  Normal   Started                 2m39s (x2 over 5m50s)  kubelet                  Started container jobservice
  Normal   Pulled                  2m39s                  kubelet                  Container image "goharbor/harbor-jobservice:v2.1.2" already present on machine
  Warning  Unhealthy               55s (x26 over 5m25s)   kubelet                  Readiness probe failed: Get http://10.42.0.223:8080/api/v1/stats: dial tcp 10.42.0.223:8080: connect: connection
```

## Kubernetes version

```
> kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-12T01:09:16Z", GoVersion:"go1.15.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.14", GitCommit:"f238f5142728be4033c37aa0ad69bf806090beae", GitTreeState:"clean", BuildDate:"2020-11-11T13:03:54Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

## kubectl status

```
> kubectl get nodes -o wide
NAME    STATUS   ROLES                      AGE   VERSION    INTERNAL-IP      EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
rkem2   Ready    controlplane,etcd,worker   19d   v1.17.14   192.168.16.133   <none>        Ubuntu 18.04.5 LTS   5.4.0-1032-azure   docker://19.3.6
rkew2   Ready    worker                     19d   v1.17.14   192.168.16.132   <none>        Ubuntu 18.04.5 LTS   5.4.0-1032-azure   docker://19.3.6
rkew3   Ready    worker                     15d   v1.17.14   192.168.16.134   <none>        Ubuntu 18.04.5 LTS   5.4.0-1031-azure   docker://19.3.6
rkew4   Ready    worker                     36h   v1.17.14   192.168.16.135   <none>        Ubuntu 18.04.5 LTS   5.4.0-1031-azure   docker://19.3.6

 > kubectl get pvc -n harbor
NAME                                      STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
data-harbor-1-1609346651-harbor-trivy-0   Bound    pvc-6a27f960-3856-44c3-8ea3-e578a876ff88   5Gi        RWX            rook-cephfs    9m25s
data-pgsql-harbor-postgresql-0            Bound    pvc-5fceaf38-2b58-4fb8-b069-495f13ca0e5f   5Gi        RWO            rook-cephfs    12h
harbor-1-1609346651-harbor-chartmuseum    Bound    pvc-09f9f703-4b02-489b-83f5-a3a0eaace4c7   5Gi        RWX            rook-cephfs    9m26s
harbor-1-1609346651-harbor-jobservice     Bound    pvc-a9e3198e-0b16-49a0-a55d-8d0c6a669766   1Gi        RWX            rook-cephfs    9m26s
harbor-1-1609346651-harbor-registry       Bound    pvc-4888817d-d48a-4f4f-a2da-5c0126cf9ba1   5Gi        RWX            rook-cephfs    9m26s
redis-data-redis-harbor-redis-cluster-0   Bound    pvc-027d0802-be56-40bd-ad01-d469d110cb2d   6Gi        RWX            rook-cephfs    15h
redis-data-redis-harbor-redis-cluster-1   Bound    pvc-a3bb16a1-3197-41b4-abf6-cb50dfafd26a   6Gi        RWX            rook-cephfs    15h
redis-data-redis-harbor-redis-cluster-2   Bound    pvc-f41505e2-a9ee-4eb6-9146-88523c2e5e74   6Gi        RWX            rook-cephfs    15h
redis-data-redis-harbor-redis-cluster-3   Bound    pvc-7ebed9b5-9275-4888-91f3-5f6d9168c889   6Gi        RWX            rook-cephfs    15h
redis-data-redis-harbor-redis-cluster-4   Bound    pvc-aa6ba75f-48ad-4ff3-8780-7aea23cbaeb1   6Gi        RWX            rook-cephfs    15h
redis-data-redis-harbor-redis-cluster-5   Bound    pvc-2e80fd6e-0d8a-4399-9502-0363b5d56c5f   6Gi        RWX            rook-cephfs    15h
```
## Core pod failing:

```
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  10m                    default-scheduler  Successfully assigned harbor/harbor-1-1609346651-harbor-core-7987554f85-s2xl9 to rkew4
  Normal   Pulling    10m                    kubelet            Pulling image "goharbor/harbor-core:v2.1.2"
  Normal   Pulled     9m33s                  kubelet            Successfully pulled image "goharbor/harbor-core:v2.1.2"
  Warning  Unhealthy  8m16s (x4 over 9m16s)  kubelet            Liveness probe failed: HTTP probe failed with statuscode: 503
  Normal   Killing    8m16s (x2 over 9m6s)   kubelet            Container core failed liveness probe, will be restarted
  Warning  Unhealthy  7m56s (x7 over 9m16s)  kubelet            Readiness probe failed: HTTP probe failed with statuscode: 503
  Normal   Created    7m45s (x3 over 9m25s)  kubelet            Created container core
  Normal   Started    7m45s (x3 over 9m25s)  kubelet            Started container core
  Normal   Pulled     7m45s (x2 over 8m35s)  kubelet            Container image "goharbor/harbor-core:v2.1.2" already present on machine
  Warning  Unhealthy  4m56s (x7 over 8m36s)  kubelet            Readiness probe failed: Get http://10.42.3.43:8080/api/v2.0/ping: dial tcp 10.42.3.43:8080: connect: connection refused
```

Please help me ;(

**Comment by fabstao** [comment]
Attaching my values.yml:

```
caSecretName: ''
chartmuseum:
  absoluteUrl: false
  affinity: {}
  enabled: true
  image:
    repository: goharbor/chartmuseum-photon
    tag: v2.1.2
  nodeSelector: {}
  podAnnotations: {}
  replicas: 1
  serviceAccountName: ''
  tolerations: []
clair:
  adapter:
    image:
      repository: goharbor/clair-adapter-photon
      tag: v2.1.2
  affinity: {}
  clair:
    image:
      repository: goharbor/clair-photon
      tag: v2.1.2
  enabled: true
  nodeSelector: {}
  podAnnotations: {}
  replicas: 1
  serviceAccountName: ''
  tolerations: []
  updatersInterval: 12
core:
  affinity: {}
  image:
    repository: goharbor/harbor-core
    tag: v2.1.2
  nodeSelector: {}
  podAnnotations: {}
  replicas: 1
  secret: ''
  secretName: ''
  serviceAccountName: ''
  startupProbe:
    enabled: true
    initialDelaySeconds: 20
  tolerations: []
  xsrfKey: ''
database:
  external:
    clairDatabase: clairdb
    coreDatabase: harbordb
    host: pgsql-harbor-postgresql
    notaryServerDatabase: notarydb
    notarySignerDatabase: notarysignerdb
    password: Rackspace.2020
    port: '5432'
    sslmode: disable
    username: postgres
  internal:
    affinity: {}
    image:
      repository: goharbor/harbor-db
      tag: v2.1.2
    nodeSelector: {}
    password: changeit
    serviceAccountName: ''
    tolerations: []
  maxIdleConns: 50
  maxOpenConns: 1000
  podAnnotations: {}
  type: external
expose:
  clusterIP:
    name: harbor
    ports:
      httpPort: 80
      httpsPort: 443
      notaryPort: 4443
  ingress:
    annotations:
      ingress.kubernetes.io/proxy-body-size: '0'
      ingress.kubernetes.io/ssl-redirect: 'true'
      nginx.ingress.kubernetes.io/proxy-body-size: '0'
      nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    controller: default
    hosts:
      core: harbor.rax.latamps.tech
      notary: notary.rax.latamps.tech
  loadBalancer:
    IP: ''
    annotations: {}
    name: harbor
    ports:
      httpPort: 80
      httpsPort: 443
      notaryPort: 4443
    sourceRanges: []
  nodePort:
    name: harbor
    ports:
      http:
        nodePort: 30002
        port: 80
      https:
        nodePort: 30003
        port: 443
      notary:
        nodePort: 30004
        port: 4443
  tls:
    auto:
      commonName: ''
    certSource: auto
    enabled: true
    secret:
      notarySecretName: ''
      secretName: ''
  type: ingress
externalURL: 'https://harbor.rax.latamps.tech'
harborAdminPassword: Harbor123
imagePullPolicy: IfNotPresent
imagePullSecrets: null
internalTLS:
  certSource: auto
  chartmuseum:
    crt: ''
    key: ''
    secretName: ''
  clair:
    crt: ''
    key: ''
    secretName: ''
  core:
    crt: ''
    key: ''
    secretName: ''
  enabled: false
  jobservice:
    crt: ''
    key: ''
    secretName: ''
  portal:
    crt: ''
    key: ''
    secretName: ''
  registry:
    crt: ''
    key: ''
    secretName: ''
  trivy:
    crt: ''
    key: ''
    secretName: ''
  trustCa: ''
jobservice:
  affinity: {}
  image:
    repository: goharbor/harbor-jobservice
    tag: v2.1.2
  jobLogger: file
  maxJobWorkers: 10
  nodeSelector: {}
  podAnnotations: {}
  replicas: 1
  secret: ''
  serviceAccountName: ''
  tolerations: []
logLevel: info
nginx:
  affinity: {}
  image:
    repository: goharbor/nginx-photon
    tag: v2.1.2
  nodeSelector: {}
  podAnnotations: {}
  replicas: 1
  serviceAccountName: ''
  tolerations: []
notary:
  affinity: {}
  enabled: true
  nodeSelector: {}
  podAnnotations: {}
  secretName: ''
  server:
    image:
      repository: goharbor/notary-server-photon
      tag: v2.1.2
    replicas: 1
    serviceAccountName: ''
  signer:
    image:
      repository: goharbor/notary-signer-photon
      tag: v2.1.2
    replicas: 1
    serviceAccountName: ''
  tolerations: []
persistence:
  enabled: true
  imageChartStorage:
    azure:
      accountkey: base64encodedaccountkey
      accountname: accountname
      container: containername
    disableredirect: false
    filesystem:
      rootdirectory: /storage
    gcs:
      bucket: bucketname
      encodedkey: base64-encoded-json-key-file
    oss:
      accesskeyid: accesskeyid
      accesskeysecret: accesskeysecret
      bucket: bucketname
      region: regionname
    s3:
      bucket: bucketname
      region: us-west-1
    swift:
      authurl: 'https://storage.myprovider.com/v3/auth'
      container: containername
      password: password
      username: username
    type: filesystem
  persistentVolumeClaim:
    chartmuseum:
      accessMode: ReadWriteMany
      existingClaim: ''
      size: 5Gi
      storageClass: 'rook-cephfs'
      subPath: ''
    database:
      accessMode: ReadWriteMany
      existingClaim: ''
      size: 1Gi
      storageClass: 'rook-cephfs'
      subPath: ''
    jobservice:
      accessMode: ReadWriteMany
      existingClaim: ''
      size: 1Gi
      storageClass: 'rook-cephfs'
      subPath: ''
    redis:
      accessMode: ReadWriteMany
      existingClaim: ''
      size: 1Gi
      storageClass: 'rook-cephfs'
      subPath: ''
    registry:
      accessMode: ReadWriteMany
      existingClaim: ''
      size: 5Gi
      storageClass: 'rook-cephfs'
      subPath: ''
    trivy:
      accessMode: ReadWriteMany
      existingClaim: ''
      size: 5Gi
      storageClass: 'rook-cephfs'
      subPath: ''
  resourcePolicy: keep
portal:
  affinity: {}
  image:
    repository: goharbor/harbor-portal
    tag: v2.1.2
  nodeSelector: {}
  podAnnotations: {}
  replicas: 1
  serviceAccountName: ''
  tolerations: []
proxy:
  components:
    - core
    - jobservice
    - clair
    - trivy
  httpProxy: null
  httpsProxy: null
  noProxy: '127.0.0.1,localhost,.local,.internal'
redis:
  external:
    addr: 'redis-harbor-redis-cluster:6379'
    chartmuseumDatabaseIndex: '3'
    clairAdapterIndex: '4'
    coreDatabaseIndex: '0'
    jobserviceDatabaseIndex: '1'
    password: 'Rackspace.2020'
    registryDatabaseIndex: '2'
    sentinelMasterSet: ''
    trivyAdapterIndex: '5'
  internal:
    affinity: {}
    image:
      repository: goharbor/redis-photon
      tag: v2.1.2
    nodeSelector: {}
    serviceAccountName: ''
    tolerations: []
  podAnnotations: {}
  type: external
registry:
  affinity: {}
  controller:
    image:
      repository: goharbor/harbor-registryctl
      tag: v2.1.2
  credentials:
    htpasswd: >-
      harbor_registry_user:$2y$10$9L4Tc0DJbFFMB6RdSCunrOpTHdwhid4ktBJmLD00bYgqkkGOvll3m
    password: harbor_registry_password
    username: harbor_registry_user
  middleware:
    cloudFront:
      baseurl: example.cloudfront.net
      duration: 3000s
      ipfilteredby: none
      keypairid: KEYPAIRID
      privateKeySecret: my-secret
    enabled: false
    type: cloudFront
  nodeSelector: {}
  podAnnotations: {}
  registry:
    image:
      repository: goharbor/registry-photon
      tag: v2.1.2
  relativeurls: false
  replicas: 1
  secret: ''
  serviceAccountName: ''
  tolerations: []
secretKey: not-a-secure-key
trivy:
  affinity: {}
  debugMode: false
  enabled: true
  gitHubToken: ''
  ignoreUnfixed: false
  image:
    repository: goharbor/trivy-adapter-photon
    tag: v2.1.2
  insecure: false
  nodeSelector: {}
  podAnnotations: {}
  replicas: 1
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 512Mi
  serviceAccountName: ''
  severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
  skipUpdate: false
  tolerations: []
  vulnType: 'os,library'
updateStrategy:
  type: RollingUpdate

```
