### ISSUE TITLE
Unable to push docker images

### ISSUE THREAD

**Issue by archit** [goharbor/harbor-helm#834]
In my lab environment, I installed Harbor v2.1.3 using Helm chart 1.5.3 on vSphere. All the pods come up fine as running. I am able to `docker login` as well using the default user/pass. However when I docker push I get an error

```
time="2021-01-13T04:58:40.771087525Z" level=error msg="response completed with error" auth.user.name="harbor_registry_user" err.code=unknown err.detail="filesystem: mkdir /storage/docker: permission denied" err.message="unknown error" go.version=go1.14.13 http.request.host="core.harbor.domain:32669" http.request.id=eb9dfea0-a1d5-4b11-9f91-4e57a7e1fa92 http.request.method=POST http.request.remoteaddr=100.96.2.1 http.request.uri="/v2/library/mongodb/blobs/uploads/" http.request.useragent="docker/20.10.0 go/go1.13.15 git-commit/eeddea2 kernel/4.19.121-linuxkit os/linux arch/amd64 UpstreamClient(Docker-Client/20.10.0 \(darwin\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=88.083098ms http.response.status=500 http.response.written=155 vars.name="library/mongodb"
```

looks like the default volume Mount of /storage is coming up with permissions of root:root

```
➜  helm kubectl get pods
NAME                                           READY   STATUS             RESTARTS   AGE
harbor-harbor-core-77ddb7b564-zzzd8            1/1     Running            2          53m
harbor-harbor-database-0                       1/1     Running            0          53m
harbor-harbor-jobservice-b7f754579-4bwmf       1/1     Running            0          53m
harbor-harbor-notary-server-767456dbb4-bbsr9   1/1     Running            1          53m
harbor-harbor-notary-signer-787589b69d-zr7vk   1/1     Running            1          53m
harbor-harbor-portal-664785787f-jb9xc          1/1     Running            0          53m
harbor-harbor-redis-0                          1/1     Running            0          53m
harbor-harbor-registry-95f87d876-k4w7w         2/2     Running            0          53m
security-context-demo                          0/1     ImagePullBackOff   0          10m
➜  helm kubectl exec -it harbor-harbor-registry-95f87d876-k4w7w -c registry -- ls -l /storage
total 16
drwx------ 2 root root 16384 2021-01-13 04:54 lost+found
➜  helm kubectl exec -it harbor-harbor-registry-95f87d876-k4w7w -c registry -- ls -l /
total 48
lrwxrwxrwx   1 root root    7 2019-05-10 19:07 bin -> usr/bin
drwxr-xr-x   2 root root 4096 2019-05-10 19:07 boot
drwxr-xr-x   5 root root  360 2021-01-13 04:54 dev
drwxr-xr-x   1 root root 4096 2021-01-13 04:54 etc
drwxr-xr-x   1 root root 4096 2021-01-06 11:53 home
lrwxrwxrwx   1 root root    7 2019-05-10 19:07 lib -> usr/lib
lrwxrwxrwx   1 root root    7 2019-05-10 19:07 lib64 -> usr/lib
lrwxrwxrwx   1 root root    9 2019-05-10 19:07 media -> run/media
drwxr-xr-x   4 root root 4096 2020-12-10 22:54 mnt
dr-xr-xr-x 157 root root    0 2021-01-13 04:54 proc
drwxr-x---   2 root root 4096 2020-12-10 22:54 root
drwxr-xr-x   1 root root 4096 2021-01-13 04:54 run
lrwxrwxrwx   1 root root    8 2019-05-10 19:07 sbin -> usr/sbin
lrwxrwxrwx   1 root root    7 2019-05-10 19:07 srv -> var/srv
drwxr-xr-x   3 root root 4096 2021-01-13 04:54 storage
dr-xr-xr-x  13 root root    0 2021-01-11 19:40 sys
drwxrwxrwt   2 root root 4096 2019-05-10 19:07 tmp
drwxr-xr-x   1 root root 4096 2020-12-10 22:54 usr
drwxr-xr-x   1 root root 4096 2020-12-10 22:54 var
➜  helm
```

Any ideas on how to proceed?

**Comment by reasonerjt** [comment]
@archit are you using any vmware product to install the k8s cluster?
It seems for different volume driver the permissions of `/storage` are different.

**Comment by archit** [comment]
@reasonerjt yes. I think I was able to narrow it down to an issue with the vsphere csi  driver. See https://github.com/kubernetes-sigs/vsphere-csi-driver/issues/370

**Comment by linonetwo** [comment]
The fix:

修复PV权限问题
be11f760d54d: Retrying in 1 second 之后 received unexpected HTTP status: 500 Internal Server Error 的问题，看 log 发现是因为报错 filesystem: mkdir /storage/docker: permission denied
进到容器里会发现 /storage 的拥有者是 root，导致 harbor 用户无法正常写入文件。这时可以查看 harbor 用户的 id

```sh
$id -u harbor
10000
```

然后用一个新的 pod 挂载同样的 pv，并例如 busybox 的 root 权限帮它更新文件夹权限，之后就能正常写入了。

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: permission-fix-pod
spec:
  initContainers:
  - name: fix-perms
    image: busybox
    command: ["sh", "-c", "chown -R 10000:10000 /storage"]
    volumeMounts:
    - name: storage-volume
      mountPath: /storage
  containers:
  - name: sleep
    image: busybox
    command: ["sleep", "infinity"]
    volumeMounts:
    - name: storage-volume
      mountPath: /storage
  volumes:
  - name: storage-volume
    persistentVolumeClaim:
      claimName: harbor-registry
```
