### ISSUE TITLE
Upgrade failed with in Trivy component

### ISSUE THREAD

**Issue by lizhongit** [goharbor/harbor-helm#845]
OS: Debian 10
Kubernetes: v1.18.14
Docker: 20.10.2
Helm: v3.5.0

values.yaml:

```yaml
notary:
  enabled: true

trivy:
  replicas: 2

database:
  external:
    host: postgresql
    password: "123456"
    username: postgres
  type: external

expose:
  annotations:
    ingress.kubernetes.io/proxy-body-size: "0"
    # ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: traefik
  ingress:
    hosts:
      core:  <MY_DOMAIN>
      notary: <MY_NOTARY_DOMAIN>
  tls:
    enabled: false
  type: ingress
externalURL: <MY_DOMAIN>
harborAdminPassword: <MY_PASSWORD>
persistence:
  persistentVolumeClaim:
    chartmuseum:
      existingClaim: harbor-chartmuseum
    jobservice:
      existingClaim: harbor-jobservice
    redis:
      existingClaim: harbor-redis
    registry:
      existingClaim: harbor-registry
    trivy:
      existingClaim: harbor-trivy


core:
  replicas: 1

jobservice:
  replicas: 1
  
registry:
  replicas: 1

chartmuseum:
  replicas: 1

clair:
  replicas: 1

```

Current version: 2.0.0

I catch some errors when I upgrading with helm

```shell
# helm upgrade --namespace harbor harbor -f values.yaml harbor/harbor
Error: UPGRADE FAILED: cannot patch "harbor-harbor-trivy" with kind StatefulSet: StatefulSet.apps "harbor-harbor-trivy" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
```

I have no idea on it, How can I upgrade my Harbor application?
