### ISSUE TITLE
status of jobservice is CrashLoopBackOff  and always restart and Failed to load and run worker pool: connect to redis server timeout

### ISSUE THREAD

**Issue by dotbalo** [goharbor/harbor-helm#87]
I am trying to deploy harbor using 0.3.0 branch, but I found that jobservice always restart and harbor-ui cannot connect internal Redis.
just like：
````
2018-11-16T15:57:24Z [FATAL] [service_logger.go:73]: Failed to load and run worker pool: connect to redis server timeout: dial tcp 10.96.137.238:0: i/o timeout

[root@k8s-master01 harbor-helm]# kubectl get pod -n harbor
NAME                                              READY     STATUS             RESTARTS   AGE
harbor-v1-harbor-adminserver-5b59c684b4-rwgvs     1/1       Running            2          17m
harbor-v1-harbor-chartmuseum-699cf6599-4bb5p      1/1       Running            0          17m
harbor-v1-harbor-clair-6d9bb84485-c829n           1/1       Running            2          17m
harbor-v1-harbor-database-0                       1/1       Running            0          17m
harbor-v1-harbor-jobservice-5c9496775d-8nfkp      0/1       CrashLoopBackOff   6          17m
harbor-v1-harbor-notary-server-5fb65b6866-6scfj   1/1       Running            0          17m
harbor-v1-harbor-notary-signer-5bfcfcd5cf-clslv   1/1       Running            0          17m
harbor-v1-harbor-registry-75c9b6b457-rzdd5        1/1       Running            0          17m
harbor-v1-harbor-ui-5974bd5549-kvcjk              1/1       Running            5          17m
harbor-v1-redis-84dffd8574-l6swk                  1/1       Running            0          17m
````
10.96.137.238:0: is redis ClusterIP，Look like there is no port of redis. 

So I open templates/_helpers.tpl, and I found：
````
host:port,pool_size,password
100 is the default value of pool size
*/}}
{{- define "harbor.redisForUI" -}}
  {{- template "harbor.redis.host" . }}:{{ template "harbor.redis.port" . }},100,{{ template "harbor.redis.password" . }}
{{- end -}}
````

and：
````
{{- define "harbor.redis.host" -}}
  {{- if .Values.redis.external.enabled -}}
    {{- .Values.redis.external.host -}}
  {{- else -}}
    {{- .Release.Name }}-redis-master
  {{- end -}}
{{- end -}}

{{- define "harbor.redis.port" -}}
  {{- if .Values.redis.external.enabled -}}
    {{- .Values.redis.external.port -}}
  {{- else -}}
    {{- .Values.redis.master.port }}
  {{- end -}}
{{- end -}}
````
Finally I open values.yaml, and found the default configuration of redis
````
redis:
  # if external Redis is used, set "external.enabled" to "true"
  # and fill the connection informations in "external" section.
  # or the internal Redis will be used
  usePassword: false
  password: "changeit"
  cluster:
    enabled: false
  master:
    persistence:
      enabled: *persistence_enabled
      storageClass: "gluster-heketi"
      accessMode: ReadWriteOnce
      size: 1Gi
  persistence:
    # existingClaim:
````
but there is no redis.master.port. Then I add port: 6379 to the values.yaml.
````
redis:
  # if external Redis is used, set "external.enabled" to "true"
  # and fill the connection informations in "external" section.
  # or the internal Redis will be used
  usePassword: false
  password: "changeit"
  cluster:
    enabled: false
  master:
    port: 6379
    persistence:
      enabled: *persistence_enabled
      storageClass: "gluster-heketi"
      accessMode: ReadWriteOnce
      size: 1Gi
  persistence:
    # existingClaim:
````
and reinstall harbor
````
[root@k8s-master01 harbor-helm]# helm del --purge harbor-v1
[root@k8s-master01 harbor-helm]# helm install --name harbor-v1 .   --wait --timeout 1500 --debug --namespace harbor
````
Harbor is working, and I can access harborUI.
![image](https://user-images.githubusercontent.com/25141522/48611697-c81b6a80-e9c1-11e8-99da-6ea6d9482a0d.png)

I just want to ask if this is a bug and everything ?
