### ISSUE TITLE
[Bug] Database data directory permission

### ISSUE THREAD

**Issue by electrical** [goharbor/harbor-helm#876]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
After upgrading I'm getting the following error of the database instance:

```
FATAL: data directory "/var/lib/postgresql/data/pgdata" has group or world access
DETAIL: Permissions should be u=rwx (0700).
```
Perhaps it would be easy to chmod it before starting up to ensure we have the right permissions?

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.1.3 -> 2.2.0
- Kubernetes: 1.19.7

**Additional context:**

The database instance uses Persisted storage backed by Ceph.

Relevant helm value:
```
    database:
      existingClaim: ""
      storageClass: "rook-ceph-block"
      subPath: "data"
      accessMode: ReadWriteOnce
      size: 1Gi
```

After debugging the issue a bit further I see in the init container it creates the data directory if it doesn't exist and ensures it's created with `0700` permissions.
Unfortunately we don't enforce it once the directory exists.
My suggestion is to replace the `|| true` at the end and convert that into `|| chmod 700 $datadirectory && true`

Note: I first reported this under https://github.com/goharbor/harbor/issues/14354 but was requested to move it here as it's specific to the helm chart deployment.
