### ISSUE TITLE
notary ingress missing tls secret when using custom secret

### ISSUE THREAD

**Issue by wu105** [goharbor/harbor-helm#879]
helm3 install ht harbor/harbor --version 1.5.2 --set redis.image.pullPolicy=IfNotPresent --set expose.tls.secret.secretName=tls-ingress-harbor ...
leads to 
```
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    annotations:
      ingress.kubernetes.io/proxy-body-size: "0"
      ingress.kubernetes.io/ssl-redirect: "true"
      meta.helm.sh/release-name: ht
      meta.helm.sh/release-namespace: harbor
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    creationTimestamp: "2021-03-04T22:13:39Z"
    generation: 1
    labels:
      app: harbor
      app.kubernetes.io/managed-by: Helm
      chart: harbor
      heritage: Helm
      release: ht
 ...
  spec:
    rules:
    - host: notary.va.xyz.com
      http:
        paths:
        - backend:
            serviceName: ht-harbor-notary-server
            servicePort: 4443
          path: /
          pathType: ImplementationSpecific
    tls:
    - hosts:
      - notary.va.xyz.com
  status:
    loadBalancer:
      ingress:
      - ip: 123.4.56.78
```
while the ingress for harbor...com seems ok.
