### ISSUE TITLE
harbor 2.2.1:  docker can push and login  but can't search

### ISSUE THREAD

**Issue by httaotao** [goharbor/harbor-helm#934]
hello, everyone , I used helm to install harbor and pushed a image into project.
but there are error when use command  to search 

```
$ sudo docker search  dev-harbor.xxxx/public/kadalu/kadalu-operator:devel
Error response from daemon: error decoding registry search results: invalid character '<' looking for beginning of value
```

it can login in and push ,but can't search by docker.

here are my values.yaml,we don't use  notary ,trivy and chartmuseum.
of course , we use harbor by http and proxy https by nginx  in front of  harbor.

```
expose:
  type: ingress
  ingress:
    hosts:
      core: dev-harbor.xxxx
      notary: notary.harbor.domain
    controller: default
    annotations:
       ingress.kubernetes.io/ssl-redirect: "false"
       ingress.kubernetes.io/proxy-body-size: "0"
       nginx.ingress.kubernetes.io/ssl-redirect: "false"
       nginx.ingress.kubernetes.io/proxy-body-size: "0"


externalURL: https://dev-harbor.xxxx


imagePullPolicy: IfNotPresent


updateStrategy:
  type: RollingUpdate


logLevel: debug


harborAdminPassword: "xxxx"


caSecretName: ""


secretKey: "not-a-secure-key"


proxy:
  httpProxy:
  httpsProxy:
  noProxy: 127.0.0.1,localhost,.local,.internal
  components:
    - core
    - jobservice
    - trivy


nginx:
  image:
    repository: xxxx/goharbor/nginx-photon
    tag: v2.2.1
  serviceAccountName: ""
  replicas: 1
  nodeSelector: {}
  tolerations: []
  affinity: {}
  ## Additional deployment annotations
  podAnnotations: {}

portal:
  image:
    repository: xxxx/goharbor/harbor-portal
    tag: v2.2.1
  serviceAccountName: ""
  replicas: 1
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podAnnotations: {}

core:
  image:
    repository: xxxx/goharbor/harbor-core
    tag: v2.2.1
  # set the service account to be used, default if left empty
  serviceAccountName: ""
  replicas: 1
  startupProbe:
    enabled: true
    initialDelaySeconds: 10
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podAnnotations: {}
  secret: ""
  secretName: ""
  xsrfKey: ""

jobservice:
  image:
    repository: xxx/goharbor/harbor-jobservice
    tag: v2.2.1
  replicas: 1
  serviceAccountName: ""
  maxJobWorkers: 10
  jobLoggers:
    - file
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podAnnotations: {}
  secret: ""

registry:
  serviceAccountName: ""
  registry:
    image:
      repository:  xxxxx/goharbor/registry-photon
      tag: v2.2.1
  controller:
    image:
      repository: xxxx/goharbor/harbor-registryctl
      tag: v2.2.1
  replicas: 1
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podAnnotations: {}
  secret: ""
  relativeurls: false
  credentials:
    username: "harbor_registry_user"
    password: "harbor_registry_password"
    htpasswd: "harbor_registry_user:$2y$10$9L4Tc0DJbFFMB6RdSCunrOpTHdwhid4ktBJmLD00bYgqkkGOvll3m"
  middleware:
    enabled: false
    type: cloudFront
    cloudFront:
      baseurl: example.cloudfront.net
      keypairid: KEYPAIRID
      duration: 3000s
      ipfilteredby: none
      # The secret key that should be present is CLOUDFRONT_KEY_DATA, which should be the encoded private key
      # that allows access to CloudFront
      privateKeySecret: "my-secret"
```

here are  the pod info 
```
# kubectl -n project-harbor  get pods 
NAME                                       READY   STATUS    RESTARTS   AGE
harbor-harbor-core-7b7754c989-q4j9w        1/1     Running   1          29m
harbor-harbor-database-0                   1/1     Running   0          29m
harbor-harbor-jobservice-98bcb9889-pkbg9   1/1     Running   0          29m
harbor-harbor-portal-dc66dc656-sz5tl       1/1     Running   0          29m
harbor-harbor-redis-0                      1/1     Running   0          29m
harbor-harbor-registry-599d96458d-qbkxf    2/2     Running   0          29m
```
