### ISSUE TITLE
ingress annotations when expose.tls.certSource is none

### ISSUE THREAD

**Issue by abdennour** [goharbor/harbor-helm#975]
what will be the values of `expose.ingress.annotations`  when `expose.tls.certSource` is `none` ?

the defaults one are : 
```yaml
    annotations:
      # note different ingress controllers may require a different ssl-redirect annotation
      # for Envoy, use ingress.kubernetes.io/force-ssl-redirect: "true" and remove the nginx lines below
      ingress.kubernetes.io/ssl-redirect: "true"
      ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
```

But this will not work when offloading TLS to the inrgess controller
