### ISSUE TITLE
[feature request] support configuring OIDC thru helm

### ISSUE THREAD

**Issue by abdennour** [goharbor/harbor-helm#977]
## overview

Configuration as code can be achieved easily in kubernetes environment.
OIDC is an admin configuration. This thread is about automating adding this configuration thru helm values.
values.yaml should consider the following and apply the configuration in idempotent fashion:

- OIDC Provider Name: 
- OIDC Endpoint:
- OIDC Client ID:
- OIDC Client Secret: 
- Group Claim Name: 
- OIDC Admin Group: 
- OIDC Scope: 
- Verify Certificate:
- Automatic Onboarding: 
- Username Claim: 

## expected values.yaml 

```yaml
oidc:
  enabled: true
  name: ....
  endpoint: 
  clientId: 
  secretId:
  ...... 

```
