### ISSUE TITLE
[feature request] support configuring OIDC thru helm

### ISSUE THREAD

**Issue by abdennour** [goharbor/harbor-helm#978]
## overview

Configuration as code can be achieved easily in kubernetes environment.
OIDC is an admin configuration. This thread is about automating adding this configuration thru helm values.
values.yaml should consider the following and apply the configuration in idempotent fashion:

- OIDC Provider Name: 
- OIDC Endpoint:
- OIDC Client ID:
- OIDC Client Secret: 
- Group Claim Name: 
- OIDC Admin Group: 
- OIDC Scope: 
- Verify Certificate:
- Automatic Onboarding: 
- Username Claim: 

## expected values.yaml 

```yaml
oidc:
  enabled: true
  name: ....
  endpoint: 
  clientId: 
  secretId:
  ...... 

```

**Comment by reasonerjt** [comment]
Since Harbor v2.3.0 you can set the configuration by setting a JSON in an env var, check the section: 
"Configure Users Settings using an Environment Variable":
https://goharbor.io/docs/edge/install-config/configure-user-settings-cli/

This is deliberately not exposed in values.yaml of the chart b/c we expect only users will only write script to set the env in the pipeline, not set it manually.

For your requirement, you can write a script update the template https://github.com/goharbor/harbor-helm/blob/master/templates/core/core-dpl.yaml to add this env var.

**Comment by reasonerjt** [comment]
Closing this one as the question is answered.

**Comment by lknite** [comment]
is an environment variable still the right solution?  seems the url provided to the solution no longer exists

**Comment by lknite** [comment]
I noticed the bitnami helm chart of harbor adds a values.yaml item to pass along a configuration as json, might it be good to add something similar to this one?

https://github.com/bitnami/charts/blob/main/bitnami/harbor/values.yaml

![image](https://github.com/goharbor/harbor-helm/assets/92187614/4a3c3093-459b-446a-a075-35771b77c729)

**Comment by pck** [comment]
https://github.com/goharbor/website/blob/release-2.10.0/docs/install-config/configure-system-settings-cli.md#harbor-configuration-items

**Comment by polarAli** [comment]
> Example for someone else who ends up here:
> 
> ```
>   core:
>     extraEnvVars:
>     - name: configOverwriteJson
>       value: |
>         {
>           "auth_mode": "oidc_auth",
>           "oidc_name": "keycloak",
>           "oidc_endpoint": "https://keycloak.vc-prod.k.home.net/realms/home.net",
>           "oidc_groups_claim": "groups",
>           "oidc_admin_group": "k-prod-app-harbor-admin",
>           "oidc_client_id": "defaultwithclientkey",
>           "oidc_client_secret": "asdfasdfasdfasdfasddfasdfasdfasdf",
>           "oidc_scope": "openid,email,profile,offline_access",
>           "oidc_verify_cert": "false",
>           "oidc_auto_onboard": "true",
>           "oidc_user_claim": "preferred_username"
>         }
> ```

The env name has changed to CONFIG_OVERWRITE_JSON. So a working example in the 1.13.3 version of the Helm chart is:
```yaml
  core:
    extraEnvVars:
    - name: CONFIG_OVERWRITE_JSON
      value: |
        {
          "auth_mode": "oidc_auth",
          "oidc_name": "keycloak",
          "oidc_endpoint": "https://keycloak.vc-prod.k.home.net/realms/home.net",
          "oidc_groups_claim": "groups",
          "oidc_admin_group": "k-prod-app-harbor-admin",
          "oidc_client_id": "defaultwithclientkey",
          "oidc_client_secret": "asdfasdfasdfasdfasddfasdfasdfasdf",
          "oidc_scope": "openid,email,profile,offline_access",
          "oidc_verify_cert": "false",
          "oidc_auto_onboard": "true",
          "oidc_user_claim": "preferred_username"
        }
```

**Comment by sule26** [comment]
> > Example for someone else who ends up here:
> > ```
> >   core:
> >     extraEnvVars:
> >     - name: configOverwriteJson
> >       value: |
> >         {
> >           "auth_mode": "oidc_auth",
> >           "oidc_name": "keycloak",
> >           "oidc_endpoint": "https://keycloak.vc-prod.k.home.net/realms/home.net",
> >           "oidc_groups_claim": "groups",
> >           "oidc_admin_group": "k-prod-app-harbor-admin",
> >           "oidc_client_id": "defaultwithclientkey",
> >           "oidc_client_secret": "asdfasdfasdfasdfasddfasdfasdfasdf",
> >           "oidc_scope": "openid,email,profile,offline_access",
> >           "oidc_verify_cert": "false",
> >           "oidc_auto_onboard": "true",
> >           "oidc_user_claim": "preferred_username"
> >         }
> > ```
> 
> The env name has changed to CONFIG_OVERWRITE_JSON. So a working example in the 1.13.3 version of the Helm chart is:
> 
>   core:
>     extraEnvVars:
>     - name: CONFIG_OVERWRITE_JSON
>       value: |
>         {
>           "auth_mode": "oidc_auth",
>           "oidc_name": "keycloak",
>           "oidc_endpoint": "https://keycloak.vc-prod.k.home.net/realms/home.net",
>           "oidc_groups_claim": "groups",
>           "oidc_admin_group": "k-prod-app-harbor-admin",
>           "oidc_client_id": "defaultwithclientkey",
>           "oidc_client_secret": "asdfasdfasdfasdfasddfasdfasdfasdf",
>           "oidc_scope": "openid,email,profile,offline_access",
>           "oidc_verify_cert": "false",
>           "oidc_auto_onboard": "true",
>           "oidc_user_claim": "preferred_username"
>         }

Is there a way of doing this without exposing `the oidc_client_secret` value?

**Comment by Kras4ooo** [comment]
Let me put my two cents too, if someone tries to use secret:
```
  extraEnvVars:
    - name: CONFIG_OVERWRITE_JSON
      valueFrom:
        secretKeyRef:
          name: <secret-name>
          key: <secret-key-name>
```
